// 📝 Auto-generated by E2E-Autogen
// 🔧 Generated from: TC-2.1, TC-2.2

import { test } from "@playwright/test";

test.skip("[TC-2.1] 홈 화면", async ({ page }) => {
  await test.step.skip("[TC-2.1.1] 사이드바 대표 아이콘 클릭 -> 홈 화면으로 이동한다", async () => {
      // 📍 UI Path: 홈 화면

      // 🎬 When: 사이드바 대표 아이콘 클릭
    
      // ✅ Then: 홈 화면으로 이동한다

    });

  await test.step.skip("[TC-2.1.2] 사이드 요약 패널 클릭 -> 사이드바가 열림/닫힘 상태로 변화한다", async () => {
      // 📍 UI Path: 홈 화면

      // 🎬 When: 사이드 요약 패널 클릭
    
      // ✅ Then: 사이드바가 열림/닫힘 상태로 변화한다

    });

  await test.step.skip("[TC-2.1.3] 수학 튜터 카드 선택 -> 수학 튜터 온보딩 페이지로 이동한다", async () => {
      // 📍 UI Path: 홈 화면 > 수학 튜터 온보딩

      // 🎬 When: 수학 튜터 카드 선택
    
      // ✅ Then: 수학 튜터 온보딩 페이지로 이동한다

    });

  await test.step.skip("[TC-2.1.4] 영어 튜터 카드 선택 -> 영어 튜터 온보딩 페이지로 이동한다", async () => {
      // 📍 UI Path: 홈 화면 > 영어 튜터 온보딩

      // 🎬 When: 영어 튜터 카드 선택
    
      // ✅ Then: 영어 튜터 온보딩 페이지로 이동한다

    });
});

test.skip("[TC-2.2] 사이드바", async ({ page }) => {
  await test.step.skip("[TC-2.2.1] 유저 아이콘 클릭 -> 유저 정보(이름, 학년)와 서비스 기본 설정(대시보드, 테마)이 노출된다", async () => {
      // 📍 UI Path: 사이드바

      // 🎬 When: 유저 아이콘 클릭
    
      // ✅ Then: 유저 정보(이름, 학년)와 서비스 기본 설정(대시보드, 테마)이 노출된다

    });

  await test.step.skip("[TC-2.2.3] 테마 클릭 -> 라이트/다크 모드 선택 depth가 노출된다", async () => {
      // 📍 UI Path: 사이드바 > 유저 아이콘 > 테마

      // 🎬 When: 테마 클릭
    
      // ✅ Then: 라이트/다크 모드 선택 depth가 노출된다

    });

  await test.step.skip("[TC-2.2.4] 테마 클릭 -> 초기 테마는 사용자의 기기 설정에 따른다", async () => {
      // 📍 UI Path: 사이드바 > 유저 아이콘 > 테마

      // 🎬 When: 테마 클릭
    
      // ✅ Then: 초기 테마는 사용자의 기기 설정에 따른다

    });

  await test.step.skip("[TC-2.2.5] 테마 클릭 -> 사용자가 원하는 모드를 클릭하면 테마 설정이 변화한다", async () => {
      // 📍 UI Path: 사이드바 > 유저 아이콘 > 테마

      // 🎬 When: 테마 클릭
    
      // ✅ Then: 사용자가 원하는 모드를 클릭하면 테마 설정이 변화한다

    });

  await test.step.skip("[TC-2.2.7] 로그아웃 클릭 -> 클로바 튜터 계정 관리 페이지로 이동한다", async () => {
      // 📍 UI Path: 사이드바 > 유저 아이콘 > 로그아웃

      // 🎬 When: 로그아웃 클릭
    
      // ✅ Then: 클로바 튜터 계정 관리 페이지로 이동한다

    });
});