/**
 * CLOVA Tutor
 * Copyright (c) 2026-present NAVER Cloud Corp.
 * MIT
 */

export const ONBOARDING_QUESTIONS = {
  math: {
    '3': [
      { id: 'math-3-1', prompt: '458 + 267을 어떻게 하면 쉽게 계산할 수 있어?' },
      { id: 'math-3-2', prompt: '902 − 465는 왜 받아내림이 필요한 거야?' },
      { id: 'math-3-3', prompt: '암산으로 399 + 201을 빨리 계산하는 방법 알려줘.' },
      { id: 'math-3-4', prompt: '7 × 8은 왜 56이 되는 거야?' },
      { id: 'math-3-5', prompt: '3 × 4랑 4 × 3은 왜 같은 값이야?' },
      { id: 'math-3-6', prompt: '9단을 쉽게 외우는 방법이 있을까?' },
      { id: 'math-3-7', prompt: '사탕 12개를 3명에게 똑같이 나누면 왜 4개씩이야?' },
      { id: 'math-3-8', prompt: '나눗셈이 곱셈이랑 어떻게 연결되는지 알려줘.' },
      { id: 'math-3-9', prompt: '1/2이랑 1/4 중에 어떤 게 더 커?' },
      { id: 'math-3-10', prompt: '피자를 8조각으로 나누면 3조각은 분수로 어떻게 써?' },
      { id: 'math-3-11', prompt: '직사각형의 둘레는 왜 네 변을 다 더해야 해?' },
      { id: 'math-3-12', prompt: '1m는 1cm보다 얼마나 긴 거야?' },
      { id: 'math-3-13', prompt: '정사각형이랑 직사각형은 뭐가 달라?' },
      { id: 'math-3-14', prompt: '삼각형은 꼭 변이 3개여야 해?' },
      { id: 'math-3-15', prompt: '3시 45분에서 20분이 지나면 몇 시야?' },
      { id: 'math-3-16', prompt: '1시간 30분은 왜 90분이야?' },
      { id: 'math-3-17', prompt: '500원짜리 동전 4개는 얼마야?' },
      { id: 'math-3-18', prompt: '1200원짜리 물건을 사고 5000원을 내면 거스름돈은 얼마야?' },
      { id: 'math-3-19', prompt: '막대그래프는 왜 사용하는 거야?' },
      { id: 'math-3-20', prompt: '숫자 2, 4, 6, 8을 한 번씩만 써서 가장 큰 네 자리 수를 만드는 방법은 뭐야?' },
    ],
    '4': [
      { id: 'math-4-1', prompt: '3,456 + 2,789는 얼마야?' },
      { id: 'math-4-2', prompt: '8,000 − 4,635는 얼마야?' },
      { id: 'math-4-3', prompt: '324 × 3은 어떻게 계산해?' },
      { id: 'math-4-4', prompt: '936 ÷ 4는 얼마가 나와?' },
      { id: 'math-4-5', prompt: '16 × 25는 어떤 방법으로 계산하면 쉬울까?' },
      { id: 'math-4-6', prompt: '3/5랑 4/5 중에 어떤 분수가 더 커?' },
      { id: 'math-4-7', prompt: '2/4를 가장 간단한 분수로 줄이면 어떻게 돼?' },
      { id: 'math-4-8', prompt: '0.8을 분수로 바꾸면 어떻게 써?' },
      { id: 'math-4-9', prompt: '1.7 + 2.35는 얼마야?' },
      { id: 'math-4-10', prompt: '5.0 − 1.86은 얼마야?' },
      { id: 'math-4-11', prompt: '가로가 10cm, 세로가 6cm인 직사각형의 둘레는 얼마야?' },
      { id: 'math-4-12', prompt: '한 변의 길이가 7cm인 정사각형의 둘레는 얼마야?' },
      { id: 'math-4-13', prompt: '30°, 90°, 120° 중에서 둔각은 어느 거야?' },
      { id: 'math-4-14', prompt: '지금 시간이 2시 25분이면, 40분 뒤는 몇 시 몇 분이야?' },
      { id: 'math-4-15', prompt: '3시간 20분은 모두 몇 분이야?' },
      { id: 'math-4-16', prompt: '2,500원짜리 연필을 4자루 사면 모두 얼마야?' },
      { id: 'math-4-17', prompt: '10,000원을 내고 6,780원어치를 샀다면 거스름돈은 얼마야?' },
      { id: 'math-4-18', prompt: '학생 4명의 키가 135cm, 140cm, 145cm, 150cm일 때 평균은 얼마야?' },
      { id: 'math-4-19', prompt: '사과를 하루에 5개씩 6일 동안 먹으면 모두 몇 개를 먹은 거야?' },
      { id: 'math-4-20', prompt: '한 상자에 12개씩 들어 있는 초콜릿이 7상자 있다면 초콜릿은 모두 몇 개일까?' },
    ],
    '7': [
      { id: 'math-7-1', prompt: '-3 + 7은 왜 4가 되는 거야?' },
      { id: 'math-7-2', prompt: '5 - 12는 왜 음수가 되는 거야?' },
      { id: 'math-7-3', prompt: '(-4) × 3은 어떻게 계산해?' },
      { id: 'math-7-4', prompt: '(-18) ÷ 6은 얼마야?' },
      { id: 'math-7-5', prompt: 'x + 5 = 12에서 x는 어떻게 구해?' },
      { id: 'math-7-6', prompt: '3x = 21일 때 x는 얼마야?' },
      { id: 'math-7-7', prompt: '2x + 3 = 11 같은 식은 어떤 순서로 풀어야 해?' },
      { id: 'math-7-8', prompt: '5x - 2x는 왜 3x가 되는 거야?' },
      { id: 'math-7-9', prompt: 'a + a + a는 문자 하나로 어떻게 나타내?' },
      { id: 'math-7-10', prompt: '한 개에 1,200원인 공책을 x권 샀을 때 총 금액은 어떻게 식으로 나타내?' },
      { id: 'math-7-11', prompt: '비가 2 : 5일 때 전체가 14라면 각각 얼마야?' },
      { id: 'math-7-12', prompt: '4km를 20분에 갔다면 1분에 몇 m를 간 거야?' },
      { id: 'math-7-13', prompt: '원의 반지름이 7cm일 때 지름은 얼마야?' },
      { id: 'math-7-14', prompt: '정삼각형 한 변이 6cm일 때 둘레는 얼마야?' },
      { id: 'math-7-15', prompt: '점 A(2, 3)는 좌표평면의 몇 사분면에 있어?' },
      { id: 'math-7-16', prompt: '점 B(-4, 5)는 왜 y축 위에 있지 않은 거야?' },
      { id: 'math-7-17', prompt: 'x = 2일 때 2x + 3의 값은 얼마야?' },
      { id: 'math-7-18', prompt: '연속된 세 자연수의 합이 45일 때 이 세 수는 어떻게 구해?' },
      { id: 'math-7-19', prompt: '길이 10cm 막대를 2 : 3으로 나누면 각각 몇 cm야?' },
      { id: 'math-7-20', prompt: '어떤 수에 7을 더했더니 15가 됐다면 그 수는 어떻게 구해?' },
    ],
    '10': [
      { id: 'math-10-1', prompt: '2x - 5 = 7에서 x는 어떻게 구해?' },
      { id: 'math-10-2', prompt: '3(x - 2) = 2x + 4는 어떤 순서로 풀어야 해?' },
      { id: 'math-10-3', prompt: 'x² - 5x + 6 = 0의 해는 어떻게 찾는 거야?' },
      { id: 'math-10-4', prompt: '이차방정식은 왜 항상 해가 2개 이하로 나오는 거야?' },
      { id: 'math-10-5', prompt: '(x + 3)(x - 2)는 전개하면 어떻게 돼?' },
      { id: 'math-10-6', prompt: 'x² - 9는 어떤 식으로 인수분해할 수 있어?' },
      { id: 'math-10-7', prompt: 'x = -2일 때 x² + 3x - 1의 값은 얼마야?' },
      { id: 'math-10-8', prompt: 'y = 2x + 1은 어떤 모양의 그래프가 나와?' },
      { id: 'math-10-9', prompt: 'y = -x + 3에서 x가 2일 때 y는 얼마야?' },
      { id: 'math-10-10', prompt: 'y = x²의 그래프는 왜 U자 모양이야?' },
      { id: 'math-10-11', prompt: 'y = x² - 4의 그래프는 y = x²랑 뭐가 달라져?' },
      { id: 'math-10-12', prompt: '이차함수의 꼭짓점은 왜 중요한 거야?' },
      { id: 'math-10-13', prompt: '두 직선이 평행하다는 건 기울기가 같다는 뜻이야?' },
      { id: 'math-10-14', prompt: '점 A(2, 3)과 점 B(5, 7) 사이의 x좌표 차이는 얼마야?' },
      { id: 'math-10-15', prompt: '2x + 3 > 7 같은 부등식은 어떻게 풀어?' },
      { id: 'math-10-16', prompt: 'x² - 5x + 6 = 0에서 해를 구할 때 왜 인수분해를 먼저 하는 거야?' },
      { id: 'math-10-17', prompt: '수열 2, 5, 8, 11, … 은 어떤 규칙을 가진 수열이야?' },
      { id: 'math-10-18', prompt: '첫째항이 3이고 공차가 4인 등차수열의 다섯째항은 얼마야?' },
      { id: 'math-10-19', prompt: '어떤 수의 제곱이 16일 때 그 수는 왜 2개가 나와?' },
      { id: 'math-10-20', prompt: '문제에서 최댓값이나 최솟값이 나오면 어떤 걸 먼저 찾아야 해?' },
    ],
  },
  english: {
    '3': [
      { id: 'english-3-1', prompt: 'apple이랑 apples는 뭐가 달라?' },
      { id: 'english-3-2', prompt: 'I am과 I like는 언제 쓰는 거야?' },
      { id: 'english-3-3', prompt: '"What\'s your name?"은 무슨 뜻이야?' },
      { id: 'english-3-4', prompt: '"How old are you?"에 어떻게 대답해?' },
      { id: 'english-3-5', prompt: '"This is a pen."에서 this는 무슨 뜻이야?' },
      { id: 'english-3-6', prompt: '"He"랑 "She"는 언제 써?' },
      { id: 'english-3-7', prompt: '"Can you swim?"에 Yes로 대답하면 어떻게 말해?' },
      { id: 'english-3-8', prompt: '"I have a dog."에서 have는 무슨 뜻이야?' },
      { id: 'english-3-9', prompt: '"big"이랑 "small" 말고 크기를 나타내는 다른 단어도 있어?' },
      { id: 'english-3-10', prompt: '"Good morning"이랑 "Good night"은 언제 써?' },
      { id: 'english-3-11', prompt: '"red, blue, yellow" 말고 색깔 단어 더 알려줘.' },
      { id: 'english-3-12', prompt: '"I like pizza."랑 "I don\'t like pizza."는 뭐가 달라?' },
      { id: 'english-3-13', prompt: '"Where are you from?"은 어떤 질문이야?' },
      { id: 'english-3-14', prompt: '"What time is it?"에 영어로 어떻게 대답해?' },
      { id: 'english-3-15', prompt: '"Let\'s go!"는 무슨 뜻이야?' },
      { id: 'english-3-16', prompt: '"My brother is tall."에서 tall은 무슨 뜻이야?' },
      { id: 'english-3-17', prompt: '"run"이랑 "running"은 뭐가 달라?' },
      { id: 'english-3-18', prompt: '영어로 자기소개는 어떻게 해?' },
      { id: 'english-3-19', prompt: '"How\'s the weather?"에 맑은 날은 뭐라고 대답해?' },
      { id: 'english-3-20', prompt: '"I\'m happy." 말고 기분을 말하는 영어 표현은 뭐가 있어?' },
    ],
    '4': [
      { id: 'english-4-1', prompt: '"apple"에 s를 붙이면 어떻게 바뀌고, 뜻은 뭐가 달라질까?' },
      { id: 'english-4-2', prompt: '"I am happy."에서 am은 무슨 역할을 해?' },
      { id: 'english-4-3', prompt: '"She ___ a book." 빈칸에 들어갈 말은 have / has 중 뭐가 맞을까?' },
      { id: 'english-4-4', prompt: '"What is your name?"에 영어로 어떻게 대답하면 좋을까?' },
      { id: 'english-4-5', prompt: '"I like milk."를 부정문으로 바꾸면 어떻게 말해야 할까?' },
      { id: 'english-4-6', prompt: '"He"는 누구를 가리킬 때 쓰는 말이야?' },
      { id: 'english-4-7', prompt: '"Can you swim?"에 Yes로 대답하는 문장은 어떻게 만들까?' },
      { id: 'english-4-8', prompt: '"big"의 반대말은 뭐야?' },
      { id: 'english-4-9', prompt: '"run"에 -ing를 붙이면 어떻게 바뀔까?' },
      { id: 'english-4-10', prompt: '"It is sunny."는 오늘 날씨가 어떻다는 뜻일까?' },
      { id: 'english-4-11', prompt: '다음 중 색깔 단어는 무엇일까? → apple / blue / run' },
      { id: 'english-4-12', prompt: '"There is a cat."과 "There are two cats."는 뭐가 다를까?' },
      { id: 'english-4-13', prompt: '"How old are you?"는 무엇을 묻는 질문일까?' },
      { id: 'english-4-14', prompt: '"I go to school at 8."에서 at은 무슨 뜻이야?' },
      { id: 'english-4-15', prompt: '"This is my bag."에서 my는 누구의 가방이라는 뜻일까?' },
      { id: 'english-4-16', prompt: '"Let\'s play soccer."는 어떤 상황에서 쓰는 말일까?' },
      { id: 'english-4-17', prompt: '"I have two brothers."에서 two는 무엇을 나타내는 말이야?' },
      { id: 'english-4-18', prompt: '"She is tall."에서 tall은 어떤 뜻일까?' },
      { id: 'english-4-19', prompt: '"What time is it?"에 "3시예요"라고 영어로 어떻게 말할까?' },
      { id: 'english-4-20', prompt: '다음 문장을 바르게 고쳐 볼까? → "He like pizza."' },
    ],
    '7': [
      { id: 'english-7-1', prompt: '"I am a student."에서 am은 왜 쓰인 거야?' },
      { id: 'english-7-2', prompt: '"She likes music."에서 likes에 s가 붙는 이유는 뭐야?' },
      { id: 'english-7-3', prompt: '"They ___ soccer after school." 빈칸에 들어갈 말은 play일까 plays일까?' },
      { id: 'english-7-4', prompt: '"I don\'t like coffee."는 왜 do not이 아니라 don\'t를 쓰는 거야?' },
      { id: 'english-7-5', prompt: '"He is reading a book."는 지금 하고 있는 일이라는 걸 어떻게 알 수 있어?' },
      { id: 'english-7-6', prompt: '"Did you do your homework?"에 Yes로 어떻게 대답해?' },
      { id: 'english-7-7', prompt: '"There is a pen on the desk."에서 there is는 무슨 뜻이야?' },
      { id: 'english-7-8', prompt: '"My brother is taller than me."에서 taller는 왜 이렇게 바뀐 거야?' },
      { id: 'english-7-9', prompt: '"This is my bag."에서 my 대신 쓸 수 있는 단어는 뭐가 있어?' },
      { id: 'english-7-10', prompt: '"Can I use your phone?"은 부탁하는 말이야, 허락을 구하는 말이야?' },
      { id: 'english-7-11', prompt: '"I went to school yesterday."에서 went는 왜 go가 아니야?' },
      { id: 'english-7-12', prompt: '"What are you doing?"은 상대방에게 무엇을 묻는 질문이야?' },
      { id: 'english-7-13', prompt: '"He has two sisters."에서 has는 왜 have가 아닌 거야?' },
      { id: 'english-7-14', prompt: '"Let\'s meet at 5."는 어떤 상황에서 쓰는 표현이야?' },
      { id: 'english-7-15', prompt: '"She is good at math."에서 good at은 무슨 뜻이야?' },
      { id: 'english-7-16', prompt: '"If it rains, I will stay home."에서 will은 어떤 의미를 가지고 있어?' },
      { id: 'english-7-17', prompt: '"Tom is the fastest runner in our class."에서 fastest는 무슨 의미야?' },
      { id: 'english-7-18', prompt: '"I was tired, but I finished my homework."에서 but은 어떤 역할을 해?' },
      { id: 'english-7-19', prompt: '다음 문장에서 틀린 부분은 어디야? → "She don\'t like milk."' },
      { id: 'english-7-20', prompt: '다음 문장을 영어로 어떻게 말해? → "나는 어제 친구와 도서관에 갔어."' },
    ],
    '10': [
      { id: 'english-10-1', prompt: '"I have lived here for three years."에서 have lived는 어떤 시제야?' },
      {
        id: 'english-10-2',
        prompt: '"She was studying when I called her."에서 was studying은 어떤 상황을 나타내는 거야?',
      },
      { id: 'english-10-3', prompt: '"If it rains, I will stay home."는 어떤 의미의 문장이야?' },
      { id: 'english-10-4', prompt: '"He is taller than his brother."에서 taller는 왜 이렇게 바뀐 거야?' },
      { id: 'english-10-5', prompt: '"Tom is the best student in our class."에서 the best는 무슨 뜻이야?' },
      { id: 'english-10-6', prompt: '"I didn\'t know the answer."에서 didn\'t는 왜 쓰인 거야?' },
      { id: 'english-10-7', prompt: '"She speaks English well."에서 well은 어떤 역할을 하는 단어야?' },
      { id: 'english-10-8', prompt: '"They are interested in science."에서 interested in은 무슨 뜻이야?' },
      {
        id: 'english-10-9',
        prompt: '"The movie was so interesting that I watched it twice."에서 so ~ that은 어떤 의미야?',
      },
      { id: 'english-10-10', prompt: '"He has to finish his homework by 10."에서 has to는 무슨 뜻이야?' },
      { id: 'english-10-11', prompt: '"I was happy because I passed the exam."에서 because는 어떤 역할을 해?' },
      { id: 'english-10-12', prompt: '"This book is easier than I thought."에서 than은 왜 필요한 거야?' },
      { id: 'english-10-13', prompt: '"She wants to become a doctor."에서 to become은 어떤 용법이야?' },
      {
        id: 'english-10-14',
        prompt: '"Reading books helps me relax."에서 Reading은 왜 동사처럼 생겼는데 명사 역할을 해?',
      },
      {
        id: 'english-10-15',
        prompt: '"The boy who is standing over there is my brother."에서 who는 무엇을 대신하는 거야?',
      },
      { id: 'english-10-16', prompt: '"I will call you when I arrive home."에서 when은 어떤 역할을 하는 접속사야?' },
      { id: 'english-10-17', prompt: '"He was too tired to walk anymore."에서 too ~ to는 어떤 뜻이야?' },
      { id: 'english-10-18', prompt: '"My English teacher told me to study harder."에서 told me to는 어떤 구조야?' },
      { id: 'english-10-19', prompt: '다음 문장에서 틀린 부분은 어디야? → "She don\'t like math."' },
      { id: 'english-10-20', prompt: '다음 문장을 영어로 어떻게 말해? → "나는 미래에 해외에서 일하고 싶다."' },
    ],
  },
} as const;
