/**
 * CLOVA Tutor
 * Copyright (c) 2026-present NAVER Cloud Corp.
 * MIT
 */

// 📝 Auto-generated by E2E-Autogen
// 🔧 Generated from: TC-1.1, TC-1.2, TC-1.3, TC-1.4, TC-1.5, TC-1.6

import { test } from '@jjades/e2e-autogen/playwright';
import { expect } from '@playwright/test';

test('[TC-1.1] 클로바 튜터 계정 관리 페이지 진입 및 기존 계정 확인', async ({ page }) => {
  await test.step('[TC-1.1.1] 서비스 접속 -> 계정 관리 메인 화면에 진입한다', async () => {
    // 📍 UI Path: 클로바 튜터 계정 관리 페이지
    // 🎬 When: 서비스 접속
    // ✅ Then: 계정 관리 메인 화면에 진입한다

    await page.goto('/');
    await page.evaluate(() => localStorage.clear());
    await page.goto('/login?scenario=TC-1.1');

    await expect(page.getByRole('heading')).toContainText('클로바 튜터 계정 관리');
  });

  await test.step("[TC-1.1.2] 서비스 접속 -> 생성된 계정이 없을 경우, '생성된 계정이 없습니다. 새로운 계정을 생성해주세요.' 안내 문구가 노출된다", async () => {
    // 📍 UI Path: 클로바 튜터 계정 관리 페이지
    // 🎬 When: 서비스 접속
    // ✅ Then: 생성된 계정이 없을 경우, '생성된 계정이 없습니다. 새로운 계정을 생성해주세요.' 안내 문구가 노출된다

    await expect(page.getByRole('cell', { name: '생성된 계정이 없습니다. 새로운 계정을 생성해주세요' })).toBeVisible();
  });
});

test('[TC-1.2] 신규 계정 생성', async ({ page }) => {
  await test.step('[TC-1.2.1] ‘계정 만들기’ 버튼 클릭 -> 계정 생성 팝업이 노출된다', async () => {
    // 📍 UI Path: 클로바 튜터 계정 관리 페이지 > 계정 생성
    // 🎬 When: ‘계정 만들기’ 버튼 클릭
    // ✅ Then: 계정 생성 팝업이 노출된다

    await page.goto('/login?scenario=TC-1.2');
    await page.getByRole('button', { name: '계정 만들기' }).click();
    await expect(page.getByRole('heading', { name: '새 학생 추가' })).toBeVisible();
  });

  await test.step('[TC-1.2.2] 이름 입력 -> 이름 필드를 입력할 수 있다', async () => {
    // 📍 UI Path: 클로바 튜터 계정 관리 페이지 > 계정 생성
    // 🎬 When: 이름 입력
    // ✅ Then: 이름 필드를 입력할 수 있다

    await page.getByRole('textbox', { name: '이름' }).click();
    await page.getByRole('textbox', { name: '이름' }).fill('e2e-playwright');
  });

  await test.step('[TC-1.2.3] 학년 선택 -> 학년(초등학교 3/4학년, 중학교 1학년, 고등학교 1학년)을 선택할 수 있다', async () => {
    // 📍 UI Path: 클로바 튜터 계정 관리 페이지 > 계정 생성
    // 🎬 When: 학년 선택
    // ✅ Then: 학년(초등학교 3/4학년, 중학교 1학년, 고등학교 1학년)을 선택할 수 있다

    await page.getByRole('combobox', { name: '학년' }).click();
    await expect(
      page.getByRole('listbox').getByText('초등학교 3학년초등학교 4학년중학교 1학년고등학교 1'),
    ).toBeVisible();
    await page.getByRole('option', { name: '고등학교 1학년' }).click();
  });

  await test.step('[TC-1.2.4] ‘생성’ 버튼 클릭 -> 신규 계정이 생성된다', async () => {
    // 📍 UI Path: 클로바 튜터 계정 관리 페이지 > 계정 생성
    // 🎬 When: ‘생성’ 버튼 클릭
    // ✅ Then: 신규 계정이 생성된다

    await page.getByRole('button', { name: '추가' }).click();
  });

  await test.step('[TC-1.2.5] 리스트 자동 갱신 -> 신규 계정이 계정 목록에 즉시 추가된다', async () => {
    // 📍 UI Path: 클로바 튜터 계정 관리 페이지 > 계정 생성
    // 🎬 When: 리스트 자동 갱신
    // ✅ Then: 신규 계정이 계정 목록에 즉시 추가된다

    await expect(page.locator('tbody')).toContainText('e2e-playwright');
  });
});

test('[TC-1.3] 계정 생성 시 필수값 누락 예외 처리', async ({ page }) => {
  await test.step('[TC-1.3.1] ‘계정 만들기’ 버튼 클릭 -> 계정 생성 팝업이 노출된다', async () => {
    // 📍 UI Path: 클로바 튜터 계정 관리 페이지 > 계정 생성
    // 🎬 When: ‘계정 만들기’ 버튼 클릭
    // ✅ Then: 계정 생성 팝업이 노출된다

    await page.goto('/login?scenario=TC-1.1');
    await page.getByRole('button', { name: '계정 만들기' }).click();
    await expect(page.getByRole('heading', { name: '새 학생 추가' })).toBeVisible();
  });

  await test.step('[TC-1.3.2] 이름 미입력 -> 필수값 누락 에러 메시지가 표시된다', async () => {
    // 📍 UI Path: 클로바 튜터 계정 관리 페이지 > 계정 생성
    // 🎬 When: 이름 미입력
    // ✅ Then: 필수값 누락 에러 메시지가 표시된다

    await page.getByRole('button', { name: '추가' }).click();
    await expect(page.getByText('이름은 최소 2글자 이상이어야 합니다')).toBeVisible();
  });
});

test('[TC-1.4] 학생 계정 선택 후 로그인', async ({ page }) => {
  await test.step('[TC-1.4.1] 특정 계정 리스트 클릭 -> 00 계정을 클릭하면 로그인 처리가 시작되고 해당 계정의 홈 화면으로 이동한다', async () => {
    // 📍 UI Path: 클로바 튜터 계정 관리 페이지 > 홈 화면
    // 🎬 When: 특정 계정 리스트 클릭
    // ✅ Then: 00 계정을 클릭하면 로그인 처리가 시작되고 해당 계정의 홈 화면으로 이동한다

    await page.goto('/login?scenario=TC-1.4');
    await page.getByRole('cell', { name: 'e2e-playwright' }).click();
    await expect(page.getByRole('heading', { name: '클로바 튜터' })).toBeVisible();
  });
});

test('[TC-1.5] 학생 계정 삭제', async ({ page }) => {
  await page.goto('/login?scenario=TC-1.5');

  await test.step('[TC-1.5.3] ‘취소’ 버튼 클릭 -> 삭제 확인 창이 닫히고 클로바 튜터 계정 관리 페이지 메인으로 돌아간다', async () => {
    // 📍 UI Path: 클로바 튜터 계정 관리 페이지> 계정 삭제
    // 🎬 When: ‘취소’ 버튼 클릭
    // ✅ Then: 삭제 확인 창이 닫히고 클로바 튜터 계정 관리 페이지 메인으로 돌아간다

    await page.locator('tbody').getByRole('button').click();
    await page.getByRole('button', { name: '삭제' }).click();
    await page.getByRole('heading', { name: '정말 계정을 삭제하시겠습니까?' }).click();
    await page.getByRole('button', { name: '취소' }).click();
    await expect(page.getByRole('heading', { name: '정말 계정을 삭제하시겠습니까?' })).toBeHidden();
  });

  await test.step('[TC-1.5.1] 특정 계정 삭제 버튼 클릭 -> 삭제 확인 모달이 표시된다', async () => {
    // 📍 UI Path: 클로바 튜터 계정 관리 페이지
    // 🎬 When: 특정 계정 삭제 버튼 클릭
    // ✅ Then: 삭제 확인 모달이 표시된다

    await page.getByRole('button', { name: '삭제' }).first().click();
    await page.getByRole('heading', { name: '정말 계정을 삭제하시겠습니까?' }).click();
  });

  await test.step('[TC-1.5.2] ‘삭제’ 버튼 클릭 -> 해당 계정이 리스트에서 즉시 삭제된다', async () => {
    // 📍 UI Path: 클로바 튜터 계정 관리 페이지> 계정 삭제
    // 🎬 When: ‘삭제’ 버튼 클릭
    // ✅ Then: 해당 계정이 리스트에서 즉시 삭제된다

    await page.getByRole('button', { name: '삭제' }).click();
    await expect(page.getByRole('cell', { name: '생성된 계정이 없습니다. 새로운 계정을 생성해주세요' })).toBeVisible();
  });
});

test('[TC-1.6] 링크로 로그인', async ({ page }) => {
  await test.step('[TC-1.6.1] /login/{user_id} 경로로 진입 -> user_id의 유저 정보로 로그인되고 홈 페이지로 이동한다', async () => {
    // 📍 UI Path: 로그인 링크 다이랙트 접속
    // 🎬 When: /login/{user_id} 경로로 진입
    // ✅ Then: user_id의 유저 정보로 로그인되고 홈 페이지로 이동한다

    await page.goto('/login/452395d2-8832-41d5-976f-857e9ad2dcb8?scenario=TC-1.6');
    await expect(page.getByRole('heading', { name: '클로바 튜터' })).toBeVisible();
  });
});

test.skip('[TC-1.7] 학생 계정 수정', async ({ page }) => {
  await page.goto('/login?scenario=TC-1.7');

  await test.step.skip(
    '[TC-1.7.3] ‘취소’ 버튼 클릭 -> 수정 설정창이 닫히고 클로바 튜터 계정 관리 페이지 메인으로 돌아간다',
    async () => {
      // 📍 UI Path: 클로바 튜터 계정 관리 페이지 > 계정 수정
      // 🎬 When: ‘취소’ 버튼 클릭
      // ✅ Then: 수정 설정창이 닫히고 클로바 튜터 계정 관리 페이지 메인으로 돌아간다

      await page.locator('tbody').getByRole('button').click();
      await page.getByRole('button', { name: '수정' }).click();
      await expect(page.getByText('수정하고 싶은 내용을 입력해주세요')).toBeVisible();
    },
  );

  await test.step.skip(
    "[TC-1.7.1] 특정 계정 설정 중 '수정' 버튼 클릭 -> 계정 이름을 수정할 수 있는 설정창이 노출된다",
    async () => {
      // 📍 UI Path: 클로바 튜터 계정 관리 페이지 > 계정 수정
      // 🎬 When: 특정 계정 설정 중 '수정' 버튼 클릭
      // ✅ Then: 계정 이름을 수정할 수 있는 설정창이 노출된다

      await page.getByRole('button', { name: '수정' }).click();
    },
  );

  await test.step.skip("[TC-1.7.2] 설정창의 이름 작성 후 '수정' 버튼 클릭 -> 해당 계정의 이름이 수정된다", async () => {
    // 📍 UI Path: 클로바 튜터 계정 관리 페이지 > 계정 수정
    // 🎬 When: 설정창의 이름 작성 후 '수정' 버튼 클릭
    // ✅ Then: 해당 계정의 이름이 수정된다

    await page.getByRole('textbox', { name: '이름' }).click();
    await page.getByRole('textbox', { name: '이름' }).press('ControlOrMeta+a');
    await page.getByRole('textbox', { name: '이름' }).fill('e2e');
    await page.getByRole('button', { name: '수정' }).click();
    await expect(page.getByRole('cell', { name: 'e2e' })).toBeVisible();
  });
});
