/**
 * CLOVA Tutor
 * Copyright (c) 2026-present NAVER Cloud Corp.
 * MIT
 */

// 📝 Auto-generated by E2E-Autogen
// 🔧 Generated from: TC-2.1, TC-2.2

import { test } from '@jjades/e2e-autogen/playwright';
import { expect } from '@playwright/test';

test('[TC-2.1] 홈 화면', async ({ page }) => {
  await test.step('[TC-2.1.1] 사이드바 대표 아이콘 클릭 -> 홈 화면으로 이동한다', async () => {
    // 📍 UI Path: 홈 화면
    // 🎬 When: 사이드바 대표 아이콘 클릭
    // ✅ Then: 홈 화면으로 이동한다

    await page.goto('/math');

    await page
      .locator('div')
      .filter({ hasText: /^Toggle Sidebar$/ })
      .click();

    await page.getByRole('button', { name: 'logo' }).click();
    await expect(page.getByRole('heading', { name: '클로바 튜터' })).toBeVisible();
  });

  await test.step('[TC-2.1.2] 사이드 요약 패널 클릭 -> 사이드바가 열림/닫힘 상태로 변화한다', async () => {
    // 📍 UI Path: 홈 화면
    // 🎬 When: 사이드 요약 패널 클릭
    // ✅ Then: 사이드바가 열림/닫힘 상태로 변화한다

    await page.getByRole('button', { name: 'Toggle Sidebar' }).click();
    await expect(page.getByRole('button', { name: '수학 채팅' })).toBeHidden();
  });

  await test.step('[TC-2.1.3] 수학 튜터 카드 선택 -> 수학 튜터 온보딩 페이지로 이동한다', async () => {
    // 📍 UI Path: 홈 화면 > 수학 튜터 온보딩
    // 🎬 When: 수학 튜터 카드 선택
    // ✅ Then: 수학 튜터 온보딩 페이지로 이동한다

    await page.goto('/math');
    await page
      .getByRole('button', { name: '수학 어떤 수학 문제든 정확하게 풀이 과정을 설명해주는 나만의 수학 공부 친구' })
      .click();
    await expect(page.getByRole('heading', { name: '수학 튜터' })).toBeVisible();
  });

  await test.step('[TC-2.1.4] 영어 튜터 카드 선택 -> 영어 튜터 온보딩 페이지로 이동한다', async () => {
    // 📍 UI Path: 홈 화면 > 영어 튜터 온보딩
    // 🎬 When: 영어 튜터 카드 선택
    // ✅ Then: 영어 튜터 온보딩 페이지로 이동한다

    await page.goto('/english');
    await page
      .getByRole('button', { name: '영어 어떤 영어 문제든 정확하게 풀이 과정을 설명해주는 나만의 영어 공부 친구' })
      .click();
    await expect(page.getByRole('heading', { name: '영어 튜터' })).toBeVisible();
  });
});

test('[TC-2.2] 사이드바', async ({ page }) => {
  await test.step('[TC-2.2.1] 유저 아이콘 클릭 -> 유저 정보(이름, 학년)와 서비스 기본 설정(대시보드, 테마)이 노출된다', async () => {
    // 📍 UI Path: 사이드바
    // 🎬 When: 유저 아이콘 클릭
    // ✅ Then: 유저 정보(이름, 학년)와 서비스 기본 설정(대시보드, 테마)이 노출된다

    await page.goto('/math?scenario=TC-2.2');
    await page.getByRole('button', { name: '유저 정보 메뉴' }).click();
    await expect(page.getByText('이름e2e-playwright학년고등학교 1학년')).toBeVisible();
  });

  await test.step('[TC-2.2.3] 테마 클릭 -> 라이트/다크 모드 선택 depth가 노출된다', async () => {
    // 📍 UI Path: 사이드바 > 유저 아이콘 > 테마
    // 🎬 When: 테마 클릭
    // ✅ Then: 라이트/다크 모드 선택 depth가 노출된다

    await page.goto('/?scenario=TC-2.2');
    await page.getByRole('button', { name: '유저 정보 메뉴' }).click();
    await page.getByRole('menuitem', { name: '테마' }).click();
    await expect(page.getByRole('menu', { name: '테마' })).toBeVisible();
  });

  await test.step('[TC-2.2.4] 테마 클릭 -> 초기 테마는 사용자의 기기 설정에 따른다', async () => {
    // 📍 UI Path: 사이드바 > 유저 아이콘 > 테마
    // 🎬 When: 테마 클릭
    // ✅ Then: 초기 테마는 사용자의 기기 설정에 따른다

    // localStorage의 테마 설정 제거 (시스템 설정을 따르도록)
    await page.evaluate(() => {
      localStorage.removeItem('theme');
    });

    await page.goto('/?scenario=TC-2.2');

    // HTML의 테마 클래스 확인
    const htmlElement = page.locator('html');
    const htmlClass = await htmlElement.getAttribute('class');
    const isDarkMode = htmlClass?.includes('dark') ?? false;

    // 테마 드롭다운 열기
    await page.getByRole('button', { name: '유저 정보 메뉴' }).click();
    await page.getByRole('menuitem', { name: '테마' }).click();

    if (isDarkMode) {
      // HTML 테마와 드롭다운 선택 항목이 일치하는지 확인
      await expect(page.getByRole('menuitem', { name: '다크' })).toHaveClass(/bg-accent/);
    } else {
      await expect(page.getByRole('menuitem', { name: '라이트' })).toHaveClass(/bg-accent/);
    }
  });

  await test.step('[TC-2.2.5] 테마 클릭 -> 사용자가 원하는 모드를 클릭하면 테마 설정이 변화한다', async () => {
    // 📍 UI Path: 사이드바 > 유저 아이콘 > 테마
    // 🎬 When: 테마 클릭
    // ✅ Then: 사용자가 원하는 모드를 클릭하면 테마 설정이 변화한다

    await page.getByRole('menuitem', { name: '다크' }).click();

    const htmlElement = page.locator('html');
    await expect(htmlElement).toHaveClass(/dark/);
  });

  await test.step.skip('[TC-2.2.7] 로그아웃 클릭 -> 클로바 튜터 계정 관리 페이지로 이동한다', async () => {
    // 📍 UI Path: 사이드바 > 유저 아이콘 > 로그아웃
    // 🎬 When: 로그아웃 클릭
    // ✅ Then: 클로바 튜터 계정 관리 페이지로 이동한다
  });
});
