/**
 * CLOVA Tutor
 * Copyright (c) 2026-present NAVER Cloud Corp.
 * MIT
 */

// 📝 Auto-generated by E2E-Autogen
// 🔧 Generated from: TC-3.1, TC-3.2, TC-3.3, TC-3.4, TC-3.5, TC-3.6

import { test } from '@jjades/e2e-autogen/playwright';
import { expect } from '@playwright/test';

test('[TC-3.1] 수학 온보딩 페이지', async ({ page }) => {
  await test.step('[TC-3.1.1] 수학 튜터 온보딩 페이지 진입 후 수학 예시 질문 1 클릭 -> 입력창에 수학 예시 질문 1 텍스트가 표시된다', async () => {
    // 📍 UI Path: 홈 화면 > 수학 온보딩 페이지
    // 🎬 When: 수학 튜터 온보딩 페이지 진입 후 수학 예시 질문 1 클릭
    // ✅ Then: 입력창에 수학 예시 질문 1 텍스트가 표시된다

    await page.goto('/math/chats?scenario=TC-3.1');

    // 예시 질문 목록에서 첫 번째 항목 선택
    const firstQuestion = page.getByRole('list', { name: '수학 예시 질문 목록' }).locator('li').first();
    await firstQuestion.click();

    // 입력창에 텍스트가 표시되는지 확인
    await expect(page.locator('form .ProseMirror')).not.toBeEmpty();
  });

  await test.step('[TC-3.1.3] 수학 예시 질문 1 클릭 후 수학 예시 질문 2 클릭 -> 입력창에 수학 예시 질문 1 텍스트 전체가 지워지고, 입력창에 수학 예시 질문 2 텍스트가 표시된다', async () => {
    // 📍 UI Path: 홈 화면 > 수학 온보딩 페이지
    // 🎬 When: 수학 예시 질문 1 클릭 후 수학 예시 질문 2 클릭
    // ✅ Then: 입력창에 수학 예시 질문 1 텍스트 전체가 지워지고, 입력창에 수학 예시 질문 2 텍스트가 표시된다

    const questionList = page.getByRole('list', { name: '수학 예시 질문 목록' });

    // 첫 번째 예시 질문 클릭
    const firstQuestion = questionList.locator('li').first();
    const firstQuestionText = await firstQuestion.textContent();
    await firstQuestion.click();
    await expect(page.locator('form .ProseMirror')).not.toBeEmpty();

    // 두 번째 예시 질문 클릭
    const secondQuestion = questionList.locator('li').nth(1);
    await secondQuestion.click();

    // 첫 번째 질문 텍스트가 사라지고 두 번째 질문 텍스트로 변경되었는지 확인
    await expect(page.locator('form .ProseMirror')).not.toContainText(firstQuestionText || '');
    await expect(page.locator('form .ProseMirror')).not.toBeEmpty();
  });

  await test.step('[TC-3.1.4] 수학 예시 질문 1 클릭 후 전송 버튼 클릭 -> 수학 채팅방이 생성되고 해당 채팅방으로 이동한다', async () => {
    // 📍 UI Path: 홈 화면 > 수학 온보딩 페이지 > 채팅방
    // 🎬 When: 수학 예시 질문 1 클릭 후 전송 버튼 클릭
    // ✅ Then: 수학 채팅방이 생성되고 해당 채팅방으로 이동한다

    // 첫 번째 예시 질문 클릭
    const firstQuestion = page.getByRole('list', { name: '수학 예시 질문 목록' }).locator('li').first();
    await firstQuestion.click();

    // 전송 버튼 클릭
    await page.getByRole('button', { name: '채팅 전송' }).click();

    // 채팅방으로 이동 확인
    await expect(
      page.getByText('클로바 튜터는 학습에 관한 정보 제공 시 실수를 할 수 있으니, 중요한 정보는 다시 한번 확인하세요'),
    ).toBeVisible();
  });
});

test('[TC-3.2] 영어 온보딩 페이지', async ({ page }) => {
  await test.step('[TC-3.2.1] 영어 튜터 온보딩 페이지 진입 후 영어 예시 질문 1 클릭 -> 입력창에 영어 예시 질문 1 텍스트가 표시된다', async () => {
    // 📍 UI Path: 홈 화면 > 영어 온보딩 페이지
    // 🎬 When: 영어 튜터 온보딩 페이지 진입 후 영어 예시 질문 1 클릭
    // ✅ Then: 입력창에 영어 예시 질문 1 텍스트가 표시된다

    await page.goto('/english/chats?scenario=TC-3.2');

    // 예시 질문 목록에서 첫 번째 항목 선택
    const firstQuestion = page.getByRole('list', { name: '영어 예시 질문 목록' }).locator('li').first();
    await firstQuestion.click();

    // 입력창에 텍스트가 표시되는지 확인
    await expect(page.locator('form .ProseMirror')).not.toBeEmpty();
  });

  await test.step('[TC-3.2.3] 영어 예시 질문 1 클릭 후 전송 버튼 클릭 -> 영어 채팅방이 생성되고 해당 채팅방으로 이동한다', async () => {
    // 📍 UI Path: 홈 화면 > 영어 온보딩 페이지 > 채팅방
    // 🎬 When: 영어 예시 질문 1 클릭 후 전송 버튼 클릭
    // ✅ Then: 영어 채팅방이 생성되고 해당 채팅방으로 이동한다

    // 첫 번째 예시 질문 클릭
    const firstQuestion = page.getByRole('list', { name: '영어 예시 질문 목록' }).locator('li').first();
    await firstQuestion.click();

    // 전송 버튼 클릭
    await page.getByRole('button', { name: '채팅 전송' }).click();

    // 채팅방으로 이동 확인
    await expect(
      page.getByText('클로바 튜터는 학습에 관한 정보 제공 시 실수를 할 수 있으니, 중요한 정보는 다시 한번 확인하세요'),
    ).toBeVisible();
  });
});

test('[TC-3.3] 새 채팅', async ({ page }) => {
  await test.step('[TC-3.3.1] 사이드 창의 새 채팅 버튼 클릭 -> 현재 위치한 과목의 채팅방(온보딩 페이지)로 이동한다', async () => {
    // 📍 UI Path: 사이드바 > 새 채팅
    // 🎬 When: 사이드 창의 새 채팅 버튼 클릭
    // ✅ Then: 현재 위치한 과목의 채팅방(온보딩 페이지)로 이동한다

    // 수학 과목에서 새 채팅 버튼 클릭 테스트
    await page.goto('/math/chats?scenario=TC-3.3');
    await page
      .locator('div')
      .filter({ hasText: /^Toggle Sidebar$/ })
      .click();
    await page.getByRole('button', { name: '새 채팅' }).click();

    // 현재 URL에서 subject 값 추출하여 올바른 경로로 이동했는지 확인
    const currentUrl = page.url();
    const urlParts = currentUrl.split('/');
    const subject = urlParts[1];

    if (subject === 'math') {
      // URL에서 subject 추출

      await expect(page).toHaveURL(/.*\/math\/chats/);
    } else if (subject === 'english') {
      await expect(page).toHaveURL(/.*\/english\/chats/);
    }

    // 영어 과목에서 새 채팅 버튼 클릭 테스트
    await page.goto('/english/chats?scenario=TC-3.3');
    await page
      .locator('div')
      .filter({ hasText: /^Toggle Sidebar$/ })
      .click();
    await page.getByRole('button', { name: '새 채팅' }).click();

    // 영어 과목에서도 올바른 경로로 이동했는지 확인
    const englishUrl = page.url();
    const englishUrlParts = englishUrl.split('/');
    const englishSubject = englishUrlParts[1];

    if (englishSubject === 'math') {
      await expect(page).toHaveURL(/.*\/math\/chats/);
    } else if (englishSubject === 'english') {
      await expect(page).toHaveURL(/.*\/english\/chats/);
    }
  });

  await test.step('[TC-3.3.2] 입력창 비워진 상태 -> 전송 버튼이 비활성화된다', async () => {
    // 📍 UI Path: 사이드바 > 새 채팅
    // 🎬 When: 입력창 비워진 상태
    // ✅ Then: 전송 버튼이 비활성화된다

    await expect(page.locator('form')).toContainText('궁금한 것이 있다면 언제든 물어봐!');
    await expect(page.getByRole('button', { name: '채팅 전송' })).toBeDisabled();
  });

  await test.step('[TC-3.3.3] 입력창에 텍스트가 입력된 상태 -> 전송 버튼이 활성화된다', async () => {
    // 📍 UI Path: 사이드바 > 새 채팅
    // 🎬 When: 입력창에 텍스트가 입력된 상태
    // ✅ Then: 전송 버튼이 활성화된다

    await page.locator('.ProseMirror').click();
    await page.locator('.ProseMirror').fill('123123');
    await expect(page.locator('form')).toContainText('123123');
    await expect(page.getByRole('button', { name: '채팅 전송' })).toBeEnabled();
  });
});

test.describe
  .serial('[TC-3.4, TC-3.5] 채팅 기록 확인 및 관리', () => {
    test('[TC-3.4] 채팅 기록 확인', async ({ page }) => {
      await test.step('[TC-3.4.1] 사이드바 > 수학 채팅 기록 폴더 아이콘 클릭 -> 아이콘 하단에 최근 수학 채팅 기록이 최대 10개까지 서브메뉴로 노출된다.', async () => {
        // 📍 UI Path: 사이드바 > 수학 채팅 기록
        // 🎬 When: 사이드바 > 수학 채팅 기록 폴더 아이콘 클릭
        // ✅ Then: 아이콘 하단에 최근 수학 채팅 기록이 최대 10개까지 서브메뉴로 노출된다.

        await page.goto('/?scenario=TC-3.4.1');
        await page
          .locator('div')
          .filter({ hasText: /^Toggle Sidebar$/ })
          .click();

        await page.waitForTimeout(500);

        await expect(page.getByRole('list', { name: '최근 수학 채팅 기록' })).toBeVisible();

        const chatList = page.getByRole('list', { name: '최근 수학 채팅 기록' });
        const chatItems = chatList.getByRole('listitem');
        const itemCount = await chatItems.count();
        expect(itemCount).toBeLessThanOrEqual(11);
      });

      await test.step('[TC-3.4.2] 채팅 기록 리스트 클릭 -> 선택한 채팅방으로 이동한다', async () => {
        // 📍 UI Path: 사이드바 > 수학 채팅 기록
        // 🎬 When: 채팅 기록 리스트 클릭
        // ✅ Then: 선택한 채팅방으로 이동한다

        const chatLink = page.locator('a[data-slot="sidebar-menu-sub-button"]').first();

        const href = await chatLink.getAttribute('href');
        expect(href).toBeTruthy();

        await chatLink.click();

        if (href) {
          await expect(page).toHaveURL(href);
        }
      });

      await test.step('[TC-3.4.3] 사이드바 > 영어 채팅 기록 폴더 아이콘 클릭 -> 아이콘 하단에 최근 영어 채팅 기록이 최대 10개까지 서브메뉴로 노출된다', async () => {
        // 📍 UI Path: 사이드바 > 영어 채팅 기록
        // 🎬 When: 사이드바 > 영어 채팅 기록 폴더 아이콘 클릭
        // ✅ Then: 아이콘 하단에 최근 영어 채팅 기록이 최대 10개까지 서브메뉴로 노출된다

        await page.goto('/?scenario=TC-3.4.3');
        await page
          .locator('div')
          .filter({ hasText: /^Toggle Sidebar$/ })
          .click();

        await page.waitForTimeout(500);

        await page.getByRole('button', { name: '영어 채팅' }).click();
        await expect(page.getByRole('list', { name: '최근 영어 채팅 기록' })).toBeVisible();

        const chatList = page.getByRole('list', { name: '최근 영어 채팅 기록' });
        const chatItems = chatList.getByRole('listitem');
        const itemCount = await chatItems.count();
        expect(itemCount).toBeLessThanOrEqual(11);
      });

      await test.step('[TC-3.4.4] 채팅 기록 리스트 클릭 -> 선택한 채팅방으로 이동한다', async () => {
        // 📍 UI Path: 사이드바 > 영어 채팅 기록
        // 🎬 When: 채팅 기록 리스트 클릭
        // ✅ Then: 선택한 채팅방으로 이동한다

        const chatLink = page.locator('a[data-slot="sidebar-menu-sub-button"]').first();

        const href = await chatLink.getAttribute('href');
        expect(href).toBeTruthy();

        await chatLink.click();

        if (href) {
          await expect(page).toHaveURL(href);
        }
      });
    });

    test('[TC-3.5] 채팅 기록 관리', async ({ page }) => {
      await test.step('[TC-3.5.1] 채팅방 리스트 마우스 호버 -> 드롭다운 메뉴 아이콘이 노출된다', async () => {
        // 📍 UI Path: 사이드바 > 수학/영어 채팅 기록
        // 🎬 When: 채팅방 리스트 마우스 호버
        // ✅ Then: 드롭다운 메뉴 아이콘이 노출된다

        await page.goto('/?scenario=TC-3.5');
        await page
          .locator('div')
          .filter({ hasText: /^Toggle Sidebar$/ })
          .click();
      });

      await test.step('[TC-3.5.2] 드롭다운 아이콘 선택 -> 이름 바꾸기와 삭제 드롭다운 메뉴를 출력한다', async () => {
        // 📍 UI Path: 사이드바 > 수학/영어 채팅 기록
        // 🎬 When: 드롭다운 아이콘 선택
        // ✅ Then: 이름 바꾸기와 삭제 드롭다운 메뉴를 출력한다

        await page.locator('li[data-slot="sidebar-menu-sub-item"]').first().hover();
        await page.getByRole('button', { name: '채팅방 옵션 열기' }).first().click();
        await expect(page.getByLabel('', { exact: true })).toContainText('이름 바꾸기삭제');
      });

      await test.step("[TC-3.5.3] 드롭다운 메뉴 중 '이름 바꾸기' 선택 -> 채팅방 이름을 변경할 수 있다", async () => {
        // 📍 UI Path: 사이드바 > 수학/영어 채팅 기록
        // 🎬 When: 드롭다운 메뉴 중 '이름 바꾸기' 선택
        // ✅ Then: 채팅방 이름을 변경할 수 있다

        await page.getByRole('menuitem', { name: '이름 바꾸기' }).click();
        await page.getByRole('textbox', { name: '채팅 제목을 입력하세요' }).fill('123');
        await page.getByRole('textbox', { name: '채팅 제목을 입력하세요' }).press('Enter');
        await page.waitForTimeout(500);
        await expect(page.getByLabel('최근 수학 채팅 기록')).toContainText('123');
      });

      await test.step("[TC-3.5.4] 드롭다운 메뉴 중 '삭제' 선택 -> 삭제 확인 팝업창이 표시된다", async () => {
        // 📍 UI Path: 사이드바 > 수학/영어 채팅 기록
        // 🎬 When: 드롭다운 메뉴 중 '삭제' 선택
        // ✅ Then: 삭제 확인 팝업창이 표시된다

        await page.getByRole('listitem').filter({ hasText: /^123$/ }).first().getByLabel('채팅방 옵션 열기').click();
        await page.getByRole('menuitem', { name: '삭제' }).click();
        await expect(page.getByLabel('"123" 대화를 삭제하시겠습니까?')).toContainText(
          '"123" 대화를 삭제하시겠습니까?삭제된 대화는 복구할 수 없습니다.취소삭제',
        );
      });

      await test.step('[TC-3.5.5] 팝업창 내 취소 버튼 선택 -> 팝업창이 사라지고 기존 페이지에 머무른다', async () => {
        // 📍 UI Path: 사이드바 > 수학/영어 채팅 기록
        // 🎬 When: 팝업창 내 취소 버튼 선택
        // ✅ Then: 팝업창이 사라지고 기존 페이지에 머무른다

        const currentURL = page.url();
        await page.getByRole('button', { name: '취소' }).click();
        await expect(page.getByLabel('"123" 대화를 삭제하시겠습니까?')).not.toBeVisible();
        await expect(page).toHaveURL(currentURL);
        await expect(page.getByLabel('최근 수학 채팅 기록')).toContainText('123');
      });

      await test.step('[TC-3.5.6] 팝업창 내 삭제 버튼 선택 -> 해당 과목의 온보딩 페이지로 리다이렉트한다', async () => {
        // 📍 UI Path: 사이드바 > 수학/영어 채팅 기록
        // 🎬 When: 팝업창 내 삭제 버튼 선택
        // ✅ Then: 해당 과목의 온보딩 페이지로 리다이렉트한다

        await page.getByRole('menuitem', { name: '삭제' }).click();
        await page.getByRole('button', { name: '삭제' }).click();
        await page.waitForURL('/math/chats?scenario=TC-3.5');
      });
    });
  });

test('[TC-3.6] 채팅 기록 페이지', async ({ page }) => {
  await test.step("[TC-3.6.1] 사이드바 수학 채팅 기록의 '모든 채팅' 영역 클릭 -> 채팅 기록 수학 페이지로 이동한다", async () => {
    // 📍 UI Path: 사이드바 > 수학 채팅 기록 > 모든 채팅
    // 🎬 When: 사이드바 수학 채팅 기록의 '모든 채팅' 영역 클릭
    // ✅ Then: 채팅 기록 수학 페이지로 이동한다

    await page.goto('/?scenario=TC-3.6');
    await page
      .locator('div')
      .filter({ hasText: /^Toggle Sidebar$/ })
      .click();
  });

  await test.step('[TC-3.6.2] 모든 채팅 버튼 클릭 -> 수학 과목의 채팅 기록 페이지로 이동한다', async () => {
    // 📍 UI Path: 사이드바 > 수학 채팅 기록 > 모든 채팅
    // 🎬 When: 모든 채팅 버튼 클릭
    // ✅ Then: 수학 과목의 채팅 기록 페이지로 이동한다

    await page.getByRole('link', { name: '모든 채팅' }).click();
    await expect(page).toHaveURL(/.*\/math\/chats\/history/);
  });

  await test.step('[TC-3.6.6] 채팅 기록 카드 오른쪽 미트볼 아이콘 클릭 -> 드롭다운 메뉴(이름 바꾸기와 삭제 메뉴)를 출력한다', async () => {
    // 📍 UI Path: 사이드바 > 수학 채팅 기록 > 모든 채팅
    // 🎬 When: 채팅 기록 카드 오른쪽 미트볼 아이콘 클릭
    // ✅ Then: 드롭다운 메뉴(이름 바꾸기와 삭제 메뉴)를 출력한다

    await page.locator('[aria-label="채팅방 옵션 열기"]').first().click();
    await expect(page.getByLabel('', { exact: true })).toContainText('이름 바꾸기삭제');
  });

  await test.step("[TC-3.6.7] 드롭다운 메뉴 중 '이름 바꾸기' 선택 -> 채팅 기록 카드 이름을 변경할 수 있다", async () => {
    // 📍 UI Path: 사이드바 > 수학 채팅 기록 > 모든 채팅
    // 🎬 When: 드롭다운 메뉴 중 '이름 바꾸기' 선택
    // ✅ Then: 채팅 기록 카드 이름을 변경할 수 있다

    await page.getByRole('menuitem', { name: '이름 바꾸기' }).click();
    await page.getByRole('textbox', { name: '채팅 제목을 입력하세요' }).click();
    await page.getByRole('textbox', { name: '채팅 제목을 입력하세요' }).press('ControlOrMeta+a');
    await page.getByRole('textbox', { name: '채팅 제목을 입력하세요' }).fill('이름변경하기');
    await page.getByRole('textbox', { name: '채팅 제목을 입력하세요' }).press('Enter');
  });

  await test.step("[TC-3.6.8] 드롭다운 메뉴 중 '삭제' 선택 -> 삭제 확인 팝업창이 표시된다", async () => {
    // 📍 UI Path: 사이드바 > 수학 채팅 기록 > 모든 채팅
    // 🎬 When: 드롭다운 메뉴 중 '삭제' 선택
    // ✅ Then: 삭제 확인 팝업창이 표시된다

    await page.getByRole('button', { name: '채팅방 옵션 열기' }).first().click();
    await page.getByRole('menuitem', { name: '삭제' }).click();
  });

  await test.step('[TC-3.6.9] 팝업창 내 취소 버튼 선택 -> 팝업창이 사라지고 기존 페이지에 머무른다', async () => {
    // 📍 UI Path: 사이드바 > 수학 채팅 기록 > 모든 채팅
    // 🎬 When: 팝업창 내 취소 버튼 선택
    // ✅ Then: 팝업창이 사라지고 기존 페이지에 머무른다

    await page.getByRole('button', { name: '취소' }).click();
  });

  await test.step('[TC-3.6.10] 팝업창 내 삭제 버튼 선택 -> 해당 채팅 기록 카드가 삭제된다', async () => {
    // 📍 UI Path: 사이드바 > 수학 채팅 기록 > 모든 채팅
    // 🎬 When: 팝업창 내 삭제 버튼 선택
    // ✅ Then: 해당 채팅 기록 카드가 삭제된다

    await page.getByRole('menuitem', { name: '삭제' }).click();
    await expect(page.getByText('삭제된 대화는 복구할 수 없습니다')).toBeVisible();
    await page.getByRole('button', { name: '삭제' }).click();
  });

  await test.step("[TC-3.6.10] 리스트 상단의 '영어' 클릭 -> 영어의 모든 채팅 기록 페이지로 이동한다", async () => {
    // 📍 UI Path: 사이드바 > 수학 채팅 기록 > 모든 채팅 > 영어 채팅 기록
    // 🎬 When: 리스트 상단의 '영어' 클릭
    // ✅ Then: 영어의 모든 채팅 기록 페이지로 이동한다

    await page.goto('/math/chats/history?scenario=TC-3.6');
    await page.getByRole('tab', { name: '영어' }).click();
    await expect(page).toHaveURL(/.*\/english\/chats\/history/);
  });

  await test.step("[TC-3.6.4] 타이틀 오른쪽 '새 채팅' 클릭 -> 수학 온보딩 페이지로 이동한다", async () => {
    // 📍 UI Path: 사이드바 > 수학 채팅 기록 > 모든 채팅
    // 🎬 When: 타이틀 오른쪽 '새 채팅' 클릭
    // ✅ Then: 수학 온보딩 페이지로 이동한다

    await page.goto('/english/chats/history?scenario=TC-3.6');
    await page.getByRole('tab', { name: '수학' }).click();
    await expect(page).toHaveURL(/.*\/math\/chats\/history/);
  });
});
