/**
 * CLOVA Tutor
 * Copyright (c) 2026-present NAVER Cloud Corp.
 * MIT
 */

// 📝 Auto-generated by E2E-Autogen
// 🔧 Generated from: TC-4.1, TC-4.2, TC-4.3, TC-4.4, TC-4.5, TC-4.6, TC-4.7

import fs from 'node:fs/promises';
import { test } from '@jjades/e2e-autogen/playwright';
import { expect } from '@playwright/test';

test('[TC-4.1] 채팅 입력', async ({ page }) => {
  await test.step('[TC-4.1.1] 입력창에 한 줄로 된 텍스트 입력 -> 입력창에 텍스트 표시되고 전송 버튼이 활성화된다', async () => {
    // 📍 UI Path: 채팅방 > 채팅 입력
    // 🎬 When: 입력창에 한 줄로 된 텍스트 입력
    // ✅ Then: 입력창에 텍스트 표시되고 전송 버튼이 활성화된다

    await page.goto('/math/chats/347?scenario=TC-4.1');
    await page.locator('.ProseMirror').click();
    await page.locator('.ProseMirror').fill('한 줄로 된 텍스트');
    await page.waitForTimeout(100);
    await expect(page.getByRole('button', { name: '채팅 전송' })).toBeEnabled();
  });

  await test.step('[TC-4.1.2] 입력창에 여러 줄로 된 텍스트 입력 -> 입력창에 텍스트 표시될때, 최대 넓이까지 채팅창이 확장되며 최대 넓이 이후에는 스크롤이 생성된다', async () => {
    // 📍 UI Path: 채팅방 > 채팅 입력
    // 🎬 When: 입력창에 여러 줄로 된 텍스트 입력
    // ✅ Then: 입력창에 텍스트 표시될때, 최대 넓이까지 채팅창이 확장되며 최대 넓이 이후에는 스크롤이 생성된다

    await page.locator('.ProseMirror').click();
    await page.locator('.ProseMirror').fill('여러 줄로 된 텍스트\n'.repeat(30));
    const inputForm = page.locator('.ProseMirror');
    const isScrollable = await inputForm.evaluate((node) => {
      return node.scrollHeight > node.clientHeight;
    });
    expect(isScrollable).toBeTruthy();
  });

  await test.step('[TC-4.1.3] 해당 채팅방의 입력 창에 텍스트를 작성 중인 상태 -> 채팅 기록 카드에 "작성중" 뱃지가 노출된다', async () => {
    // 📍 UI Path: 사이드바 > 채팅 기록 > 모든 채팅
    // 🎬 When: 해당 채팅방의 입력 창에 텍스트를 작성 중인 상태
    // ✅ Then: 채팅 기록 카드에 "작성중" 뱃지가 노출된다

    await page.getByRole('link', { name: '모든 채팅' }).click({ force: true });
    const chatList = page.getByRole('list', { name: '채팅 목록' });
    await expect(chatList.getByText('작성중')).toBeVisible();
  });
});

test('[TC-4.2] 채팅 전송', async ({ page }) => {
  await test.step('[TC-4.2.1] 전송 버튼 클릭 -> 입력한 채팅이 모델에 전송되며 보낸 메시지로 표시된다', async () => {
    // 📍 UI Path: 채팅방 > 채팅 입력 > 채팅 전송
    // 🎬 When: 전송 버튼 클릭
    // ✅ Then: 입력한 채팅이 모델에 전송되며 보낸 메시지로 표시된다

    await page.goto('/math/chats?scenario=TC-4.2');

    const editor = page.locator('.ProseMirror').first();

    await editor.waitFor({ state: 'visible' });
    await editor.click();

    await page.locator('.ProseMirror').fill('테스트 메시지 전송');
    await page.getByRole('button', { name: '채팅 전송' }).click();

    await page.waitForURL('/math/chats/226?scenario=TC-4.2');

    await expect(page.locator('#selection-popover-wrapper')).toContainText('테스트 메시지 전송');
  });

  await test.step('[TC-4.2.2] 엔터 키 입력 -> 입력한 채팅이 모델에 전송되며 보낸 메시지로 표시된다', async () => {
    // 📍 UI Path: 채팅방 > 채팅 입력 > 채팅 전송
    // 🎬 When: 엔터 키 입력
    // ✅ Then: 입력한 채팅이 모델에 전송되며 보낸 메시지로 표시된다

    await page.locator('.ProseMirror').click();
    await page.locator('.ProseMirror').fill('엔터키 테스트 메시지 전송');
    await page
      .locator('div')
      .filter({ hasText: /^엔터키 테스트 메시지 전송$/ })
      .nth(5)
      .press('Enter');
    await page.waitForTimeout(1000);
    await expect(page.locator('#selection-popover-wrapper')).toContainText('엔터키 테스트 메시지 전송');
  });

  await test.step('[TC-4.2.3] 마크다운 적용 텍스트 입력 > 전송 버튼 클릭 -> 보낸 메시지에 마크다운이 적용된다', async () => {
    // 📍 UI Path: 채팅방 > 채팅 입력 > 채팅 전송
    // 🎬 When: 마크다운 적용 텍스트 입력 > 전송 버튼 클릭
    // ✅ Then: 보낸 메시지에 마크다운이 적용된다

    await page.locator('.ProseMirror').click();
    await page.locator('.ProseMirror').fill('## 안녕하세요');
    await page
      .locator('div')
      .filter({ hasText: /^## 안녕하세요$/ })
      .nth(5)
      .press('Enter');
    await page.waitForTimeout(500);
    await expect(page.locator('#selection-popover-wrapper')).toContainText('안녕하세요');
  });

  await test.step('[TC-4.2.4] LaTeX 적용 텍스트 입력 > 전송 버튼 클릭 -> 보낸 메시지에 수식이 적용된다', async () => {
    // 📍 UI Path: 채팅방 > 채팅 입력 > 채팅 전송
    // 🎬 When: LaTeX 적용 텍스트 입력 > 전송 버튼 클릭
    // ✅ Then: 보낸 메시지에 수식이 적용된다

    await page.locator('.ProseMirror').click();
    await page.locator('.ProseMirror').fill(`$ \\sqrt{2} $`);
    await page.locator('div').filter({ hasText: '$ \\sqrt{2} $' }).nth(5).press('Enter');
    await page.waitForTimeout(500);
    await expect(page.locator('#selection-popover-wrapper')).toContainText('2');
  });
});

test('[TC-4.3] 수식 블럭 삽입', async ({ page }) => {
  await test.step('[TC-4.3.1] 수학 튜터 메뉴 선택 -> 수식 블럭 삽입 버튼이 활성화된다', async () => {
    // 📍 UI Path: 채팅방(수학 튜터)
    // 🎬 When: 수학 튜터 메뉴 선택
    // ✅ Then: 수식 블럭 삽입 버튼이 활성화된다

    await page.goto('/math/chats?scenario=TC-4.1');
    await expect(page.getByRole('button', { name: '수식 블럭 삽입' }).first()).toBeEnabled();
  });

  await test.step('[TC-4.3.2] 수식 블럭 삽입 버튼 클릭 -> 입력창에 수식 블럭이 표시되고 수식 입력 popover가 활성화되며 커서가 popover 내부로 이동한다.', async () => {
    // 📍 UI Path: 채팅방(수학 튜터) > 수식 블럭 삽입
    // 🎬 When: 수식 블럭 삽입 버튼 클릭
    // ✅ Then: 입력창에 수식 블럭이 표시되고 수식 입력 popover가 활성화되며 커서가 popover 내부로 이동한다.

    await page.getByRole('button', { name: '수식 블럭 삽입' }).first().click();
    await expect(page.locator('.ML__container')).toBeVisible();
    await expect(page.getByRole('textbox')).toBeFocused();
  });

  await test.step('[TC-4.3.3] 마우스 클릭을 사용해 수식 블럭 밖으로 커서 이동 -> 수식 입력 popover가 닫힌다', async () => {
    // 📍 UI Path: 채팅방(수학 튜터) > 수식 블럭 삽입
    // 🎬 When: 마우스 클릭을 사용해 수식 블럭 밖으로 커서 이동
    // ✅ Then: 수식 입력 popover가 닫힌다

    await page.locator('.ProseMirror').click();
    await expect(page.locator('.ML__container')).toBeHidden();
  });

  await test.step('[TC-4.3.4] 마우스 클릭을 사용해 수식 블럭 안으로 커서 이동 -> 수식 입력 popover가 열린다', async () => {
    // 📍 UI Path: 채팅방(수학 튜터) > 수식 블럭 삽입
    // 🎬 When: 마우스 클릭을 사용해 수식 블럭 안으로 커서 이동
    // ✅ Then: 수식 입력 popover가 열린다

    await page.getByText('수식 입력').first().click();
    await expect(page.locator('.ML__container')).toBeVisible();
  });

  await test.step('[TC-4.3.7] 수식 블럭 안에 숫자/영문 입력 -> 수식 블럭 안에 숫자, 영문이 입력된다', async () => {
    // 📍 UI Path: 채팅방(수학 튜터) > 수식 블럭 삽입
    // 🎬 When: 수식 블럭 안에 숫자/영문 입력
    // ✅ Then: 수식 블럭 안에 숫자, 영문이 입력된다

    await page.getByRole('textbox').first().fill('123abc', { force: true });
    await expect(page.locator('form')).toContainText('123abc');
  });

  await test.step('[TC-4.3.8] 수식 블럭 안에 한글 입력 -> 수식 블럭 안에 한글이 입력된다', async () => {
    // 📍 UI Path: 채팅방(수학 튜터) > 수식 블럭 삽입
    // 🎬 When: 수식 블럭 안에 한글 입력
    // ✅ Then: 수식 블럭 안에 한글이 입력된다

    await page.getByRole('textbox').first().fill('가나다', { force: true });
    await expect(page.locator('form')).toContainText('가나다');
  });

  await test.step('[TC-4.3.5] 키보드 화살표를 사용해 수식 블럭 밖으로 커서 이동 -> 수식 입력 popover가 닫히며 수식 블럭 다음으로 커서가 이동한다', async () => {
    // 📍 UI Path: 채팅방(수학 튜터) > 수식 블럭 삽입
    // 🎬 When: 키보드 화살표를 사용해 수식 블럭 밖으로 커서 이동
    // ✅ Then: 수식 입력 popover가 닫히며 수식 블럭 다음으로 커서가 이동한다

    // 수식 블럭 밖으로 이동
    await page.getByRole('textbox').press('ArrowRight');
    await expect(page.locator('.ML__container')).toBeHidden();

    // ProseMirror의 selection을 사용해 커서가 수식 블럭 다음에 있는지 확인
    const selectionInfo = await page.evaluate(() => {
      // biome-ignore lint/suspicious/noExplicitAny: 테스트코드
      const view = (window as Window & { __editorView?: any }).__editorView;
      if (!view) return null;

      const { state } = view;
      const { selection, doc } = state;

      // 수식 블럭의 위치 찾기
      let mathNodePos = -1;
      let mathNodeSize = 0;

      // biome-ignore lint/suspicious/noExplicitAny: 테스트코드
      doc.descendants((node: any, pos: number) => {
        if (node.type.name === 'math_inline' && mathNodePos === -1) {
          mathNodePos = pos;
          mathNodeSize = node.nodeSize;
          return false; // 첫 번째 수식 노드만 찾음
        }
        return true;
      });

      return {
        cursorPos: selection.from,
        mathNodeEndPos: mathNodePos + mathNodeSize,
        mathNodeFound: mathNodePos !== -1,
      };
    });

    expect(selectionInfo?.mathNodeFound).toBe(true);
    expect(selectionInfo?.cursorPos).toBe(selectionInfo?.mathNodeEndPos);
  });

  await test.step('[TC-4.3.6] 키보드 화살표를 사용해 수식 블럭 안으로 커서 이동 -> 수식 입력 popover가 열리며 수식 입력 popover 내부의 모든 텍스트가 select 처리된다', async () => {
    // 📍 UI Path: 채팅방(수학 튜터) > 수식 블럭 삽입
    // 🎬 When: 키보드 화살표를 사용해 수식 블럭 안으로 커서 이동
    // ✅ Then: 수식 입력 popover가 열리며 수식 입력 popover 내부의 모든 텍스트가 select 처리된다

    // 수식 블럭 안으로 다시 이동 (ArrowLeft)
    await page.keyboard.press('ArrowLeft');
    await expect(page.locator('.ML__container')).toBeVisible();

    // MathLive가 다시 렌더링되고 selection이 설정될 때까지 대기
    await page.waitForTimeout(100);

    // MathLive의 selection 상태 확인
    const selectionInfo = await page.locator('math-field').evaluate((mathfield) => {
      type MathfieldElement = Element & {
        selection?: { ranges?: Array<[number, number]>; direction?: string };
        value?: string;
      };
      const mf = mathfield as MathfieldElement;
      const selection = mf.selection;
      if (!selection) return { found: false, ranges: null, isAllSelected: false };

      const firstRange = selection.ranges?.[0];
      const valueLength = mf.value?.length || 0;

      // 전체 선택 확인:
      // - [0, -1]: 설정 시 사용되는 "끝까지" 특수값
      // - [0, valueLength]: 실제 읽을 때 구체적인 끝 위치
      const isAllSelected = firstRange?.[0] === 0 && (firstRange?.[1] === -1 || firstRange?.[1] === valueLength);

      return {
        found: true,
        ranges: firstRange,
        valueLength,
        isAllSelected,
      };
    });

    // 전체 선택 여부 확인
    expect(selectionInfo.found).toBe(true);
    expect(selectionInfo.isAllSelected).toBe(true);
  });

  await test.step('[TC-4.3.10] 수식 블럭 안에서 방향키 입력 -> 수식 블럭 안에서 커서가 이동한다', async () => {
    // 📍 UI Path: 채팅방(수학 튜터) > 수식 블럭 삽입
    // 🎬 When: 수식 블럭 안에서 방향키 입력
    // ✅ Then: 수식 블럭 안에서 커서가 이동한다

    // 현재 MathLive의 selection 상태 가져오기 (전체 선택된 상태)
    const beforeSelection = await page.locator('math-field').evaluate((mathfield) => {
      type MathfieldElement = Element & {
        selection?: { ranges?: Array<[number, number]>; direction?: string };
      };
      const selection = (mathfield as MathfieldElement).selection;
      return selection?.ranges?.[0] || null;
    });

    // ArrowRight 입력하여 커서 이동 (전체 선택 해제되고 끝으로 이동)
    await page.keyboard.press('ArrowRight');

    // 이동 후 selection 상태 확인
    const afterSelection = await page.locator('math-field').evaluate((mathfield) => {
      type MathfieldElement = Element & {
        selection?: { ranges?: Array<[number, number]>; direction?: string };
      };
      const selection = (mathfield as MathfieldElement).selection;
      return selection?.ranges?.[0] || null;
    });

    // selection이 변경되었는지 확인 (전체 선택에서 특정 위치로)
    expect(beforeSelection).not.toEqual(afterSelection);
    // 커서가 단일 위치가 되었는지 확인 (from === to이면 커서, from !== to이면 범위 선택)
    expect(afterSelection?.[0]).toEqual(afterSelection?.[1]);
    // popover는 여전히 열려있어야 함
    await expect(page.locator('.ML__container')).toBeVisible();
  });

  await test.step('[TC-4.3.11] 수식 블럭 안에서 백스페이스 입력 -> 수식 블럭 안에 텍스트가 지워진다', async () => {
    // 📍 UI Path: 채팅방(수학 튜터) > 수식 블럭 삽입
    // 🎬 When: 수식 블럭 안에서 백스페이스 입력
    // ✅ Then: 수식 블럭 안에 텍스트가 지워진다

    // 백스페이스 입력 전 MathLive의 값 확인
    const beforeValue = await page.locator('math-field').evaluate((mathfield) => {
      type MathfieldElement = Element & { value?: string };
      return (mathfield as MathfieldElement).value || '';
    });

    // MathLive의 selection 속성을 사용해 전체 선택
    await page.locator('math-field').evaluate((mathfield) => {
      type MathfieldElement = Element & {
        selection?: { ranges?: Array<[number, number]>; direction?: string };
      };
      const mf = mathfield as MathfieldElement;
      mf.selection = { ranges: [[0, -1]], direction: 'forward' };
    });

    // 전체 선택된 상태에서 백스페이스 입력 (모든 텍스트 삭제)
    await page.keyboard.press('Backspace');

    // 백스페이스 입력 후 값 확인
    const afterValue = await page.locator('math-field').evaluate((mathfield) => {
      type MathfieldElement = Element & { value?: string };
      return (mathfield as MathfieldElement).value || '';
    });

    // 모든 텍스트가 지워졌는지 확인
    expect(beforeValue).not.toBe('');
    expect(afterValue).toBe('');
    // popover는 여전히 열려있어야 함
    await expect(page.locator('.ML__container')).toBeVisible();
  });

  await test.step('[TC-4.3.9] 수식 블럭 안에 수학 및 논리 기호 입력 -> 수식 블럭 안에 수학 및 논리 기호 표시되고 띄어쓰기 불가 > 추가 입력 가능한 영역이 표시된다', async () => {
    // 📍 UI Path: 채팅방(수학 튜터) > 수식 블럭 삽입
    // 🎬 When: 수식 블럭 안에 수학 및 논리 기호 입력
    // ✅ Then: 수식 블럭 안에 수학 및 논리 기호 표시되고 띄어쓰기 불가 > 추가 입력 가능한 영역이 표시된다

    // MathLive에 포커스 (TC-4.3.11 이후 popover가 열려있는 상태)
    await page.locator('math-field').click();

    // 실제 키 입력으로 '/' 입력 (분수 입력 트리거)
    await page.keyboard.type('/');

    // 분수 형태(\frac)가 표시되고 placeholder가 두 개 있는지 확인
    await expect(page.locator('form')).toContainText('\\placeholder\\placeholder');
  });

  await test.step('[TC-4.3.12] 수식 가상키보드 열기 -> 수식 입력 popover의 키보드 아이콘을 누르면 가상키보드가 열리며 채팅 입력 영역이 가상키보드 위로 밀려 올라간다', async () => {
    // 📍 UI Path: 채팅방(수학 튜터) > 수식 블럭 삽입
    // 🎬 When: 수식 가상키보드 열기
    // ✅ Then: 수식 입력 popover의 키보드 아이콘을 누르면 가상키보드가 열리며 채팅 입력 영역이 가상키보드 위로 밀려 올라간다

    // 가상 키보드 열기 전 채팅 입력 영역의 위치 저장
    const chatInputBefore = await page.locator('form').boundingBox();

    // 가상 키보드 열기
    await page.getByRole('button', { name: 'Toggle Virtual Keyboard' }).click();

    // 가상 키보드가 표시될 때까지 대기
    await expect(page.locator('#math-virtual-keyboard-container')).toBeVisible();

    // 가상 키보드 열린 후 채팅 입력 영역의 위치 확인
    const chatInputAfter = await page.locator('form').boundingBox();

    // Y 좌표가 위로 이동했는지 확인 (y값이 작아짐)
    expect(chatInputBefore).not.toBeNull();
    expect(chatInputAfter).not.toBeNull();
    if (chatInputBefore && chatInputAfter) {
      expect(chatInputAfter.y).toBeLessThan(chatInputBefore.y);
    }
  });

  await test.step('[TC-4.3.13] 아이콘을 사용해 수식 가상키보드 닫기 -> 가상키보드가 열린 상태에서 수식 popover의 키보드 아이콘을 누르면 가상키보드가 닫힌다', async () => {
    // 📍 UI Path: 채팅방(수학 튜터) > 수식 블럭 삽입
    // 🎬 When: 아이콘을 사용해 수식 가상키보드 닫기
    // ✅ Then: 가상키보드가 열린 상태에서 수식 popover의 키보드 아이콘을 누르면 가상키보드가 닫힌다

    // 가상 키보드 토글 버튼 클릭 (닫기)
    await page.getByRole('button', { name: 'Toggle Virtual Keyboard' }).click();

    // 가상 키보드 컨테이너의 높이가 0이 되는지 확인
    const keyboardContainer = page.locator('#math-virtual-keyboard-container');
    await expect(keyboardContainer).toHaveCSS('height', '0px');
  });

  await test.step('[TC-4.3.14] 포커스 해제를 통한 수식 가상키보드 닫기 -> 수식 입력 popover가 닫히면 가상키보드가 닫힌다', async () => {
    // 📍 UI Path: 채팅방(수학 튜터) > 수식 블럭 삽입
    // 🎬 When: 포커스 해제를 통한 수식 가상키보드 닫기
    // ✅ Then: 수식 입력 popover가 닫히면 가상키보드가 닫힌다

    // 가상 키보드 열기
    await page.getByRole('button', { name: 'Toggle Virtual Keyboard' }).click();
    const keyboardContainer = page.locator('#math-virtual-keyboard-container');
    await expect(keyboardContainer).toBeVisible();

    // ProseMirror 영역 클릭하여 popover 닫기 (수식 블럭 밖)
    await page.locator('.ProseMirror').click();
    await expect(page.locator('.ML__container')).toBeHidden();

    // 가상 키보드도 자동으로 닫혀야 함
    await expect(keyboardContainer).toHaveCSS('height', '0px');
  });

  await test.step('[TC-4.3.17] 수식 블럭 뒤에서 백스페이스 입력 -> 수식 블럭 전체가 지워진다', async () => {
    // 📍 UI Path: 채팅방(수학 튜터) > 수식 블럭 삽입
    // 🎬 When: 수식 블럭 뒤에서 백스페이스 입력
    // ✅ Then: 수식 블럭 전체가 지워진다

    // ProseMirror의 수식 블럭이 존재하는지 확인
    const mathBlockExists = await page.evaluate(() => {
      // biome-ignore lint/suspicious/noExplicitAny: 테스트코드
      const view = (window as Window & { __editorView?: any }).__editorView;
      if (!view) return false;

      const { state } = view;
      let found = false;

      // biome-ignore lint/suspicious/noExplicitAny: 테스트코드
      state.doc.descendants((node: any) => {
        if (node.type.name === 'math_inline') {
          found = true;
          return false;
        }
        return true;
      });

      return found;
    });

    expect(mathBlockExists).toBe(true);

    // 수식 블럭 바로 뒤로 커서 이동
    await page.evaluate(() => {
      const view = (window as Window & { __editorView?: any }).__editorView;
      if (!view) return;

      const { state } = view;
      let mathNodeEndPos = -1;

      state.doc.descendants((node: any, pos: number) => {
        if (node.type.name === 'math_inline' && mathNodeEndPos === -1) {
          mathNodeEndPos = pos + node.nodeSize;
          return false;
        }
        return true;
      });

      if (mathNodeEndPos !== -1) {
        const tr = state.tr.setSelection((state.selection.constructor as any).create(state.doc, mathNodeEndPos));
        view.dispatch(tr);
      }
    });

    // 백스페이스 입력 (수식 블럭 전체 삭제)
    await page.keyboard.press('Backspace');

    // 수식 블럭이 삭제되었는지 확인
    const mathBlockDeleted = await page.evaluate(() => {
      const view = (window as Window & { __editorView?: any }).__editorView;
      if (!view) return true;

      const { state } = view;
      let found = false;

      state.doc.descendants((node: any) => {
        if (node.type.name === 'math_inline') {
          found = true;
          return false;
        }
        return true;
      });

      return !found; // 찾지 못했으면 삭제된 것
    });

    expect(mathBlockDeleted).toBe(true);
  });

  await test.step('[TC-4.3.15] 수식 블럭 안에서 가상 키 입력 -> 수식 블럭 안에 로마자/수학 및 논리 기호 표시되고 띄어쓰기 불가 > 추가 입력 가능한 영역이 표시된다', async () => {
    // 📍 UI Path: 채팅방(수학 튜터) > 수식 블럭 삽입
    // 🎬 When: 수식 블럭 안에서 가상 키 입력
    // ✅ Then: 수식 블럭 안에 로마자/수학 및 논리 기호 표시되고 띄어쓰기 불가 > 추가 입력 가능한 영역이 표시된다

    // 새 수식 블럭 생성
    await page.getByRole('button', { name: '수식 블럭 삽입' }).first().click();
    await expect(page.locator('.ML__container')).toBeVisible();

    // 가상 키보드 열기
    await page.getByRole('button', { name: 'Toggle Virtual Keyboard' }).click();
    await expect(page.locator('#math-virtual-keyboard-container')).toBeVisible();

    await page.waitForTimeout(100);
    await page.locator('.ML__content').click();
    await page.waitForTimeout(100);
    await page.getByLabel('\\sqrt{#0}').click();
    await page.waitForTimeout(100);
    await page.getByText('2■2').click();

    // 결과 확인: √2가 표시되어야 함
    const mathValue = await page.locator('math-field').evaluate((mf) => {
      // biome-ignore lint/suspicious/noExplicitAny: 테스트코드
      return (mf as any).value;
    });
    console.log(mathValue);

    expect(mathValue).toContain('sqrt');
    expect(mathValue).toContain('2');
  });
});

test('[TC-4.4] 수식 삽입 전송', async ({ page }) => {
  await test.step('[TC-4.4.1] 수식 블럭 안에 커서 위치 > 전송 버튼 클릭 -> 가상 키보드가 비활성화된다', async () => {
    // 📍 UI Path: 채팅방(수학 튜터) > 수식 블럭 삽입
    // 🎬 When: 수식 블럭 안에 커서 위치 > 전송 버튼 클릭
    // ✅ Then: 가상 키보드가 비활성화된다

    await page.goto('/math/chats?scenario=TC-4.1');

    // 새 수식 블럭 생성
    await page.getByRole('button', { name: '수식 블럭 삽입' }).first().click();
    await expect(page.locator('.ML__container')).toBeVisible();

    // 가상 키보드 열기
    await page.getByRole('button', { name: 'Toggle Virtual Keyboard' }).click();
    await expect(page.locator('#math-virtual-keyboard-container')).toBeVisible();

    await page.waitForTimeout(100);
    await page.locator('.ML__content').click();
    await page.waitForTimeout(100);
    await page.getByLabel('\\sqrt{#0}').click();
    await page.waitForTimeout(100);
    await page.getByText('2■2').click();

    await page.getByRole('button', { name: '채팅 전송' }).click();
    await expect(page.locator('#selection-popover-wrapper')).toContainText('2\\sqrt22');
  });

  await test.step('[TC-4.4.2] 수식 블럭 안에 커서 위치 > 엔터 키 입력 -> 수식 블럭 오른쪽으로 커서 이동 > 가상 키보드가 비활성화된다', async () => {
    // 📍 UI Path: 채팅방(수학 튜터) > 수식 블럭 삽입
    // 🎬 When: 수식 블럭 안에 커서 위치 > 엔터 키 입력
    // ✅ Then: 수식 블럭 오른쪽으로 커서 이동 > 가상 키보드가 비활성화된다

    await page.getByRole('button', { name: '수식 블럭 삽입' }).first().click();
    await expect(page.locator('.ML__container')).toBeVisible();
  });
});

test('[TC-4.5] 이미지 업로드', async ({ page, mockApiResponses }) => {
  await test.step('[TC-4.5.1] 이미지 업로드 버튼 클릭 -> 파일 선택창 팝업이 노출된다', async () => {
    // 📍 UI Path: 채팅방 > 이미지 업로드
    // 🎬 When: 이미지 업로드 버튼 클릭
    // ✅ Then: 파일 선택창 팝업이 노출된다

    await page.goto('/math/chats?scenario=TC-4.1');

    // 파일 선택 다이얼로그는 네이티브 OS 다이얼로그이므로 직접 테스트 불가
    // 대신 fileChooser 이벤트가 발생하는지 확인
    const fileChooserPromise = page.waitForEvent('filechooser');
    await page.getByRole('button', { name: '이미지 업로드' }).click();
    const fileChooser = await fileChooserPromise;

    // 파일 선택기가 올바른 accept 속성을 가지고 있는지 확인
    expect(fileChooser.isMultiple()).toBe(false); // 1개씩만 업로드 가능
  });

  await test.step('[TC-4.5.2] 형식: PNG, JPG, JPEG -> 파일 선택 버튼이 활성화된다', async () => {
    // 📍 UI Path: 채팅방 > 이미지 업로드
    // 🎬 When: 형식: PNG, JPG, JPEG
    // ✅ Then: 파일 선택 버튼이 활성화된다

    // 파일 선택 다이얼로그 열기
    const fileChooserPromise = page.waitForEvent('filechooser');
    await page.getByRole('button', { name: '이미지 업로드' }).click();
    const fileChooser = await fileChooserPromise;

    // input 요소의 accept 속성 확인
    const inputElement = fileChooser.element();
    const acceptValue = await inputElement.getAttribute('accept');

    // .jpeg, .png, .jpg 형식이 허용되는지 확인
    expect(acceptValue).toContain('.jpeg');
    expect(acceptValue).toContain('.png');
    expect(acceptValue).toContain('.jpg');
  });

  await test.step('[TC-4.5.3] 0Byte 파일 제출 -> 에러 토스트를 표시한다', async () => {
    // 📍 UI Path: 채팅방 > 이미지 업로드
    // 🎬 When: 0Byte 파일 제출
    // ✅ Then: 에러 토스트를 표시한다

    const fileChooserPromise = page.waitForEvent('filechooser');
    await page.getByRole('button', { name: '이미지 업로드' }).click();
    const fileChooser = await fileChooserPromise;

    // zero-byte.png 파일 선택
    await fileChooser.setFiles(new URL('../test-images/zero-byte.png', import.meta.url).pathname);

    // 에러 토스트 메시지 확인 (sonner는 aria-live="polite"를 사용하는 section > ol > li 구조)
    await expect(
      page.locator('[aria-live="polite"] ol[data-sonner-toaster] li[data-sonner-toast]').first(),
    ).toBeVisible();
  });

  await test.step('[TC-4.5.4] 20MB를 초과하는 파일 제출 -> 에러 토스트를 표시한다', async () => {
    // 📍 UI Path: 채팅방 > 이미지 업로드
    // 🎬 When: 20MB를 초과하는 파일 제출
    // ✅ Then: 에러 토스트를 표시한다

    const fileChooserPromise = page.waitForEvent('filechooser');
    await page.getByRole('button', { name: '이미지 업로드' }).click();
    const fileChooser = await fileChooserPromise;

    // over-20mb.png 파일 선택
    await fileChooser.setFiles(new URL('../test-images/over-20mb.png', import.meta.url).pathname);

    // 에러 토스트 메시지 확인
    await expect(
      page.locator('[aria-live="polite"] ol[data-sonner-toaster] li[data-sonner-toast]').first(),
    ).toBeVisible();
  });

  await test.step('[TC-4.5.5] 가로, 세로가 5:1을 초과하는 파일(3000x300) 제출 -> 에러 토스트를 표시한다', async () => {
    // 📍 UI Path: 채팅방 > 이미지 업로드
    // 🎬 When: 가로, 세로가 5:1을 초과하는 파일(3000x300) 제출
    // ✅ Then: 에러 토스트를 표시한다

    const fileChooserPromise = page.waitForEvent('filechooser');
    await page.getByRole('button', { name: '이미지 업로드' }).click();
    const fileChooser = await fileChooserPromise;

    // ratio-5-1.png 파일 선택
    await fileChooser.setFiles(new URL('../test-images/ratio-5-1.png', import.meta.url).pathname);

    // 에러 토스트 메시지 확인
    await expect(
      page.locator('[aria-live="polite"] ol[data-sonner-toaster] li[data-sonner-toast]').first(),
    ).toBeVisible();
  });

  await test.step('[TC-4.5.6] 가로, 세로가 1:5을 초과하는 파일(300x3000) 제출 -> 에러 토스트를 표시한다', async () => {
    // 📍 UI Path: 채팅방 > 이미지 업로드
    // 🎬 When: 가로, 세로가 1:5을 초과하는 파일(300x3000) 제출
    // ✅ Then: 에러 토스트를 표시한다

    const fileChooserPromise = page.waitForEvent('filechooser');
    await page.getByRole('button', { name: '이미지 업로드' }).click();
    const fileChooser = await fileChooserPromise;

    // ratio-1-5.png 파일 선택
    await fileChooser.setFiles(new URL('../test-images/ratio-1-5.png', import.meta.url).pathname);

    // 에러 토스트 메시지 확인
    await expect(
      page.locator('[aria-live="polite"] ol[data-sonner-toaster] li[data-sonner-toast]').first(),
    ).toBeVisible();
  });

  await test.step('[TC-4.5.7] 긴 쪽이 2240px을 초과하는 파일(3000x600) 제출 -> 에러 토스트를 표시한다', async () => {
    // 📍 UI Path: 채팅방 > 이미지 업로드
    // 🎬 When: 긴 쪽이 2240px을 초과하는 파일(3000x600) 제출
    // ✅ Then: 에러 토스트를 표시한다

    const fileChooserPromise = page.waitForEvent('filechooser');
    await page.getByRole('button', { name: '이미지 업로드' }).click();
    const fileChooser = await fileChooserPromise;

    // long-side-over-2240px.png 파일 선택
    await fileChooser.setFiles(new URL('../test-images/long-side-over-2240px.png', import.meta.url).pathname);

    // 에러 토스트 메시지 확인
    await expect(
      page.locator('[aria-live="polite"] ol[data-sonner-toaster] li[data-sonner-toast]').first(),
    ).toBeVisible();
  });

  await test.step('[TC-4.5.8] 짧은 쪽이 4px 미만인 파일(10x2) 제출 -> 에러 토스트를 표시한다', async () => {
    // 📍 UI Path: 채팅방 > 이미지 업로드
    // 🎬 When: 짧은 쪽이 4px 미만인 파일(10x2) 제출
    // ✅ Then: 에러 토스트를 표시한다

    const fileChooserPromise = page.waitForEvent('filechooser');
    await page.getByRole('button', { name: '이미지 업로드' }).click();
    const fileChooser = await fileChooserPromise;

    // short-side-under-4px.png 파일 선택
    await fileChooser.setFiles(new URL('../test-images/short-side-under-4px.png', import.meta.url).pathname);

    // 에러 토스트 메시지 확인
    await expect(
      page.locator('[aria-live="polite"] ol[data-sonner-toaster] li[data-sonner-toast]').first(),
    ).toBeVisible();
  });

  await test.step('[TC-4.5.9] 형식: PNG, JPG, JPEG 크기: 0Byte 초과 20MB 이하 비율: 가로, 세로가 1:5 또는 5:1 이하 길이: 가로, 세로 중 긴 쪽은 2240px이하, 짧은 쪽은 4px 이상 -> 입력창에 이미지 첨부한 후, 이미지 업로드 버튼이 비활성화된다', async () => {
    // 📍 UI Path: 채팅방 > 이미지 업로드
    // 🎬 When: 형식: PNG, JPG, JPEG 크기: 0Byte 초과 20MB 이하 비율: 가로, 세로가 1:5 또는 5:1 이하 길이: 가로, 세로 중 긴 쪽은 2240px이하, 짧은 쪽은 4px 이상
    // ✅ Then: 입력창에 이미지 첨부한 후, 이미지 업로드 버튼이 비활성화된다

    const TC459 = JSON.parse(
      await fs.readFile(new URL('../../mocks/__data__/api-recorder/tc-4.5.9.json', import.meta.url), 'utf-8'),
    );
    await mockApiResponses(TC459);

    const fileChooserPromise = page.waitForEvent('filechooser');
    await page.getByRole('button', { name: '이미지 업로드' }).click();
    const fileChooser = await fileChooserPromise;

    // valid-1000x800.png 파일 선택
    await fileChooser.setFiles(new URL('../test-images/valid-1000x800.png', import.meta.url).pathname);

    // 이미지 업로드가 완료되어 버튼이 사라질 때까지 대기
    await expect(page.getByRole('button', { name: '이미지 업로드' })).toBeHidden();
  });

  await test.step('[TC-4.5.10] X 버튼 클릭 -> 첨부한 이미지 삭제한 후, 이미지 업로드 버튼이 활성화된다', async () => {
    // 📍 UI Path: 채팅방 > 이미지 업로드
    // 🎬 When: X 버튼 클릭
    // ✅ Then: 첨부한 이미지 삭제한 후, 이미지 업로드 버튼이 활성화된다

    // X 버튼 클릭
    await page.getByRole('button', { name: '첨부된 이미지 삭제' }).click();

    // 이미지가 삭제되었는지 확인
    await expect(page.locator('form img[alt="첨부된 이미지"]')).not.toBeVisible();

    // 이미지 업로드 버튼이 다시 활성화되는지 확인
    await expect(page.getByRole('button', { name: '이미지 업로드' })).toBeEnabled();
  });

  await test.step('[TC-4.5.11] 이미지 업로드 실패 -> 첨부한 이미지 썸네일 위해 재시도 버튼이 표시되고, 버튼을 누르면 업로드를 다시 시도한다', async () => {
    // 📍 UI Path: 채팅방 > 이미지 업로드
    // 🎬 When: 이미지 업로드 실패
    // ✅ Then: 첨부한 이미지 썸네일 위해 재시도 버튼이 표시되고, 버튼을 누르면 업로드를 다시 시도한다

    await page.goto('/math/chats?scenario=TC-4.5.11');

    const fileChooserPromise = page.waitForEvent('filechooser');
    await page.getByRole('button', { name: '이미지 업로드' }).click();
    const fileChooser = await fileChooserPromise;

    // valid-1000x800.png 파일 선택
    await fileChooser.setFiles(new URL('../test-images/valid-1000x800.png', import.meta.url).pathname);

    // 재시도 버튼이 표시되는지 확인
    await expect(page.getByRole('button', { name: '이미지 업로드 재시도' })).toBeVisible();

    // 재시도 버튼 클릭
    await page.getByRole('button', { name: '이미지 업로드 재시도' }).click();
  });
});

test('[TC-4.6] 이미지 전송', async ({ page }) => {
  await test.step('[TC-4.6.1] 입력창에 이미지 첨부 > 전송 버튼 클릭 -> 채팅창의 보낸 메시지에 이미지가 표시된다', async () => {
    // 📍 UI Path: 채팅방 > 이미지 업로드 > 채팅 전송
    // 🎬 When: 입력창에 이미지 첨부 > 전송 버튼 클릭
    // ✅ Then: 채팅창의 보낸 메시지에 이미지가 표시된다

    await page.goto('/english/chats?scenario=TC-4.6');

    const fileChooserPromise = page.waitForEvent('filechooser');
    await page.getByRole('button', { name: '이미지 업로드' }).click();
    const fileChooser = await fileChooserPromise;

    // valid-1000x800.png 파일 선택
    await fileChooser.setFiles(new URL('../test-images/valid-1000x800.png', import.meta.url).pathname);

    // 이미지 업로드가 완료되어 버튼이 사라질 때까지 대기
    await expect(page.getByRole('button', { name: '이미지 업로드' })).toBeHidden();

    // 텍스트 입력
    await page.locator('.ProseMirror').click();
    await page.locator('.ProseMirror').fill('123');

    // 채팅 전송
    await page.getByRole('button', { name: '채팅 전송' }).click();
  });

  await test.step('[TC-4.6.2] 보낸 메시지의 이미지 클릭 -> 이미지 보기가 활성화된다', async () => {
    // 📍 UI Path: 채팅방 > 이미지 업로드 > 채팅 전송
    // 🎬 When: 보낸 메시지의 이미지 클릭
    // ✅ Then: 이미지 보기가 활성화된다

    const previewImage = page.getByRole('img', { name: '이미지 미리보기' });
    await previewImage.click();

    // 이미지 보기 다이얼로그가 열렸는지 확인
    const dialog = page.getByRole('dialog');
    await expect(dialog).toBeVisible();
    await expect(dialog).toHaveAttribute('data-state', 'open');
  });
});

test('[TC-4.7] AI 튜터에게 질문', async ({ page }) => {
  await page.goto('/math/chats/114?scenario=TC-4.7');

  await test.step('[TC-4.7.1] 텍스트 드래그 -> 텍스트를 드래그한 후 AI 튜터에게 질문 버튼 활성화된다', async () => {
    // 📍 UI Path: 채팅방 > AI 튜터에게 질문
    // 🎬 When: 텍스트 드래그
    // ✅ Then: 텍스트를 드래그한 후 AI 튜터에게 질문 버튼 활성화된다

    // "채팅 메시지 목록" 섹션에서 마지막 article의 첫 번째 문장 찾기
    await page
      .getByText('x+1x\\frac{x+1}{x}xx+1 : 여기서 분자(x+1), 분모(x) 모두 다항식이지!')
      .click({ clickCount: 3 });

    // AI 튜터에게 질문 버튼이 활성화되는지 확인
    await expect(page.getByRole('button', { name: 'AI 튜터에게 질문' })).toBeVisible();
  });

  await test.step('[TC-4.7.2] AI 튜터에게 질문 버튼 클릭 -> 질문 버튼을 클릭하면 입력창에 드래드한 텍스트가 인용구로 표시된다', async () => {
    // 📍 UI Path: 채팅방 > AI 튜터에게 질문
    // 🎬 When: AI 튜터에게 질문 버튼 클릭
    // ✅ Then: 질문 버튼을 클릭하면 입력창에 드래드한 텍스트가 인용구로 표시된다

    await page.getByRole('button', { name: 'AI 튜터에게 질문' }).click();
    await expect(page.locator('form')).toContainText(
      '- : 여기서 분자(x+1), 분모(x) 모두 다항식이지! - $ \\frac{2y-3}{y^2+y-6} $',
    );
  });

  await test.step('[TC-4.7.3] AI 튜터에게 질문 버튼 클릭 -> 입력창에 마크다운 문법이 사용된 그대로 텍스트 표시된다', async () => {
    // 📍 UI Path: 채팅방 > AI 튜터에게 질문
    // 🎬 When: AI 튜터에게 질문 버튼 클릭
    // ✅ Then: 입력창에 마크다운 문법이 사용된 그대로 텍스트 표시된다

    await expect(page.locator('form')).toContainText(
      '- : 여기서 분자(x+1), 분모(x) 모두 다항식이지! - $ \\frac{2y-3}{y^2+y-6} $',
    );
  });
});
