/**
 * CLOVA Tutor
 * Copyright (c) 2026-present NAVER Cloud Corp.
 * MIT
 */

// 📝 Auto-generated by E2E-Autogen
// 🔧 Generated from: TC-6.1, TC-6.2, TC-6.3

import { test } from '@jjades/e2e-autogen/playwright';
import { expect } from '@playwright/test';

test('[TC-6.1] 직독직해 요청', async ({ page }) => {
  await page.goto('/english/chats/135?scenario=TC-6.1');

  await test.step("[TC-6.1.1] 채팅창에 'Small steps taken consistently can lead to surprisingly big changes. 이 문장 해석해줘'를 입력 -> 모델 응답의 가장 하단에 직독직해 Callout이 노출된다", async () => {
    // 📍 UI Path: (영어) 채팅방
    // 🎬 When: 채팅창에 'Small steps taken consistently can lead to surprisingly big changes. 이 문장 해석해줘'를 입력
    // ✅ Then: 모델 응답의 가장 하단에 직독직해 Callout이 노출된다

    await expect(page.locator('#selection-popover-wrapper')).toContainText(
      'Small steps taken consistently can lead to surprisingly big changes. 이 문장 해석해줘',
    );
    await expect(page.locator('#selection-popover-wrapper')).toContainText('직독직해 보기');
  });

  await test.step('[TC-6.1.2] 모델 응답 하단의 직독직해 Callout 토글 클릭 -> Callout이 열리며 직독직해 텍스트를 확인할 수 있다', async () => {
    // 📍 UI Path: (영어) 채팅방 > 채팅창 직독직해 callout
    // 🎬 When: 모델 응답 하단의 직독직해 Callout 토글 클릭
    // ✅ Then: Callout이 열리며 직독직해 텍스트를 확인할 수 있다

    await page.getByRole('button', { name: '직독직해 보기' }).click();
    await expect(page.getByLabel('직독직해 보기')).toContainText(
      'Small steps작은 발걸음들이/taken consistently꾸준히 취해질 때/can lead to이어질 수 있습니다/surprisingly big changes.놀랍게도 큰 변화들을/',
    );
  });
});

test('[TC-6.2] 문법, 단어 관련 학습 질의응답 요청', async ({ page }) => {
  await page.goto('/english/chats/136?scenario=TC-6.2');

  await test.step("[TC-6.2.1] 채팅창에 'consistently의 뜻이 뭐야?'를 입력 -> 모델 응답의 가장 하단에 관련 학습자료 Callout이 노출된다", async () => {
    // 📍 UI Path: (영어) 채팅방
    // 🎬 When: 채팅창에 'consistently의 뜻이 뭐야?'를 입력
    // ✅ Then: 모델 응답의 가장 하단에 관련 학습자료 Callout이 노출된다

    await expect(page.locator('#selection-popover-wrapper')).toContainText('consistently의 뜻이 뭐야?');
    await expect(page.getByRole('button', { name: '관련 학습자료 보기' })).toBeVisible();
  });

  await test.step('[TC-6.2.2] 모델 메시지 하단의 관련 학습 자료 Callout 토글 클릭 -> Callout이 열리며 관련 학습 자료에 해당하는 table을 확인할 수 있다', async () => {
    // 📍 UI Path: (영어) 채팅방 > 채팅창 관련 학습 자료 callout
    // 🎬 When: 모델 메시지 하단의 관련 학습 자료 Callout 토글 클릭
    // ✅ Then: Callout이 열리며 관련 학습 자료에 해당하는 table을 확인할 수 있다

    await page.getByRole('button', { name: '관련 학습자료 보기' }).click();
    await expect(page.getByLabel('관련 학습자료 보기')).toContainText(
      'consistent [컨시스턴트] 뜻품사예문해석일관된, 한결같은형용사Her performance has been consistent throughout the season.그녀의 성적은 시즌 내내 일관되었다.(의견, 행동 등이) 일치하는, 조화를 이루는형용사His actions are consistent with his words.그의 행동은 그의 말과 일치한다.',
    );
  });
});

test('[TC-6.3] 추가 질문하기', async ({ page }) => {
  await page.goto('/english/chats/136?scenario=TC-6.3');

  await test.step('[TC-6.3.1] 사용자가 입력한 질문이 단어, 문법에 대한 질의 응답일 경우 -> 랜덤으로 2개의 추가 질문이 추가 질문 리스트 UI로 노출된다', async () => {
    // 📍 UI Path: (영어) 채팅방 > 추가 질문하기
    // 🎬 When: 사용자가 입력한 질문이 단어, 문법에 대한 질의 응답일 경우
    // ✅ Then: 랜덤으로 2개의 추가 질문이 추가 질문 리스트 UI로 노출된다

    await expect(page.locator('h4')).toContainText('추가 질문하기');

    const questionList = page.getByRole('list', { name: '추가 질문 목록' }).first();
    const listItems = questionList.getByRole('listitem');
    await expect(listItems).toHaveCount(2);
  });

  await test.step('[TC-6.3.2] 노출된 추가 질문 1개를 선택하여 클릭 -> 클릭한 질문이 채팅창에 자동으로 전송된다', async () => {
    // 📍 UI Path: (영어) 채팅방 > 추가 질문하기
    // 🎬 When: 노출된 추가 질문 1개를 선택하여 클릭
    // ✅ Then: 클릭한 질문이 채팅창에 자동으로 전송된다

    const questionList = page.getByRole('list', { name: '추가 질문 목록' }).first();
    const listItem = questionList.getByRole('listitem').first();
    const listItemText = (await listItem.textContent()) ?? '';
    await listItem.click();
    await expect(page.locator('#selection-popover-wrapper')).toContainText(listItemText);
  });

  await test.step('[TC-6.3.3] 질문 전송 완료 -> 채팅창에서 추가 질문 리스트 UI가 사라지고 전송된 input(질문 내용)으로 대화가 이어진다', async () => {
    // 📍 UI Path: (영어) 채팅방
    // 🎬 When: 질문 전송 완료
    // ✅ Then: 채팅창에서 추가 질문 리스트 UI가 사라지고 전송된 input(질문 내용)으로 대화가 이어진다

    const questionList = page.getByRole('list', { name: '추가 질문 목록' });
    expect(questionList).toHaveCount(1);
  });

  await test.step('[TC-6.3.4] 랜덤 질문 미클릭 상태에서 채팅 입력 -> 입력창은 기존 입력 상태가 유지된다', async () => {
    // 📍 UI Path: (영어) 채팅방 > 채팅 입력
    // 🎬 When: 랜덤 질문 미클릭 상태에서 채팅 입력
    // ✅ Then: 입력창은 기존 입력 상태가 유지된다

    await page.locator('.ProseMirror').click();
    await page.locator('.ProseMirror').fill('다른 공부할래');
  });

  await test.step("[TC-6.3.5] 채팅창에 '다른 공부할래' 전송 -> 채팅창에서 추가 질문 리스트 UI가 사라지고 전송된 input(자유 입력)으로 대화가 시작된다", async () => {
    // 📍 UI Path: (영어) 채팅방 > 채팅 입력 > 채팅 전송
    // 🎬 When: 채팅창에 '다른 공부할래' 전송
    // ✅ Then: 채팅창에서 추가 질문 리스트 UI가 사라지고 전송된 input(자유 입력)으로 대화가 시작된다

    await page.getByRole('button', { name: '채팅 전송' }).click();
    await expect(page.locator('#selection-popover-wrapper')).toContainText('다른 공부할래');
  });
});
