/**
 * CLOVA Tutor
 * Copyright (c) 2026-present NAVER Cloud Corp.
 * MIT
 */

// 📝 Auto-generated by E2E-Autogen
// 🔧 Generated from: TC-7.1, TC-7.2, TC-7.3, TC-7.4, TC-7.5, TC-7.6, TC-7.7

import { test } from '@jjades/e2e-autogen/playwright';
import { expect } from '@playwright/test';

test('[TC-7.1] 학습 콘텐츠 영역 활성화', async ({ page }) => {
  // MSW scenario를 활성화하기 위해 URL에 scenario 파라미터 추가
  await page.goto('/math/chats?scenario=TC-7.1');

  // 테스트 시작 전 problem-store 로컬 스토리지 초기화
  await page.evaluate(() => {
    localStorage.removeItem('problem-store');
  });

  await test.step('[TC-7.1.1] 문제 추천 요청에 따른 트리거링 -> 학습 콘텐츠 영역이 활성화되며 대화창에 요약 카드가 함께 생성된다', async () => {
    // 📍 UI Path: 채팅방
    // 🎬 When: 문제 추천 요청에 따른 트리거링
    // ✅ Then: 학습 콘텐츠 영역이 활성화되며 대화창에 요약 카드가 함께 생성된다

    await page.locator('.ProseMirror').click();
    await page.locator('.ProseMirror').fill('문제 추천해줘');
    await page.getByRole('button', { name: '채팅 전송' }).click();
    await page.waitForURL('/math/chats/380/problem?problem_id=H1-M-004&scenario=TC-7.1');
  });

  await test.step('[TC-7.1.2] 학습 콘텐츠 영역 활성화 -> 학습 콘텐츠 영역에 추출된 문제 DB 정보가 정확하게 노출된다 - 학년, 난이도 - 문제 주제 - 문제 번호 - 문제 정보, 보기 및 입력창', async () => {
    // 📍 UI Path: 채팅방 > 학습 콘텐츠 영역
    // 🎬 When: 학습 콘텐츠 영역 활성화
    // ✅ Then: 학습 콘텐츠 영역에 추출된 문제 DB 정보가 정확하게 노출된다 - 학년, 난이도 - 문제 주제 - 문제 번호 - 문제 정보, 보기 및 입력창

    await expect(page.locator('header').filter({ hasText: '학습 문제 추천내가 푼 문제' })).toBeVisible();
    await expect(page.locator('#study-area-panel')).toContainText(
      '((x - 2)(x + 1))의 전개식은? 1x² - x - 22x² - x + 23x² + x - 24x² + 3x + 2채점하기',
    );
  });

  await test.step('[TC-7.1.3] 학습 콘텐츠 영역 활성화 -> 문제 정보 상단에 내가 푼 문제 버튼이 활성화된다', async () => {
    // 📍 UI Path: 채팅방 > 학습 콘텐츠 영역
    // 🎬 When: 학습 콘텐츠 영역 활성화
    // ✅ Then: 문제 정보 상단에 내가 푼 문제 버튼이 활성화된다

    await expect(page.getByRole('button', { name: '내가 푼 문제' })).toBeVisible();
  });

  await test.step('[TC-7.1.4] 학습 콘텐츠 영역 활성화 -> 접기(>) 버튼과 X 버튼이 활성화된다', async () => {
    // 📍 UI Path: 채팅방 > 학습 콘텐츠 영역
    // 🎬 When: 학습 콘텐츠 영역 활성화
    // ✅ Then: 접기(>) 버튼과 X 버튼이 활성화된다

    await expect(page.getByRole('button', { name: '추천 문제 영역 닫기' })).toBeVisible();
    await expect(page.getByRole('button', { name: '문제 추천 영역 토글' })).toBeVisible();
  });

  await test.step("[TC-7.1.5] 학습 콘텐츠 영역 활성화 -> 자동으로 '클로바 튜터에게 문제 질문하기'가 활성화되며 입력창에 연결 뱃지가 표시된다", async () => {
    // 📍 UI Path: 채팅방 > 학습 콘텐츠 영역
    // 🎬 When: 학습 콘텐츠 영역 활성화
    // ✅ Then: 자동으로 '클로바 튜터에게 문제 질문하기'가 활성화되며 입력창에 연결 뱃지가 표시된다

    await expect(page.getByRole('button', { name: '문제 질문중' })).toBeVisible();
  });

  await test.step('[TC-7.1.6] 학습 콘텐츠 영역 활성화 -> 1문제 이상 누적 호출된 경우, 하단의 페이지네이션이 활성화된다', async () => {
    // 📍 UI Path: 채팅방 > 학습 콘텐츠 영역
    // 🎬 When: 학습 콘텐츠 영역 활성화
    // ✅ Then: 1문제 이상 누적 호출된 경우, 하단의 페이지네이션이 활성화된다

    await page.locator('.ProseMirror').click();
    await page.locator('.ProseMirror').fill('다른 문제 더 추천해줘');
    await page.getByRole('button', { name: '채팅 전송' }).click();
    await page.waitForURL('/math/chats/380/problem?problem_id=H1-M-002&scenario=TC-7.1');
    await expect(page.getByRole('button', { name: '이전' }).first()).toBeVisible();
  });

  await test.step('[TC-7.1.7] 하단의 페이지네이션(이전/다음) 버튼 클릭 -> 호출된 문제 순서에 따라 해당 문제 정보로 이동한다', async () => {
    // 📍 UI Path: 채팅방 > 학습 콘텐츠 영역
    // 🎬 When: 하단의 페이지네이션(이전/다음) 버튼 클릭
    // ✅ Then: 호출된 문제 순서에 따라 해당 문제 정보로 이동한다

    await page.getByRole('button', { name: '이전' }).first().click();
    await page.waitForURL('/math/chats/380/problem?problem_id=H1-M-004&scenario=TC-7.1');
    await expect(
      page.getByText('((x - 2)(x + 1))의 전개식은? 1x² - x - 22x² - x + 23x² + x - 24x² + 3x + 2채점하기'),
    ).toBeVisible();
  });
});

test('[TC-7.2] 학습 콘텐츠 영역 종료', async ({ page }) => {
  // MSW scenario를 활성화하기 위해 URL에 scenario 파라미터 추가
  await page.goto('/math/chats/380/problem?problem_id=H1-M-004&scenario=TC-7.2');

  // 테스트 시작 전 problem-store 로컬 스토리지 초기화
  await page.evaluate(() => {
    localStorage.removeItem('problem-store');
  });

  await test.step('[TC-7.2.1] X 버튼 클릭 -> 종료 확인 팝업이 노출된다', async () => {
    // 📍 UI Path: 채팅방 > 학습 콘텐츠 영역 > 종료
    // 🎬 When: X 버튼 클릭
    // ✅ Then: 종료 확인 팝업이 노출된다

    // 학습 콘텐츠 영역이 완전히 로드될 때까지 대기
    await page.waitForTimeout(1000);

    await page.getByRole('button', { name: '추천 문제 영역 닫기' }).click();
    await expect(page.getByRole('alertdialog', { name: '풀지 않은 문제가 있어요' })).toBeVisible();
  });

  await test.step("[TC-7.2.3] 종료 확인 팝업의 '취소' 클릭 -> 학습 콘텐츠 영역이 활성화된 상태가 그대로 유지된다", async () => {
    // 📍 UI Path: 채팅방 > 학습 콘텐츠 영역 > 종료
    // 🎬 When: 종료 확인 팝업의 '취소' 클릭
    // ✅ Then: 학습 콘텐츠 영역이 활성화된 상태가 그대로 유지된다

    await page.getByRole('button', { name: '취소' }).click();
    await expect(page.locator('header').filter({ hasText: '학습 문제 추천내가 푼 문제' })).toBeVisible();
  });

  await test.step("[TC-7.2.2] 종료 확인 팝업의 '종료하기' 클릭 -> 학습 콘텐츠 영역이 비활성화되고 대화창 요약 카드에 열기 버튼이 표시된다", async () => {
    // 📍 UI Path: 채팅방 > 학습 콘텐츠 영역 > 종료
    // 🎬 When: 종료 확인 팝업의 '종료하기' 클릭
    // ✅ Then: 학습 콘텐츠 영역이 비활성화되고 대화창 요약 카드에 열기 버튼이 표시된다

    await page.getByRole('button', { name: '추천 문제 영역 닫기' }).click();
    await page.getByRole('button', { name: '종료하기' }).click();
    await expect(page.locator('header').filter({ hasText: '학습 문제 추천내가 푼 문제' })).toBeHidden();
  });

  await test.step('[TC-7.2.4] 접기(>) 버튼 클릭 -> 종료 확인 팝업이 노출된다', async () => {
    // 📍 UI Path: 채팅방 > 학습 콘텐츠 영역 > 종료
    // 🎬 When: 접기(>) 버튼 클릭
    // ✅ Then: 종료 확인 팝업이 노출된다

    await page.getByRole('button', { name: '문제 추천 영역 토글' }).click();
    await page.getByRole('button', { name: '문제 추천 영역 토글' }).click();
    await expect(page.getByRole('alertdialog', { name: '풀지 않은 문제가 있어요' })).toBeVisible();
  });

  await test.step("[TC-7.2.6] 종료 확인 팝업의 '취소' 클릭 -> 학습 콘텐츠 영역이 활성화된 상태가 그대로 유지된다", async () => {
    // 📍 UI Path: 채팅방 > 학습 콘텐츠 영역 > 종료
    // 🎬 When: 종료 확인 팝업의 '취소' 클릭
    // ✅ Then: 학습 콘텐츠 영역이 활성화된 상태가 그대로 유지된다
    await page.getByRole('button', { name: '취소' }).click();
    await expect(page.locator('header').filter({ hasText: '학습 문제 추천내가 푼 문제' })).toBeVisible();
  });

  await test.step("[TC-7.2.5] 종료 확인 팝업의 '종료하기' 클릭 -> 학습 콘텐츠 영역이 비활성화되고 대화창 요약 카드에 열기 버튼이 표시된다", async () => {
    // 📍 UI Path: 채팅방 > 학습 콘텐츠 영역 > 종료
    // 🎬 When: 종료 확인 팝업의 '종료하기' 클릭
    // ✅ Then: 학습 콘텐츠 영역이 비활성화되고 대화창 요약 카드에 열기 버튼이 표시된다

    await page.getByRole('button', { name: '문제 추천 영역 토글' }).click();
    await page.getByRole('button', { name: '종료하기' }).click();
    await expect(page.locator('header').filter({ hasText: '학습 문제 추천내가 푼 문제' })).toBeHidden();
  });
});

test('[TC-7.3] 객관식 문제 풀기', async ({ page }) => {
  await page.goto('/math/chats/380/problem?problem_id=H1-M-002&scenario=TC-7.3');

  await test.step('[TC-7.3.1] 문제 추천 트리거링 -> 객관식 선택지 버튼이 활성화된다', async () => {
    // 📍 UI Path: 채팅방 > 학습 콘텐츠 영역
    // 🎬 When: 문제 추천 트리거링
    // ✅ Then: 객관식 선택지 버튼이 활성화된다

    await expect(
      page.getByText('((x + 3)(x + 5))의 전개식은? 1x² + 152x² + 8x + 153x² + 5x + 84x² + 3x + 15채점하기'),
    ).toBeVisible();
  });

  await test.step('[TC-7.3.2] 사용자가 선택지 버튼 클릭 시 -> 해당 선택지에 체크 아이콘이 표시되며 백그라운드 색상이 변경된다', async () => {
    // 📍 UI Path: 채팅방 > 학습 콘텐츠 영역
    // 🎬 When: 사용자가 선택지 버튼 클릭 시
    // ✅ Then: 해당 선택지에 체크 아이콘이 표시되며 백그라운드 색상이 변경된다

    await page.getByText('x² + 15').click();
    await expect(page.locator('.lucide.lucide-check')).toBeVisible();
    await expect(page.locator('label').filter({ hasText: '1x² +' })).toContainClass('bg-slate-100');
  });

  await test.step('[TC-7.3.3] 다른 선택지를 다시 클릭할 때 -> 이전 선택은 해제되고 마지막 선택지만 유지된다', async () => {
    // 📍 UI Path: 채팅방 > 학습 콘텐츠 영역
    // 🎬 When: 다른 선택지를 다시 클릭할 때
    // ✅ Then: 이전 선택은 해제되고 마지막 선택지만 유지된다

    await page.getByText('x² + 8x +').click();
    await expect(page.locator('label').filter({ hasText: '1x² +' })).not.toContainClass('bg-slate-100');
    await expect(page.locator('label').filter({ hasText: '2x² + 8x +' })).toContainClass('bg-slate-100');
  });

  await test.step('[TC-7.3.5] 정답일 경우 -> 정답 표시와 함께 선택지 상단 힌트 및 하단에 해설 정보가 표시되고 ‘채점하기’ 버튼이 비활성화된다', async () => {
    // 📍 UI Path: 채팅방 > 학습 콘텐츠 영역
    // 🎬 When: 정답일 경우
    // ✅ Then: 정답 표시와 함께 선택지 상단 힌트 및 하단에 해설 정보가 표시되고 ‘채점하기’ 버튼이 비활성화된다

    await page.getByRole('button', { name: '채점하기' }).click();
    await expect(page.locator('#study-area-panel')).toContainText(
      '1x² + 152x² + 8x + 15정답입니다!(x×x + 5x + 3x + 15)3x² + 5x + 84x² + 3x + 15',
    );
  });

  await test.step('[TC-7.3.6] 오답일 경우 -> 오답 표시와 함께 선택지 상단 힌트가 표시되고 사용자는 다른 선택지를 다시 선택할 수 있다', async () => {
    // 📍 UI Path: 채팅방 > 학습 콘텐츠 영역
    // 🎬 When: 오답일 경우
    // ✅ Then: 오답 표시와 함께 선택지 상단 힌트가 표시되고 사용자는 다른 선택지를 다시 선택할 수 있다

    await page.getByRole('button', { name: '이전' }).click();
    await page.locator('label').filter({ hasText: '4x² + 3x +' }).click();
    await page.getByRole('button', { name: '채점하기' }).click();
    await expect(page.locator('label').filter({ hasText: '4x² + 3x + 2' })).toContainClass('bg-accent-red-100');
    await expect(page.locator('#study-area-panel')).toContainText(
      '((x - 2)(x + 1))의 전개식은? 힌트 보기1x² - x - 22x² - x + 23x² + x - 24x² + 3x + 2채점하기',
    );
  });
});

test('[TC-7.4] 주관식 문제 풀기', async ({ page }) => {
  await test.step('[TC-7.4.1] 문제 추천 트리거링 -> 주관식 답안 입력창에 텍스트 입력이 가능해진다', async () => {
    // 📍 UI Path: 채팅방 > 학습 콘텐츠 영역
    // 🎬 When: 문제 추천 트리거링
    // ✅ Then: 주관식 답안 입력창에 텍스트 입력이 가능해진다

    await page.goto('/math/chats/129/problem?problem_id=H1-M-057&scenario=TC-7.4');
    await page.locator('.ML__container').click();
    await page.getByRole('textbox').fill('2', { force: true });
  });

  await test.step('[TC-7.4.4] 정답일 경우 -> 입력창 하단에 정답이 표시되고 해설 정보가 callout 형태로 나타나며 입력창 및 ‘채점하기’ 버튼이 비활성화된다', async () => {
    // 📍 UI Path: 채팅방 > 학습 콘텐츠 영역
    // 🎬 When: 정답일 경우
    // ✅ Then: 입력창 하단에 정답이 표시되고 해설 정보가 callout 형태로 나타나며 입력창 및 ‘채점하기’ 버튼이 비활성화된다

    await page.getByRole('button', { name: '채점하기' }).click();
    await expect(
      page
        .locator('div')
        .filter({ hasText: /^정답입니다!두 식을 연립하면 \(x\^2−2x−2=0\), D>0 → 교점 2개\.$/ })
        .nth(1),
    ).toBeVisible();
  });

  await test.step("[TC-7.4.5] 오답일 경우 -> 입력창 하단에 '오답입니다''다시 풀어보세요' 등의 오답 표시가 노출되고 재입력 및 채점하기 버튼 활성 상태가 유지된다", async () => {
    // 📍 UI Path: 채팅방 > 학습 콘텐츠 영역
    // 🎬 When: 오답일 경우
    // ✅ Then: 입력창 하단에 '오답입니다''다시 풀어보세요' 등의 오답 표시가 노출되고 재입력 및 채점하기 버튼 활성 상태가 유지된다

    await page.getByRole('button', { name: '다음' }).click();
    await page.locator('.ML__container').click();
    await page.getByRole('textbox').fill('2', { force: true });
    await page.getByRole('button', { name: '채점하기' }).click();
    await expect(page.getByRole('button', { name: '힌트 보기' })).toBeVisible();
  });

  await test.step('[TC-7.4.2] 사용자가 수식 입력 시 -> 수학 주관식 문제의 경우, 아이콘을 클릭하여 수식 블럭을 활성화하여 수식 입력이 가능하다', async () => {
    // 📍 UI Path: 채팅방 > 학습 콘텐츠 영역 > 수식 블럭
    // 🎬 When: 사용자가 수식 입력 시
    // ✅ Then: 수학 주관식 문제의 경우, 아이콘을 클릭하여 수식 블럭을 활성화하여 수식 입력이 가능하다

    await expect(page.locator('.ML__toggles')).toBeVisible();
  });
});

test('[TC-7.5] 다시 풀기', async ({ page }) => {
  await test.step('[TC-7.5.1] 사용자가 오답 문제를 다시 풀고 정답 처리할 때 -> 문제 상태가 ‘복습 완료’로 변경된다', async () => {
    // 📍 UI Path: 채팅방 > 학습 콘텐츠 영역 > 채점하기 버튼
    // 🎬 When: 사용자가 오답 문제를 다시 풀고 정답 처리할 때
    // ✅ Then: 문제 상태가 ‘복습 완료’로 변경된다

    await page.goto('/math/chats/129/problem?problem_id=H1-M-093&scenario=TC-7.5');
    await page.locator('.ML__container').click();
    await page.getByRole('textbox').fill('2', { force: true });
    await page.getByRole('button', { name: '채점하기' }).first().click();
    await expect(page.getByText('정답입니다!x↔y 바꾸고 y에 대해 정리')).toBeVisible();
  });
});

test('[TC-7.6] 내가 푼 문제 확인', async ({ page }) => {
  await page.goto('/math/chats/129/problem?problem_id=H1-M-093&scenario=TC-7.5');

  await test.step('[TC-7.6.1] 내가 푼 문제 버튼 클릭 -> 해당 채팅방에서 추천된 문제가 풀이 상태, 난이도, 카테고리 정보와 함께 드롭다운 리스트 형태로 표시된다', async () => {
    // 📍 UI Path: 채팅방 > 학습 콘텐츠 영역 > 내가 푼 문제
    // 🎬 When: 내가 푼 문제 버튼 클릭
    // ✅ Then: 해당 채팅방에서 추천된 문제가 풀이 상태, 난이도, 카테고리 정보와 함께 드롭다운 리스트 형태로 표시된다

    await page.getByRole('button', { name: '내가 푼 문제' }).click();
    await page.waitForTimeout(1000);
    await expect(page.getByRole('menu', { name: '내가 푼 문제' })).toBeVisible();
  });

  await test.step('[TC-7.6.2] 내가 푼 문제 드롭다운 리스트 클릭 -> 드롭다운에 포함된 문제 중, 원하는 문제 클릭 시 해당 문제가 학습 콘텐츠 영역에 노출된다', async () => {
    // 📍 UI Path: 채팅방 > 학습 콘텐츠 영역 > 내가 푼 문제
    // 🎬 When: 내가 푼 문제 드롭다운 리스트 클릭
    // ✅ Then: 드롭다운에 포함된 문제 중, 원하는 문제 클릭 시 해당 문제가 학습 콘텐츠 영역에 노출된다

    await page.getByRole('link', { name: '복습 완료 [고1] 나눗셈 계산' }).click();
    expect(page).toHaveURL('/math/chats/129/problem?problem_id=H1-M-016&scenario=TC-7.5');
  });
});

test('[TC-7.7] 클로바 튜터에게 문제 질문하기', async ({ page }) => {
  await page.goto('/math/chats/129/problem?problem_id=H1-M-093&scenario=TC-7.7');
  await page.waitForTimeout(1000);

  await test.step("[TC-7.7.1] 학습 콘텐츠 영역 활성화 -> 클로바 튜터에게 문제 질문하기' 버튼이 자동 활성화되며 입력창 아웃라인 색상이 변경 및 뱃지가 표시된다", async () => {
    // 📍 UI Path: 채팅방 > 학습 콘텐츠 영역 > 클로바 튜터에게 문제 질문하기
    // 🎬 When: 학습 콘텐츠 영역 활성화
    // ✅ Then: 클로바 튜터에게 문제 질문하기' 버튼이 자동 활성화되며 입력창 아웃라인 색상이 변경 및 뱃지가 표시된다

    await expect(page.getByRole('button', { name: '문제 질문중' })).toBeVisible();
  });

  await test.step("[TC-7.7.2] 클로바 튜터에게 문제 질문하기' 버튼 호버 -> 클로바 튜터에게 문제 질문하기' 툴팁이 플로팅된다", async () => {
    // 📍 UI Path: 채팅방 > 학습 콘텐츠 영역 > 클로바 튜터에게 문제 질문하기
    // 🎬 When: 클로바 튜터에게 문제 질문하기' 버튼 호버
    // ✅ Then: 클로바 튜터에게 문제 질문하기' 툴팁이 플로팅된다

    await page.getByRole('button', { name: '클로바 튜터에게 문제 질문하기' }).hover();
    await expect(page.locator('body')).toContainText('클로바 튜터에게 문제 질문하기클로바 튜터에게 문제 질문하기');
  });

  await test.step("[TC-7.7.3] 활성화된 '클로바 튜터에게 문제 질문하기' 버튼 클릭 -> 활성화되어 있는 버튼을 재클릭 할 경우, 연결이 해지되고 아웃라인은 기본 색상으로 돌아오며 입력창의 뱃지가 사라진다", async () => {
    // 📍 UI Path: 채팅방 > 학습 콘텐츠 영역 > 클로바 튜터에게 문제 질문하기
    // 🎬 When: 활성화된 '클로바 튜터에게 문제 질문하기' 버튼 클릭
    // ✅ Then: 활성화되어 있는 버튼을 재클릭 할 경우, 연결이 해지되고 아웃라인은 기본 색상으로 돌아오며 입력창의 뱃지가 사라진다

    await page.getByRole('button', { name: '클로바 튜터에게 문제 질문하기' }).click();
    await expect(page.getByRole('button', { name: '문제 질문중' })).toBeHidden();
  });

  await test.step("[TC-7.7.4] 입력창의 뱃지 x클릭 -> 문제 연결이 해지되고 '클로바 튜터에게 문제 질문하기' 버튼이 비활성화되며 아웃라인은 기본 색상으로 변경 및 뱃지가 사라진다", async () => {
    // 📍 UI Path: 채팅방 > 학습 콘텐츠 영역 > 클로바 튜터에게 문제 질문하기
    // 🎬 When: 입력창의 뱃지 x클릭
    // ✅ Then: 문제 연결이 해지되고 '클로바 튜터에게 문제 질문하기' 버튼이 비활성화되며 아웃라인은 기본 색상으로 변경 및 뱃지가 사라진다

    await page.getByRole('button', { name: '클로바 튜터에게 문제 질문하기' }).click();
    await page.getByRole('button', { name: '문제 질문중' }).click();
    await expect(page.getByRole('button', { name: '문제 질문중' })).toBeHidden();
  });

  await test.step("[TC-7.7.5] 학습 문제 추천 영역의 텍스트 드래그 -> 플로팅된 'AI 튜터에게 질문'을 누르면 '클로바 튜터에게 문제 질문하기' 버튼이 자동 활성화된다", async () => {
    // 📍 UI Path: 채팅방 > 학습 콘텐츠 영역 > 클로바 튜터에게 문제 질문하기
    // 🎬 When: 학습 문제 추천 영역의 텍스트 드래그
    // ✅ Then: 플로팅된 'AI 튜터에게 질문'을 누르면 '클로바 튜터에게 문제 질문하기' 버튼이 자동 활성화된다

    // 1. 타겟 텍스트 요소를 찾습니다.
    const targetText = page.getByText('역함수를').first();

    // 2. 요소의 위치와 크기 정보(x, y, width, height)를 가져옵니다.
    const box = await targetText.boundingBox();

    if (box) {
      // 3. 드래그 동작 수행
      // 텍스트의 왼쪽 중앙(시작점)으로 이동
      await page.mouse.move(box.x + 120, box.y + box.height / 2);

      // 마우스 버튼 누름 (클릭 유지)
      await page.mouse.down();

      // 텍스트의 오른쪽 중앙(끝점)으로 이동 (드래그)
      // steps 옵션을 주어 움직임을 부드럽게 만들면 드래그 인식률이 높아집니다.
      await page.mouse.move(box.x + 180, box.y + box.height / 2, { steps: 5 });

      // 마우스 버튼 뗌 (드롭)
      await page.mouse.up();
    }

    await page.waitForTimeout(100);
    await page.getByRole('button', { name: 'AI 튜터에게 질문' }).click();
    await expect(page.getByRole('button', { name: '문제 질문중' })).toBeVisible();
  });
});
