/**
 * CLOVA Tutor
 * Copyright (c) 2026-present NAVER Cloud Corp.
 * MIT
 */

// 📝 Auto-generated by E2E-Autogen
// 🔧 Generated from: TC-8.1, TC-8.2, TC-8.3, TC-8.4, TC-8.5, TC-8.6, TC-8.7

import { test } from '@jjades/e2e-autogen/playwright';
import { expect } from '@playwright/test';

test('[TC-8.1] 학습노트 문제 저장', async ({ page }) => {
  await test.step('[TC-8.1.1] 사용자가 저장하기 버튼 클릭 -> 해당 문제가 학습 노트에 카드로 저장되고, 저장 완료 토스트가 노출된다', async () => {
    // 📍 UI Path: 채팅 화면 > 학습 콘텐츠 영역
    // 🎬 When: 사용자가 저장하기 버튼 클릭
    // ✅ Then: 해당 문제가 학습 노트에 카드로 저장되고, 저장 완료 토스트가 노출된다

    await page.goto('/math/chats/380/problem?problem_id=H1-M-092&scenario=TC-8.1');
    await expect(page.getByLabel('toggle save problem bookmark')).toContainText('학습 노트에 저장하기');
  });

  await test.step("[TC-8.1.2] 동일 problem_id를 다른 chat_id에서 다시 저장하려고 시도 -> 학습노트에 이미 저장한 문제야! 복습을 위해 한번 더 저장할까?' 문구가 노출되며 저장 여부에 대해 재학습한다", async () => {
    // 📍 UI Path: 채팅 화면 > 학습 콘텐츠 영역
    // 🎬 When: 동일 problem_id를 다른 chat_id에서 다시 저장하려고 시도
    // ✅ Then: 학습노트에 이미 저장한 문제야! 복습을 위해 한번 더 저장할까?' 문구가 노출되며 저장 여부에 대해 재학습한다

    await page.getByRole('button', { name: '이전' }).click();
    await page.getByRole('button', { name: 'toggle save problem bookmark' }).click();
    await expect(page.getByRole('dialog', { name: '학습 노트에 이미 저장된 문제야!' })).toBeVisible();
  });
});

test('[TC-8.2] 학습노트 페이지 이동', async ({ page }) => {
  await test.step('[TC-8.2.1] 사용자가 학습 노트 페이지로 이동할 때 -> 저장된 문제 카드 리스트가 최신 상태로 렌더링된다', async () => {
    // 📍 UI Path: 사이드바 > 학습 노트 진입
    // 🎬 When: 사용자가 학습 노트 페이지로 이동할 때
    // ✅ Then: 저장된 문제 카드 리스트가 최신 상태로 렌더링된다

    await page.goto('math/chats');
    await page.getByRole('button', { name: '학습 노트' }).click();
    await page.waitForURL('math/problems/bookmark');
  });
});

test('[TC-8.3] 문제 상태 검색 필터링', async ({ page }) => {
  await test.step('[TC-8.3.1] 사용자가 필터 버튼 클릭 -> 정답·오답·복습 완료·풀지 않음 드롭다운 옵션이 노출된다', async () => {
    // 📍 UI Path: 학습 노트 페이지 > 필터 버튼
    // 🎬 When: 사용자가 필터 버튼 클릭
    // ✅ Then: 정답·오답·복습 완료·풀지 않음 드롭다운 옵션이 노출된다

    await page.goto('/math/problems/bookmark?scenario=TC-8.3');
    await page.getByRole('button', { name: '필터' }).click();
    await expect(page.getByRole('menu', { name: '필터' })).toBeVisible();
  });

  await test.step('[TC-8.3.2] 사용자가 풀이 상태 옵션 선택 -> 해당 상태의 문제 카드만 리스트에 표시된다', async () => {
    // 📍 UI Path: 학습 노트 페이지 > 필터 드롭다운
    // 🎬 When: 사용자가 풀이 상태 옵션 선택
    // ✅ Then: 해당 상태의 문제 카드만 리스트에 표시된다

    await page.getByRole('menuitemcheckbox', { name: '정답 정답' }).click();
    await expect(page.getByRole('link', { name: '복습 완료 ((x - 2)(x + 1' })).toBeHidden();
  });

  await test.step('[TC-8.3.3] 이미 선택된 옵션을 다시 클릭 -> 체크가 해제되고 전체 문제 리스트가 다시 노출된다', async () => {
    // 📍 UI Path: 학습 노트 페이지 > 필터 드롭다운
    // 🎬 When: 이미 선택된 옵션을 다시 클릭
    // ✅ Then: 체크가 해제되고 전체 문제 리스트가 다시 노출된다

    await page.getByRole('menuitemcheckbox', { name: '정답 정답' }).click();
    await page.locator('html').click();
    await expect(page.getByRole('link', { name: '복습 완료 y=3x−6의 역함수를 구하시오. 2025' })).toBeVisible();
  });
});

test('[TC-8.4] 문제 재풀이', async ({ page }) => {
  await test.step('[TC-8.4.1] 사용자가 저장된 문제 카드 클릭 -> 문제 정보가 및 풀이 상태가 표시된 재풀이 모드 다이얼로그가 노출된다', async () => {
    // 📍 UI Path: 학습 노트 페이지 > 문제 카드
    // 🎬 When: 사용자가 저장된 문제 카드 클릭
    // ✅ Then: 문제 정보가 및 풀이 상태가 표시된 재풀이 모드 다이얼로그가 노출된다

    await page.goto('/math/problems/bookmark?scenario=TC-8.4');
    await page.getByRole('link', { name: '복습 필요 정사각형의 한 변의 길이가 ((x + 2' }).click();
    await expect(
      page.getByLabel('[고1] 응용 계산학습컨텐츠 다이얼로그').getByText('정사각형의 한 변의 길이가 ((x + 2'),
    ).toBeVisible();
  });

  await test.step('[TC-8.4.3] 사용자가 다이얼로그에서 문제를 다시 풀고 답안을 제출 -> 채점이 수행되고 결과 상태가 업데이트된다', async () => {
    // 📍 UI Path: 학습 노트 > 재풀이 다이얼로그
    // 🎬 When: 사용자가 다이얼로그에서 문제를 다시 풀고 답안을 제출
    // ✅ Then: 채점이 수행되고 결과 상태가 업데이트된다

    await page.getByLabel('[고1] 응용 계산학습컨텐츠 다이얼로그').getByText('x² + 4x +').click();
    await page.getByRole('button', { name: '채점하기' }).click();
  });

  await test.step('[TC-8.4.2] 문제 다이얼로그가 노출된 상태에서 새로고침 -> 새로고침해도 현재 열려있는 다이얼로그가 유지된다', async () => {
    // 📍 UI Path: 학습 노트 페이지 > 문제 카드
    // 🎬 When: 문제 다이얼로그가 노출된 상태에서 새로고침
    // ✅ Then: 새로고침해도 현재 열려있는 다이얼로그가 유지된다

    await expect(page.getByLabel('[고1] 응용 계산학습컨텐츠 다이얼로그').getByText('x² + 4x +').first()).toBeVisible();
    await page.reload();
    await page.waitForTimeout(200);
    await expect(page.getByLabel('[고1] 응용 계산학습컨텐츠 다이얼로그').getByText('x² + 4x +').first()).toBeVisible();
  });
});

test('[TC-8.5] 학습 목표 달성', async ({ page }) => {
  await test.step('[TC-8.5.2] 사용자가 학습 목표가 설정된 다이얼로그에서 문제를 풀었지만 오답이었을 때 -> 오답 표시와 함께 선택지 상단 힌트가 표시되고 사용자는 다른 선택지를 다시 선택하여 채점하기 버튼을 클릭할 수 있다', async () => {
    // 📍 UI Path: 학습 노트 > 재풀이 다이얼로그
    // 🎬 When: 사용자가 학습 목표가 설정된 다이얼로그에서 문제를 풀었지만 오답이었을 때
    // ✅ Then: 오답 표시와 함께 선택지 상단 힌트가 표시되고 사용자는 다른 선택지를 다시 선택하여 채점하기 버튼을 클릭할 수 있다

    await page.goto('/math/problems/bookmark?scenario=TC-8.5');
    await page.getByRole('link', { name: '풀지 않음 ((x + 3)(x + 5' }).click();

    const dialog = page.getByLabel('[고1');
    await dialog.locator('label').filter({ hasText: '1x² + 15' }).click();
    await expect(page.locator('.lucide.lucide-check')).toBeVisible();

    // 다이얼로그 내의 채점하기 버튼이 활성화될 때까지 대기 후 클릭
    const gradeButton = dialog.getByRole('button', { name: '채점하기' });
    await expect(gradeButton).toBeEnabled();
    await gradeButton.click();
  });

  await test.step('[TC-8.5.3] 재풀이 채점 완료 시, 정답 또는 오답 피드백을 받았을 때 -> 문제 카드의 문제 상태 배지가 풀이 상태에 맞춰 업데이트된다', async () => {
    // 📍 UI Path: 학습 노트 > 재풀이 다이얼로그
    // 🎬 When: 재풀이 채점 완료 시, 정답 또는 오답 피드백을 받았을 때
    // ✅ Then: 문제 카드의 문제 상태 배지가 풀이 상태에 맞춰 업데이트된다

    // 이미 이전 스텝에서 '힌트 보기' 버튼 확인 완료
    await expect(page.getByRole('button', { name: '힌트 보기' })).toBeVisible();
  });

  await test.step('[TC-8.5.1] 사용자가 학습 목표가 설정된 다이얼로그에서 문제를 풀고 정답을 맞춰 목표 달성 -> 진행률 100% 달성 시점에 축하 메시지와 함께 confetti 애니메이션이 나타난다 정답 표시와 함께 선택지 상단 힌트 및 하단에 해설 정보가 표시되고 ‘채점하기’ 버튼이 비활성화된다', async () => {
    // 📍 UI Path: 학습 노트 > 재풀이 다이얼로그
    // 🎬 When: 사용자가 학습 목표가 설정된 다이얼로그에서 문제를 풀고 정답을 맞춰 목표 달성
    // ✅ Then: 진행률 100% 달성 시점에 축하 메시지와 함께 confetti 애니메이션이 나타난다 정답 표시와 함께 선택지 상단 힌트 및 하단에 해설 정보가 표시되고 ‘채점하기’ 버튼이 비활성화된다

    await page.getByLabel('[고1').locator('label').filter({ hasText: '2x² + 8x +' }).click();
    await expect(page.locator('.lucide.lucide-check')).toBeVisible();
    await page.getByRole('button', { name: '채점하기' }).click();
    expect(
      page.getByText('학습 목표 달성!오늘도 스스로 세운 목표를 끝까지 해냈네! 정말 멋져👍다음 목표도 함께 도전해보자!'),
    ).toBeVisible();
  });

  await test.step('[TC-8.5.4] 다이얼로그 좌, 우의 페이지네이션 버튼 클릭 -> 양 옆의 문제로 페이지네이션이 가능하여 문제를 확인할 수 있다', async () => {
    // 📍 UI Path: 학습 노트 > 재풀이 다이얼로그
    // 🎬 When: 다이얼로그 좌, 우의 페이지네이션 버튼 클릭
    // ✅ Then: 양 옆의 문제로 페이지네이션이 가능하여 문제를 확인할 수 있다

    await page.getByRole('button', { name: '다음 문제' }).click();
    await expect(
      page.getByLabel('[고1] 응용 계산학습컨텐츠 다이얼로그').getByText('정사각형의 한 변의 길이가 ((x + 2'),
    ).toBeVisible();
  });
});

test.skip('[TC-8.6] 채팅방에서 질문하기', async () => {
  await test.step.skip(
    '[TC-8.6.1] 사용자가 ‘채팅방에서 질문하기’ 버튼 클릭 -> 해당 문제가 추천된 chat_id 기반 원본 채팅방으로 이동하여 대화를 지속할 수 있다',
    async () => {
      // 📍 UI Path: 학습 노트 페이지 > 문제 카드 > 채팅방에서 질문하기
      // 🎬 When: 사용자가 ‘채팅방에서 질문하기’ 버튼 클릭
      // ✅ Then: 해당 문제가 추천된 chat_id 기반 원본 채팅방으로 이동하여 대화를 지속할 수 있다
    },
  );
});

test('[TC-8.7] 북마크 설정', async ({ page }) => {
  await page.goto('/math/problems/bookmark?scenario=TC-8.7');

  await test.step.skip(
    '[TC-8.7.1] 북마크가 켜져있는 상태에서 북마크 아이콘 클릭 -> 해당 문제의 북마크가 해제되며, 아이콘이 변경되고 카드 UI는 그대로 유지된다',
    async () => {
      // 📍 UI Path: 학습 노트 > 문제 카드
      // 🎬 When: 북마크가 켜져있는 상태에서 북마크 아이콘 클릭
      // ✅ Then: 해당 문제의 북마크가 해제되며, 아이콘이 변경되고 카드 UI는 그대로 유지된다

      await page.getByRole('button', { name: 'toggle problem bookmark' }).first().click();
      // 이 토글 버튼의 data-state가 off인지 확인
      await expect(page.getByRole('button', { name: 'toggle problem bookmark' }).first()).toHaveAttribute(
        'data-state',
        'off',
      );
    },
  );

  await test.step.skip(
    '[TC-8.7.2] 북마크가 해제된 상태에서 북마크 아이콘 클릭 -> 해당 문제의 북마크가 다시 켜지며, 아이콘이 변경되고 카드 UI는 그대로 유지된다',
    async () => {
      // 📍 UI Path: 학습 노트 > 문제 카드
      // 🎬 When: 북마크가 해제된 상태에서 북마크 아이콘 클릭
      // ✅ Then: 해당 문제의 북마크가 다시 켜지며, 아이콘이 변경되고 카드 UI는 그대로 유지된다

      await page.getByRole('button', { name: 'toggle problem bookmark' }).first().click();
      // 이 토글 버튼의 data-state가 on인지 확인
      await expect(page.getByRole('button', { name: 'toggle problem bookmark' }).first()).toHaveAttribute(
        'data-state',
        'on',
      );
    },
  );

  await test.step.skip(
    '[TC-8.7.3] 북마크가 해제된 상태에서 페이지 이동 혹은 새로고침 -> 북마크가 해제된 카드 UI가 사라진다',
    async () => {
      // 📍 UI Path: 학습 노트 > 문제 카드
      // 🎬 When: 북마크가 해제된 상태에서 페이지 이동 혹은 새로고침
      // ✅ Then: 북마크가 해제된 카드 UI가 사라진다

      // 먼저 북마크를 해제
      await page.getByRole('button', { name: 'toggle problem bookmark' }).first().click();

      // 페이지 이동
      await page.getByRole('tab', { name: '영어' }).click();
      await page.getByRole('tab', { name: '수학' }).click();

      // data-state가 off인 토글 버튼이 사라졌는지 확인 (북마크 해제된 문제 카드가 안 보임)
      await expect(page.locator('[data-state="off"][aria-label="toggle problem bookmark"]')).not.toBeVisible();
    },
  );
});
