# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: modelchat.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'modelchat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmodelchat.proto\x12\tmodelchat\"\xf0\x01\n\x0cModelRequest\x12\x0f\n\x07\x63hat_id\x18\x01 \x01(\x03\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12\r\n\x05grade\x18\x03 \x01(\x05\x12\x0f\n\x07user_id\x18\x04 \x01(\t\x12\x11\n\tuser_name\x18\x05 \x01(\t\x12\x12\n\nuser_query\x18\x06 \x01(\t\x12\x11\n\timage_url\x18\x07 \x03(\t\x12\x1e\n\x11vector_problem_id\x18\x08 \x01(\tH\x00\x88\x01\x01\x12\x1a\n\x12translation_button\x18\t \x01(\x08\x12\x12\n\nrequest_id\x18\n \x01(\tB\x14\n\x12_vector_problem_id\",\n\x16\x43reateChatTitleRequest\x12\x12\n\nuser_input\x18\x01 \x01(\t\"L\n\x12RecommendationInfo\x12\x16\n\x0erecommend_tool\x18\x01 \x01(\x08\x12\x1e\n\x16recommended_problem_id\x18\x02 \x01(\t\"p\n\x12PresentationOption\x12\x16\n\x0eresponse_style\x18\x01 \x01(\t\x12%\n\x18has_translation_response\x18\x02 \x01(\x08H\x00\x88\x01\x01\x42\x1b\n\x19_has_translation_response\"\x84\x02\n\rModelResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x63reated\x18\x02 \x01(\x03\x12\x0e\n\x06\x66inish\x18\x03 \x01(\x08\x12\x16\n\x0emodel_response\x18\x04 \x01(\t\x12\x14\n\x07subject\x18\x05 \x01(\tH\x00\x88\x01\x01\x12 \n\x18reference_image_document\x18\x06 \x03(\t\x12\x35\n\x0erecommendation\x18\x07 \x01(\x0b\x32\x1d.modelchat.RecommendationInfo\x12\x33\n\x0cpresentation\x18\x08 \x03(\x0b\x32\x1d.modelchat.PresentationOptionB\n\n\x08_subject\"(\n\x17\x43reateChatTitleResponse\x12\r\n\x05title\x18\x01 \x01(\t2\xb3\x01\n\x0cModelService\x12G\n\x10GenerateResponse\x12\x17.modelchat.ModelRequest\x1a\x18.modelchat.ModelResponse0\x01\x12Z\n\x11GenerateChatTitle\x12!.modelchat.CreateChatTitleRequest\x1a\".modelchat.CreateChatTitleResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'modelchat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODELREQUEST']._serialized_start=31
  _globals['_MODELREQUEST']._serialized_end=271
  _globals['_CREATECHATTITLEREQUEST']._serialized_start=273
  _globals['_CREATECHATTITLEREQUEST']._serialized_end=317
  _globals['_RECOMMENDATIONINFO']._serialized_start=319
  _globals['_RECOMMENDATIONINFO']._serialized_end=395
  _globals['_PRESENTATIONOPTION']._serialized_start=397
  _globals['_PRESENTATIONOPTION']._serialized_end=509
  _globals['_MODELRESPONSE']._serialized_start=512
  _globals['_MODELRESPONSE']._serialized_end=772
  _globals['_CREATECHATTITLERESPONSE']._serialized_start=774
  _globals['_CREATECHATTITLERESPONSE']._serialized_end=814
  _globals['_MODELSERVICE']._serialized_start=817
  _globals['_MODELSERVICE']._serialized_end=996
# @@protoc_insertion_point(module_scope)
