# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import modelchat_pb2 as modelchat__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in modelchat_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModelServiceStub(object):
    """────────────────────────────────
    서비스 정의
    ────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateResponse = channel.unary_stream(
                '/modelchat.ModelService/GenerateResponse',
                request_serializer=modelchat__pb2.ModelRequest.SerializeToString,
                response_deserializer=modelchat__pb2.ModelResponse.FromString,
                _registered_method=True)
        self.GenerateChatTitle = channel.unary_unary(
                '/modelchat.ModelService/GenerateChatTitle',
                request_serializer=modelchat__pb2.CreateChatTitleRequest.SerializeToString,
                response_deserializer=modelchat__pb2.CreateChatTitleResponse.FromString,
                _registered_method=True)


class ModelServiceServicer(object):
    """────────────────────────────────
    서비스 정의
    ────────────────────────────────
    """

    def GenerateResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateChatTitle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateResponse': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateResponse,
                    request_deserializer=modelchat__pb2.ModelRequest.FromString,
                    response_serializer=modelchat__pb2.ModelResponse.SerializeToString,
            ),
            'GenerateChatTitle': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateChatTitle,
                    request_deserializer=modelchat__pb2.CreateChatTitleRequest.FromString,
                    response_serializer=modelchat__pb2.CreateChatTitleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'modelchat.ModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('modelchat.ModelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelService(object):
    """────────────────────────────────
    서비스 정의
    ────────────────────────────────
    """

    @staticmethod
    def GenerateResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/modelchat.ModelService/GenerateResponse',
            modelchat__pb2.ModelRequest.SerializeToString,
            modelchat__pb2.ModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateChatTitle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modelchat.ModelService/GenerateChatTitle',
            modelchat__pb2.CreateChatTitleRequest.SerializeToString,
            modelchat__pb2.CreateChatTitleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
