/**
 * CLOVA Tutor
 * Copyright (c) 2026-present NAVER Cloud Corp.
 * MIT
 */

import { ChevronLeft, ChevronRight, Delete, Space, Subscript, Superscript } from 'lucide-react';
import type { Key } from '../types/keys';

export const basicKeys: Key[] = [
  { label: '(', value: '(', action: 'text', tooltip: '왼쪽 괄호' },
  { label: ')', value: ')', action: 'text', tooltip: '오른쪽 괄호' },
  { label: '[', value: '[', action: 'text', tooltip: '왼쪽 대괄호' },
  { label: ']', value: ']', action: 'text', tooltip: '오른쪽 대괄호' },
  {
    label: '\\frac{?}{?}',
    value: '\\frac{?}{?}',
    action: 'latex',
    tooltip: '분수',
  },
  {
    label: <Superscript />,
    value: '^',
    action: 'text',
    tooltip: '윗첨자 (지수)',
  },
  { label: <Subscript />, value: '_', action: 'text', tooltip: '아랫첨자' },
  { label: '=', value: '=', action: 'text', tooltip: '같다 (=)' },
  { label: '<', value: '<', action: 'text', tooltip: '작다 (<)' },
  { label: '>', value: '>', action: 'text', tooltip: '크다 (>)' },
  {
    label: '\\pm',
    value: '\\pm',
    action: 'latex',
    tooltip: '플러스마이너스 (±)',
  },
  {
    label: '\\sqrt{}',
    value: '\\sqrt{}',
    action: 'latex',
    tooltip: '제곱근 (√)',
  },
  { label: 'x', value: 'x', action: 'text', tooltip: '문자 x' },
  { label: '7', value: '7', action: 'text', tooltip: '숫자 7' },
  { label: '8', value: '8', action: 'text', tooltip: '숫자 8' },
  { label: '9', value: '9', action: 'text', tooltip: '숫자 9' },
  { label: '-', value: '-', action: 'text', tooltip: '빼기 (-)' },
  { label: '+', value: '+', action: 'text', tooltip: '더하기 (+)' },
  { label: '\\times', value: '*', action: 'text', tooltip: '곱하기 (×)' },
  { label: '\\div', value: '\\div', action: 'latex', tooltip: '나누기 (÷)' },
  {
    label: '\\therefore',
    value: '\\therefore',
    action: 'latex',
    tooltip: '따라서 (∴)',
  },
  { label: '\\neq', value: '\\neq', action: 'latex', tooltip: '같지 않다 (≠)' },
  {
    label: '\\approx',
    value: '\\approx',
    action: 'latex',
    tooltip: '대략 같다 (≈)',
  },
  {
    label: '\\infty',
    value: '\\infty',
    action: 'latex',
    tooltip: '무한대 (∞)',
  },
  { label: 'y', value: 'y', action: 'text', tooltip: '문자 y' },
  { label: '4', value: '4', action: 'text', tooltip: '숫자 4' },
  { label: '5', value: '5', action: 'text', tooltip: '숫자 5' },
  { label: '6', value: '6', action: 'text', tooltip: '숫자 6' },
  { label: '\\alpha', value: '\\alpha', action: 'latex', tooltip: '알파 (α)' },
  { label: '\\beta', value: '\\beta', action: 'latex', tooltip: '베타 (β)' },
  {
    label: '\\omega',
    value: '\\omega',
    action: 'latex',
    tooltip: '오메가 (ω)',
  },
  {
    label: '\\leq',
    value: '\\leq',
    action: 'latex',
    tooltip: '작거나 같다 (≤)',
  },
  {
    label: '\\geq',
    value: '\\geq',
    action: 'latex',
    tooltip: '크거나 같다 (≥)',
  },
  { label: '\\degree', value: '^\\circ', action: 'latex', tooltip: '도 (°)' },
  { label: ',', value: ',', action: 'text', tooltip: '쉼표 (,)' },
  { label: '.', value: '.', action: 'text', tooltip: '소수점 (.)' },
  { label: 'z', value: 'z', action: 'text', tooltip: '문자 z' },
  { label: '1', value: '1', action: 'text', tooltip: '숫자 1' },
  { label: '2', value: '2', action: 'text', tooltip: '숫자 2' },
  { label: '3', value: '3', action: 'text', tooltip: '숫자 3' },
  { label: '\\angle', value: '\\angle', action: 'latex', tooltip: '각 (∠)' },
  { label: '\\perp', value: '\\perp', action: 'latex', tooltip: '수직 (⊥)' },
  {
    label: '\\parallel',
    value: '\\parallel',
    action: 'latex',
    tooltip: '평행 (∥)',
  },
  {
    label: '\\triangle',
    value: '\\triangle',
    action: 'latex',
    tooltip: '삼각형 (△)',
  },
  {
    label: '\\text{cm}^2',
    value: '\\text{cm}^2',
    action: 'latex',
    tooltip: '제곱센티미터 (cm²)',
  },
  {
    label: '\\text{cm}^3',
    value: '\\text{cm}^3',
    action: 'latex',
    tooltip: '세제곱센티미터 (cm³)',
  },
  {
    label: '\\text{m}^2',
    value: '\\text{m}^2',
    action: 'latex',
    tooltip: '제곱미터 (m²)',
  },
  {
    label: '\\text{m}^3',
    value: '\\text{m}^3',
    action: 'latex',
    tooltip: '세제곱미터 (m³)',
  },
  { label: '\\pi', value: '\\pi', action: 'latex', tooltip: '원주율 파이 (π)' },
  {
    label: '\\because',
    value: '\\because',
    action: 'latex',
    tooltip: '왜냐하면 (∵)',
  },
  { label: '0', value: '0', action: 'text', tooltip: '숫자 0' },
  { label: '%', value: '%', action: 'text', tooltip: '퍼센트 (%)' },
  {
    label: <Space />,
    value: 'Space',
    className: 'col-span-4 w-full h-13 !text-4xl',
    action: 'keystroke',
    tooltip: '띄어쓰기',
  },
  {
    label: <ChevronLeft />,
    value: 'Left',
    action: 'keystroke',
    tooltip: '왼쪽 이동',
  },
  {
    label: <ChevronRight />,
    value: 'Right',
    action: 'keystroke',
    tooltip: '오른쪽 이동',
  },
  {
    label: <Delete />,
    value: 'Backspace',
    action: 'keystroke',
    tooltip: '지우기',
  },
  { label: '↵', value: 'Enter', action: 'keystroke', tooltip: '줄 바꿈' },
];
