/**
 * CLOVA Tutor
 * Copyright (c) 2026-present NAVER Cloud Corp.
 * MIT
 */

import { ChevronLeft, ChevronRight, Delete, Sigma, Space, Subscript, Superscript } from 'lucide-react';
import type { Key } from '../types/keys';

export const calculusKeys: Key[] = [
  { label: '(', value: '(', action: 'text', tooltip: '왼쪽 괄호' },
  { label: ')', value: ')', action: 'text', tooltip: '오른쪽 괄호' },
  { label: '|', value: '|', action: 'text', tooltip: '절대값 또는 조건' },
  { label: '[', value: '[', action: 'text', tooltip: '왼쪽 대괄호' },
  { label: ']', value: ']', action: 'text', tooltip: '오른쪽 대괄호' },
  {
    label: '\\sqrt{}',
    value: '\\sqrt{}',
    action: 'latex',
    tooltip: '제곱근 (√)',
  },
  {
    label: '\\sqrt[3]{}',
    value: '\\sqrt[3]{}',
    action: 'latex',
    tooltip: '세제곱근 (∛)',
  },
  {
    label: '\\geq',
    value: '\\geq',
    action: 'latex',
    tooltip: '크거나 같다 (≥)',
  },
  { label: <Sigma />, value: '\\sum', action: 'latex', tooltip: '합계 (Σ)' },
  { label: '\\int', value: '\\int', action: 'latex', tooltip: '적분 (∫)' },
  { label: 'f(x)', value: 'f(x)', action: 'latex', tooltip: '함수 f(x)' },
  { label: '^\\circ', value: '^\\circ', action: 'latex', tooltip: '도 (°)' },
  { label: 'x', value: 'x', action: 'text', tooltip: '문자 x' },
  { label: '7', value: '7', action: 'text', tooltip: '숫자 7' },
  { label: '8', value: '8', action: 'text', tooltip: '숫자 8' },
  { label: '9', value: '9', action: 'text', tooltip: '숫자 9' },
  {
    label: '\\frac{?}{?}',
    value: '\\frac{?}{?}',
    action: 'latex',
    tooltip: '분수',
  },
  {
    label: <Superscript />,
    value: '^',
    action: 'text',
    tooltip: '윗첨자 (지수)',
  },
  { label: <Subscript />, value: '_', action: 'text', tooltip: '아랫첨자' },
  {
    label: '\\leq',
    value: '\\leq',
    action: 'latex',
    tooltip: '작거나 같다 (≤)',
  },
  { label: '\\sin', value: '\\sin', action: 'latex', tooltip: '사인 함수' },
  { label: '\\cos', value: '\\cos', action: 'latex', tooltip: '코사인 함수' },
  { label: '\\tan', value: '\\tan', action: 'latex', tooltip: '탄젠트 함수' },
  { label: '\\theta', value: '\\theta', action: 'latex', tooltip: '세타 (θ)' },
  { label: 'y', value: 'y', action: 'text', tooltip: '문자 y' },
  { label: '4', value: '4', action: 'text', tooltip: '숫자 4' },
  { label: '5', value: '5', action: 'text', tooltip: '숫자 5' },
  { label: '6', value: '6', action: 'text', tooltip: '숫자 6' },
  { label: '/', value: '/', action: 'text', tooltip: '나누기 (÷)' },
  { label: '%', value: '%', action: 'text', tooltip: '퍼센트 (%)' },
  { label: '\\cdot', value: '\\cdot', action: 'latex', tooltip: '곱하기 (·)' },
  { label: '>', value: '>', action: 'text', tooltip: '크다 (>)' },
  { label: 'i', value: 'i', action: 'text', tooltip: '허수 단위 i' },
  { label: '\\pi', value: '\\pi', action: 'latex', tooltip: '원주율 파이 (π)' },
  {
    label: '\\log_{}{}',
    value: '\\log_{}{}',
    action: 'latex',
    tooltip: '로그 템플릿',
  },
  { label: 'e', value: 'e', action: 'text', tooltip: '자연상수 e' },
  { label: 'z', value: 'z', action: 'text', tooltip: '문자 z' },
  { label: '1', value: '1', action: 'text', tooltip: '숫자 1' },
  { label: '2', value: '2', action: 'text', tooltip: '숫자 2' },
  { label: '3', value: '3', action: 'text', tooltip: '숫자 3' },
  { label: '-', value: '-', action: 'text', tooltip: '빼기 (-)' },
  { label: '+', value: '+', action: 'text', tooltip: '더하기 (+)' },
  { label: '\\div', value: '\\div', action: 'latex', tooltip: '나누기 (÷)' },
  { label: '<', value: '<', action: 'text', tooltip: '작다 (<)' },
  {
    label: '\\lim_{n\\to{}}',
    value: '\\lim_{n\\to{}}',
    action: 'latex',
    tooltip: '리미트 템플릿',
  },
  {
    label: '\\infty',
    value: '\\infty',
    action: 'latex',
    tooltip: '무한대 (∞)',
  },
  { label: '\\ln', value: '\\ln', action: 'latex', tooltip: '자연로그' },
  { label: '!', value: '!', action: 'text', tooltip: '팩토리얼 (!)' },
  { label: ',', value: ',', action: 'text', tooltip: '쉼표 (,)' },
  { label: '.', value: '.', action: 'text', tooltip: '소수점 (.)' },
  { label: '0', value: '0', action: 'text', tooltip: '숫자 0' },
  { label: '=', value: '=', action: 'text', tooltip: '같다 (=)' },
  {
    label: <Space />,
    value: 'Space',
    className: 'col-span-4 w-full h-13 !text-4xl',
    action: 'keystroke',
    tooltip: '띄어쓰기',
  },
  {
    label: <ChevronLeft />,
    value: 'Left',
    action: 'keystroke',
    tooltip: '왼쪽 이동',
  },
  {
    label: <ChevronRight />,
    value: 'Right',
    action: 'keystroke',
    tooltip: '오른쪽 이동',
  },
  {
    label: <Delete />,
    value: 'Backspace',
    action: 'keystroke',
    tooltip: '지우기',
  },
  { label: '↵', value: 'Enter', action: 'keystroke', tooltip: '줄 바꿈' },
];
