"""remove_m_type_field

Revision ID: 65a73492a336
Revises: ea50b58d7fe0
Create Date: 2025-04-11 14:00:27.254436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '65a73492a336'
down_revision: Union[str, None] = 'ea50b58d7fe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'm_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('m_type', mysql.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
