"""refactor

Revision ID: 6e977ba3c1ec
Revises: 696ca92fcff2
Create Date: 2025-11-13 11:43:50.070829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6e977ba3c1ec'
down_revision: Union[str, None] = '696ca92fcff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('_chat_option_uc', table_name='chat_option')
    op.drop_table('chat_option')
    op.drop_index('_problem_option_uc', table_name='problem_option')
    op.drop_table('problem_option')
    op.add_column('chat', sa.Column('latest_used_at', sa.DateTime(), nullable=False))
    op.add_column('chat', sa.Column('grade', sa.Integer(), nullable=False))
    op.add_column('chat', sa.Column('subject', sa.String(length=50), nullable=False))
    op.alter_column('chat', 'user_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.Uuid(),
               comment=None,
               existing_comment='사용자 UUID',
               existing_nullable=False)
    op.alter_column('chat', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('chat', 'updated_at')
    op.add_column('chat_problem', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.add_column('chat_problem', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('chat_problem', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_index('_chat_problem_number_uc', table_name='chat_problem')
    op.drop_index('ix_chat_problem_chat_id_number', table_name='chat_problem')
    op.create_unique_constraint('uc_chat_id_problem_id', 'chat_problem', ['chat_id', 'problem_id'])
    op.alter_column('goal', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('goal', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('message', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.add_column('problem', sa.Column('url', sa.String(length=2048), nullable=True))
    op.add_column('problem', sa.Column('semester', sa.Integer(), nullable=True))
    op.add_column('problem', sa.Column('primary', sa.String(length=255), nullable=True))
    op.add_column('problem', sa.Column('secondary', sa.String(length=255), nullable=True))
    op.add_column('problem', sa.Column('specific', sa.String(length=255), nullable=True))
    op.add_column('problem', sa.Column('problem', sa.Text(), nullable=False))
    op.add_column('problem', sa.Column('choices', sa.Text(), nullable=True))
    op.add_column('problem', sa.Column('correct_answers', sa.Text(), nullable=False))
    op.add_column('problem', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('problem', sa.Column('hint', sa.Text(), nullable=True))
    op.add_column('problem', sa.Column('tags', sa.Text(), nullable=True))
    op.alter_column('problem', 'subject',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='과목',
               existing_nullable=False)
    op.alter_column('problem', 'grade',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='학년',
               existing_nullable=False)
    op.alter_column('problem', 'level',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='문제 난이도')
    op.alter_column('problem', 'category',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               comment=None,
               existing_comment='문제 카테고리',
               existing_nullable=True)
    op.alter_column('problem', 'type',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='문제 유형 (예: 단일선택 객관식, 다중선택 객관식, 주관식 등)',
               existing_nullable=False)
    op.alter_column('problem', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('problem', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('problem', 'short_answer_text')
    op.drop_column('problem', 'passage')
    op.drop_column('problem', 'image')
    op.drop_column('problem', 'instruction')
    op.drop_column('problem', 'vector_problem_id')
    op.alter_column('user', 'id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('user', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('user', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('user_unknown_concept', 'user_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('user_unknown_concept', 'subject',
               existing_type=mysql.VARCHAR(length=30),
               comment=None,
               existing_comment='과목',
               existing_nullable=False)
    op.alter_column('user_unknown_concept', 'key_concept',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='해당 과목 내 주요 개념(대단원)',
               existing_nullable=False)
    op.alter_column('user_unknown_concept', 'unknown_concept',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='실제로 모르는 세부 개념',
               existing_nullable=False)
    op.alter_column('user_unknown_concept', 'unknown_concept_reason',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='이유, 상황',
               existing_nullable=True)
    op.alter_column('user_unknown_concept', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('user_unknown_concept', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_unknown_concept', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('user_unknown_concept', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('user_unknown_concept', 'unknown_concept_reason',
               existing_type=mysql.TEXT(),
               comment='이유, 상황',
               existing_nullable=True)
    op.alter_column('user_unknown_concept', 'unknown_concept',
               existing_type=mysql.VARCHAR(length=100),
               comment='실제로 모르는 세부 개념',
               existing_nullable=False)
    op.alter_column('user_unknown_concept', 'key_concept',
               existing_type=mysql.VARCHAR(length=100),
               comment='해당 과목 내 주요 개념(대단원)',
               existing_nullable=False)
    op.alter_column('user_unknown_concept', 'subject',
               existing_type=mysql.VARCHAR(length=30),
               comment='과목',
               existing_nullable=False)
    op.alter_column('user_unknown_concept', 'user_id',
               existing_type=sa.Uuid(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('user', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('user', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('user', 'id',
               existing_type=sa.Uuid(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.add_column('problem', sa.Column('vector_problem_id', mysql.VARCHAR(length=50), nullable=False, comment='Vector DB에서 사용되는 Problem Id'))
    op.add_column('problem', sa.Column('instruction', mysql.TEXT(), nullable=True, comment='문제 지시사항'))
    op.add_column('problem', sa.Column('image', mysql.VARCHAR(length=255), nullable=True, comment='이미지 URL 등'))
    op.add_column('problem', sa.Column('passage', mysql.TEXT(), nullable=True, comment='문제 지문'))
    op.add_column('problem', sa.Column('short_answer_text', mysql.VARCHAR(length=255), nullable=True, comment='단답형 정답 텍스트'))
    op.alter_column('problem', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('problem', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('problem', 'type',
               existing_type=mysql.VARCHAR(length=50),
               comment='문제 유형 (예: 단일선택 객관식, 다중선택 객관식, 주관식 등)',
               existing_nullable=False)
    op.alter_column('problem', 'category',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               comment='문제 카테고리',
               existing_nullable=True)
    op.alter_column('problem', 'level',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='문제 난이도')
    op.alter_column('problem', 'grade',
               existing_type=mysql.INTEGER(),
               comment='학년',
               existing_nullable=False)
    op.alter_column('problem', 'subject',
               existing_type=mysql.VARCHAR(length=50),
               comment='과목',
               existing_nullable=False)
    op.drop_column('problem', 'tags')
    op.drop_column('problem', 'hint')
    op.drop_column('problem', 'explanation')
    op.drop_column('problem', 'correct_answers')
    op.drop_column('problem', 'choices')
    op.drop_column('problem', 'problem')
    op.drop_column('problem', 'specific')
    op.drop_column('problem', 'secondary')
    op.drop_column('problem', 'primary')
    op.drop_column('problem', 'semester')
    op.drop_column('problem', 'url')
    op.alter_column('message', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('goal', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('goal', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('uc_chat_id_problem_id', 'chat_problem', type_='unique')
    op.create_index('ix_chat_problem_chat_id_number', 'chat_problem', ['chat_id', 'number'], unique=False)
    op.create_index('_chat_problem_number_uc', 'chat_problem', ['chat_id', 'number'], unique=True)
    op.alter_column('chat_problem', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('chat_problem', 'updated_at')
    op.drop_column('chat_problem', 'user_id')
    op.add_column('chat', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.alter_column('chat', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('chat', 'user_id',
               existing_type=sa.Uuid(),
               type_=mysql.VARCHAR(length=36),
               comment='사용자 UUID',
               existing_nullable=False)
    op.drop_column('chat', 'subject')
    op.drop_column('chat', 'grade')
    op.drop_column('chat', 'latest_used_at')
    op.create_table('problem_option',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('problem_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('option_key', mysql.INTEGER(), autoincrement=False, nullable=False, comment='보기 키 (1, 2, 3, ...)'),
    sa.Column('option_value', mysql.TEXT(), nullable=False, comment='보기 내용'),
    sa.Column('is_correct', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='정답 여부'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('_problem_option_uc', 'problem_option', ['problem_id', 'option_key'], unique=True)
    op.create_table('chat_option',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('option_key', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('option_value', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('display_name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('_chat_option_uc', 'chat_option', ['chat_id', 'option_key'], unique=True)
    # ### end Alembic commands ###
