"""remove_problem_number_field

Revision ID: d2f41d7e9a4f
Revises: d77d035a8405
Create Date: 2025-04-18 15:40:33.606054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd2f41d7e9a4f'
down_revision: Union[str, None] = 'd77d035a8405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('number', mysql.INTEGER(), autoincrement=False, nullable=False, comment='문제 번호'))
    # ### end Alembic commands ###
