"""add_number_column_to_chat_problem

Revision ID: d77d035a8405
Revises: fff8d562c8fb
Create Date: 2025-04-18 15:11:50.719886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd77d035a8405'
down_revision: Union[str, None] = 'fff8d562c8fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_problem', sa.Column('number', sa.Integer(), nullable=False))
    op.drop_index('ix_chat_problem_chat_id_order', table_name='chat_problem')
    op.create_unique_constraint('_chat_problem_number_uc', 'chat_problem', ['chat_id', 'number'])
    op.create_index('ix_chat_problem_chat_id_number', 'chat_problem', ['chat_id', 'number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_problem_chat_id_number', table_name='chat_problem')
    op.drop_constraint('_chat_problem_number_uc', 'chat_problem', type_='unique')
    op.create_index('ix_chat_problem_chat_id_order', 'chat_problem', ['chat_id'], unique=False)
    op.drop_column('chat_problem', 'number')
    # ### end Alembic commands ###
