"""goal_status

Revision ID: ccf75e0c4543
Revises: ee2ff8d78844
Create Date: 2025-09-12 15:04:25.182151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccf75e0c4543'
down_revision: Union[str, None] = 'ee2ff8d78844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "goal",
        sa.Column("status", sa.String(length=10), nullable=True)
    )

    # 기존에 있던 테이블 데이터는 다 무효화 처리함!!
    op.execute("UPDATE goal SET status='CANCELLED' WHERE status IS NULL")

    op.alter_column(
        "goal",
        "status",
        existing_type=sa.String(length=10),
        nullable=False
    )
    op.drop_index('ix_goal_user_id', table_name='goal')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_goal_user_id', 'goal', ['user_id'], unique=False)
    op.drop_column('goal', 'status')
    # ### end Alembic commands ###
