"""add_problem_bookmarks

Revision ID: da911bae4b48
Revises: 8109a40b1c87
Create Date: 2025-11-25 12:19:01.423933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da911bae4b48'
down_revision: Union[str, None] = '8109a40b1c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_problem', sa.Column('is_bookmarked', sa.Boolean(), nullable=False))
    op.add_column('chat_problem', sa.Column('bookmarked_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_chat_problem_is_bookmarked'), 'chat_problem', ['is_bookmarked'], unique=False)
    op.create_index(op.f('ix_problem_subject'), 'problem', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problem_subject'), table_name='problem')
    op.drop_index(op.f('ix_chat_problem_is_bookmarked'), table_name='chat_problem')
    op.drop_column('chat_problem', 'bookmarked_at')
    op.drop_column('chat_problem', 'is_bookmarked')
    # ### end Alembic commands ###
