"""add_problem_table

Revision ID: ea50b58d7fe0
Revises: 43417594a9e5
Create Date: 2025-04-01 16:20:01.675793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea50b58d7fe0'
down_revision: Union[str, None] = '43417594a9e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.Integer(), nullable=False, comment='문제 번호'),
    sa.Column('subject', sa.String(length=50), nullable=False, comment='과목'),
    sa.Column('grade', sa.Integer(), nullable=False, comment='학년'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='문제 유형 (예: 단일선택 객관식, 다중선택 객관식, 주관식 등)'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='문제 카테고리'),
    sa.Column('level', sa.Integer(), nullable=True, comment='문제 난이도'),
    sa.Column('instruction', sa.Text(), nullable=True, comment='문제 지시사항'),
    sa.Column('passage', sa.Text(), nullable=True, comment='문제 지문'),
    sa.Column('image', sa.String(length=255), nullable=True, comment='이미지 URL 등'),
    sa.Column('short_answer_text', sa.String(length=255), nullable=True, comment='단답형 정답 텍스트'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problem_option',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('option_key', sa.Integer(), nullable=False, comment='보기 키 (1, 2, 3, ...)'),
    sa.Column('option_value', sa.Text(), nullable=False, comment='보기 내용'),
    sa.Column('is_correct', sa.Boolean(), nullable=False, comment='정답 여부'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem_id', 'option_key', name='_problem_option_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problem_option')
    op.drop_table('problem')
    # ### end Alembic commands ###
