"""add_vector_problem_id_field

Revision ID: 14cb8c2dabed
Revises: 1d8fe62ec43f
Create Date: 2025-05-13 11:32:47.759518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14cb8c2dabed'
down_revision: Union[str, None] = '1d8fe62ec43f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('vector_problem_id', sa.String(length=50), nullable=False, comment='Vector DB에서 사용되는 Problem Id'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'vector_problem_id')
    # ### end Alembic commands ###
