"""change_chat_table_user_uuid_id

Revision ID: b1b763bea8bb
Revises: 18b318d43d2e
Create Date: 2025-06-04 18:19:21.470348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b1b763bea8bb'
down_revision: Union[str, None] = '18b318d43d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat', 'user_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=36),
               comment='사용자 UUID',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat', 'user_id',
               existing_type=sa.String(length=36),
               type_=mysql.INTEGER(),
               comment=None,
               existing_comment='사용자 UUID',
               existing_nullable=False)
    # ### end Alembic commands ###
