"""add_status_field_into_chatproblem_table

Revision ID: 6e991aadc1eb
Revises: 6ccebf22df2d
Create Date: 2025-04-23 15:36:03.596582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e991aadc1eb'
down_revision: Union[str, None] = '6ccebf22df2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_problem', sa.Column('status', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_problem', 'status')
    # ### end Alembic commands ###
