"""change_user_uuid_id

Revision ID: 18b318d43d2e
Revises: a9cdf7c32c39
Create Date: 2025-06-04 15:20:15.417079

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "18b318d43d2e"
down_revision: Union[str, None] = "a9cdf7c32c39"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "id",
        existing_type=mysql.INTEGER(),
        type_=sa.String(length=36),
        existing_nullable=False,
    )
    op.alter_column(
        "user_unknown_concept",
        "user_id",
        existing_type=mysql.INTEGER(),
        type_=sa.String(length=36),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_unknown_concept",
        "user_id",
        existing_type=sa.String(length=36),
        type_=mysql.INTEGER(),
        existing_nullable=False,
    )
    op.add_column("user", sa.Column("uuid_id", sa.BINARY(length=16), nullable=True))
    op.alter_column(
        "user",
        "id",
        existing_type=sa.String(length=36),
        type_=mysql.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
