"""add_metadata_column_into_message_table

Revision ID: 1d8fe62ec43f
Revises: f4c180aff59a
Create Date: 2025-04-30 13:34:21.146759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d8fe62ec43f'
down_revision: Union[str, None] = 'f4c180aff59a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('meta_data', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'meta_data')
    # ### end Alembic commands ###
