"""problem_category_size_up

Revision ID: 696ca92fcff2
Revises: beb82d8233e9
Create Date: 2025-10-02 16:59:22.756950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '696ca92fcff2'
down_revision: Union[str, None] = 'beb82d8233e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('problem', 'category',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_comment='문제 카테고리',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('problem', 'category',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_comment='문제 카테고리',
               existing_nullable=True)
    # ### end Alembic commands ###
