"""create_user_unknown_concept_table

Revision ID: a9cdf7c32c39
Revises: 14cb8c2dabed
Create Date: 2025-05-22 16:28:37.902277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9cdf7c32c39'
down_revision: Union[str, None] = '14cb8c2dabed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_unknown_concept',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=30), nullable=False, comment='과목'),
    sa.Column('key_concept', sa.String(length=100), nullable=False, comment='해당 과목 내 주요 개념(대단원)'),
    sa.Column('unknown_concept', sa.String(length=100), nullable=False, comment='실제로 모르는 세부 개념'),
    sa.Column('unknown_concept_reason', sa.Text(), nullable=True, comment='이유, 상황'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'subject', 'key_concept', name='uq_user_subject_unknown')
    )
    op.create_index('idx_user_subject', 'user_unknown_concept', ['user_id', 'subject'], unique=False)
    op.create_index(op.f('ix_user_unknown_concept_user_id'), 'user_unknown_concept', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_unknown_concept_user_id'), table_name='user_unknown_concept')
    op.drop_index('idx_user_subject', table_name='user_unknown_concept')
    op.drop_table('user_unknown_concept')
    # ### end Alembic commands ###
