"""Goal

Revision ID: ee2ff8d78844
Revises: 8c52bf42fcd1
Create Date: 2025-09-09 11:06:05.359271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee2ff8d78844'
down_revision: Union[str, None] = '8c52bf42fcd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('goal_count', sa.Integer(), nullable=False),
    sa.Column('solved_count', sa.Integer(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('is_finish', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_user_id'), 'goal', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goal_user_id'), table_name='goal')
    op.drop_table('goal')
    # ### end Alembic commands ###
