"""add_last_answer_field_into_chatproblem

Revision ID: f4c180aff59a
Revises: 6e991aadc1eb
Create Date: 2025-04-24 16:18:16.103410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4c180aff59a'
down_revision: Union[str, None] = '6e991aadc1eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_problem', sa.Column('last_answer', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_problem', 'last_answer')
    # ### end Alembic commands ###
