// Generated by ts-to-zod
import { z } from 'zod';

export const systemHintDtoSchema = z.literal('translation_button');

export const subjectEnumDtoSchema = z.union([z.literal('math'), z.literal('english'), z.literal('science')]);

export const stopResponseStatusValueDtoSchema = z.literal('ok');

export const reActModelToolTypeDtoSchema = z.union([
  z.literal('translation'),
  z.literal('eng_voca'),
  z.literal('eng_grammar'),
  z.literal('table_fetch'),
  z.literal('answer_included'),
  z.literal('math_concept'),
  z.literal('stepwise_solution'),
  z.literal('solution_demonstration'),
  z.literal('recommend_problem'),
  z.literal('default_chat'),
]);

export const problemStatusDtoSchema = z.union([
  z.literal('\uD480\uC9C0 \uC54A\uC74C'),
  z.literal('\uC815\uB2F5'),
  z.literal('\uC624\uB2F5'),
  z.literal('\uBCF5\uC2B5 \uC644\uB8CC'),
]);

export const problemDuplicateStatusDtoSchema = z.union([z.literal('duplicate'), z.literal('unique')]);

export const messageRoleDtoSchema = z.union([z.literal('user'), z.literal('assistant'), z.literal('system')]);

export const chatStreamStatusDtoSchema = z.union([z.literal('IS_STREAMING'), z.literal('COMPLETE')]);

export const activeGoalResponseDtoSchema = z.object({
  id: z.number(),
  goal_count: z.number(),
  solved_count: z.number(),
});

export const chatCreateRequestBodyDtoSchema = z.object({
  title: z.string(),
  grade: z.string(),
  subject: z.string(),
});

export const chatDetailResponseDtoSchema = z.object({
  id: z.number(),
  title: z.string(),
  subject: z.string(),
  has_problem: z.boolean(),
  has_active_goal: z.boolean(),
  active_goal: activeGoalResponseDtoSchema.nullable(),
});

export const chatMessageMetadataRequestDtoSchema = z.object({
  system_hints: z.array(systemHintDtoSchema).optional().nullable(),
});

export const messageAuthorDtoSchema = z.object({
  role: messageRoleDtoSchema,
});

export const chatMessageStopResponseDtoSchema = z.object({
  status: stopResponseStatusValueDtoSchema,
});

export const chatProblemResponseDtoSchema = z.object({
  id: z.string(),
  number: z.number(),
  status: problemStatusDtoSchema,
  category: z.string().optional().nullable(),
  grade: z.number(),
  level: z.number(),
});

export const multipleChoiceAnswerDtoSchema = z.object({
  type: z.literal('\uB2E4\uC911\uC120\uD0DD \uAC1D\uAD00\uC2DD'),
  answer: z.array(z.number()),
});

export const multipleShortAnswerDtoSchema = z.object({
  type: z.literal('\uB2E4\uC911\uC751\uB2F5 \uC8FC\uAD00\uC2DD'),
  answer: z.array(z.string()),
});

export const singleChoiceAnswerDtoSchema = z.object({
  type: z.literal('\uB2E8\uC77C\uC120\uD0DD \uAC1D\uAD00\uC2DD'),
  answer: z.number(),
});

export const singleShortAnswerDtoSchema = z.object({
  type: z.literal('\uB2E8\uC77C\uC751\uB2F5 \uC8FC\uAD00\uC2DD'),
  answer: z.string(),
});

export const chatProblemSubmitResponseDtoSchema = z.object({
  is_correct: z.boolean(),
  active_goal: activeGoalResponseDtoSchema.nullable(),
});

export const chatQuoteSourceDtoSchema = z.object({
  type: z.literal('chat'),
  chat_id: z.number(),
});

export const chatResponseDtoSchema = z.object({
  id: z.number(),
  title: z.string(),
  subject: z.string(),
  has_problem: z.boolean(),
  has_active_goal: z.boolean(),
  latest_used_at: z.string().datetime({ offset: true }),
});

export const chatStreamStatusResponseDtoSchema = z.object({
  status: chatStreamStatusDtoSchema,
});

export const chatTitleUpdateRequestBodyDtoSchema = z.object({
  title: z.string(),
});

export const problemChoiceDtoSchema = z.object({
  no: z.number(),
  inst: z.string(),
});

export const cursorPaginateResponseChatResponseDtoSchema = z.object({
  items: z.array(chatResponseDtoSchema),
  next_cursor: z.string().nullable(),
});

export const dateValueDtoSchema = z.object({
  text: z.string(),
});

export const errorResponseDtoSchema = z.object({
  message: z.string(),
  detail: z.record(z.any()).optional().nullable(),
});

export const goalCreateRequestBodyDtoSchema = z.object({
  chat_id: z.number(),
  goal_count: z.number(),
});

export const goalResponseDtoSchema = z.object({
  id: z.number(),
  goal_count: z.number(),
  solved_count: z.number(),
});

export const validationErrorDtoSchema = z.object({
  loc: z.array(z.union([z.string(), z.number()])),
  msg: z.string(),
  type: z.string(),
});

export const imagesValueDtoSchema = z.object({
  sources: z.array(z.string()),
});

export const choiceProblemContentDtoSchema = z.object({
  subject: z.string(),
  grade: z.number(),
  semester: z.number().nullable(),
  level: z.number(),
  primary: z.string().nullable(),
  secondary: z.string().nullable(),
  specific: z.string().nullable(),
  category: z.string().nullable(),
  problem: z.string(),
  tags: z.array(z.string()).optional().nullable(),
  hint: z.string().nullable(),
  explanation: z.string().nullable(),
  choices: z.array(problemChoiceDtoSchema).optional().default([]),
});

export const shortAnswerProblemContentDtoSchema = z.object({
  subject: z.string(),
  grade: z.number(),
  semester: z.number().nullable(),
  level: z.number(),
  primary: z.string().nullable(),
  secondary: z.string().nullable(),
  specific: z.string().nullable(),
  category: z.string().nullable(),
  problem: z.string(),
  tags: z.array(z.string()).optional().nullable(),
  hint: z.string().nullable(),
  explanation: z.string().nullable(),
});

export const problemBookmarkChatResponseDtoSchema = z.object({
  id: z.number(),
  has_active_goal: z.boolean(),
});

export const problemBookmarkCheckResponseDtoSchema = z.object({
  status: problemDuplicateStatusDtoSchema,
});

export const problemBookmarkCreateRequestBodyDtoSchema = z.object({
  chat_id: z.number(),
  problem_id: z.string(),
  is_bookmarked: z.boolean(),
  bookmarked_at: z.string().optional().nullable(),
});

export const problemBookmarkCreateResponseDtoSchema = z.object({
  id: z.number(),
  chat_id: z.number(),
  problem_id: z.string(),
  is_bookmarked: z.boolean(),
  bookmarked_at: z.string().nullable(),
});

export const problemCreateAnswerRequestDtoSchema = z.object({
  answer: z.string(),
  accepted_answers: z.array(z.string()).optional().nullable(),
});

export const problemCreateChoiceRequestDtoSchema = z.object({
  no: z.number(),
  inst: z.string(),
});

export const problemCreateRequestDtoSchema = z.object({
  id: z.string(),
  subject: z.string(),
  grade: z.number(),
  type: z.string(),
  level: z.number(),
  url: z.string().nullable(),
  semester: z.number().nullable(),
  primary: z.string().nullable(),
  secondary: z.string().nullable(),
  specific: z.string().nullable(),
  category: z.string().nullable(),
  problem: z.string(),
  choices: z.array(problemCreateChoiceRequestDtoSchema).nullable(),
  correct_answers: z.array(problemCreateAnswerRequestDtoSchema),
  explanation: z.string().nullable(),
  hint: z.string().nullable(),
  tags: z.array(z.string()).nullable(),
});

export const problemCreateRequestBodyDtoSchema = z.object({
  problems: z.array(problemCreateRequestDtoSchema),
});

export const problemCreateResponseDtoSchema = z.object({
  ids: z.array(z.string()),
});

export const problemLinkValueDtoSchema = z.object({
  problem_id: z.string(),
});

export const problemQuoteSourceDtoSchema = z.object({
  type: z.literal('problem'),
  problem_id: z.string(),
});

export const problemRecommendedValueDtoSchema = z.object({
  problem_id: z.string(),
  category: z.string().nullable(),
  status: problemStatusDtoSchema,
});

export const quoteValueDtoSchema = z.object({
  text: z.string(),
  source: z.union([problemQuoteSourceDtoSchema, chatQuoteSourceDtoSchema]),
});

export const singleChoiceProblemResponseDtoSchema = z.object({
  id: z.string(),
  type: z.literal('\uB2E8\uC77C\uC120\uD0DD \uAC1D\uAD00\uC2DD'),
  content: choiceProblemContentDtoSchema,
});

export const singleShortAnswerProblemResponseDtoSchema = z.object({
  id: z.string(),
  type: z.literal('\uB2E8\uC77C\uC751\uB2F5 \uC8FC\uAD00\uC2DD'),
  content: shortAnswerProblemContentDtoSchema,
});

export const dateContentDtoSchema = z.object({
  m_type: z.literal('date'),
  value: dateValueDtoSchema,
});

export const textValueDtoSchema = z.object({
  text: z.string(),
});

export const toolValueDictDtoSchema = z.object({
  translation_button_visible: z.boolean().optional(),
});

export const unknownConceptCreateRequestBodyDtoSchema = z.object({
  subject: z.string(),
  key_concept: z.string(),
  unknown_concept: z.string(),
  unknown_concept_reason: z.string().optional().nullable(),
});

export const unknownConceptResponseDtoSchema = z.object({
  id: z.number(),
  subject: z.string(),
  key_concept: z.string(),
  unknown_concept: z.string(),
  unknown_concept_reason: z.string().optional().nullable(),
  created_at: z.string().datetime({ offset: true }),
  updated_at: z.string().datetime({ offset: true }),
});

export const uploadUrlRequestDtoSchema = z.object({
  mime_type: z.string(),
});

export const uploadUrlResponseDtoSchema = z.object({
  presigned_url: z.string(),
  file_url: z.string(),
});

export const userCreateRequestBodyDtoSchema = z.object({
  name: z.string(),
  grade: z.number(),
  memo: z.string().optional().nullable(),
});

export const userCreateResponseDtoSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  grade: z.number(),
  memo: z.string().nullable(),
});

export const userResponseDtoSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  grade: z.number(),
  memo: z.string().nullable(),
  created_at: z.string().datetime({ offset: true }),
  updated_at: z.string().datetime({ offset: true }),
});

export const userUpdateRequestBodyDtoSchema = z.object({
  name: z.string().optional().nullable(),
  grade: z.number().optional().nullable(),
  memo: z.string().optional().nullable(),
});

export const userUpdateResponseDtoSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  grade: z.number(),
  memo: z.string().nullable(),
});

export const getChatsChatsGetQueryParamsSchema = z.object({
  subject: z.array(subjectEnumDtoSchema).optional().nullable(),
  cursor: z.string().optional().nullable(),
  size: z.number().optional().default(10),
});

export const createProblemsProblemsPostHeadersSchema = z.object({
  'x-api-key': z.string().optional().nullable(),
});

export const uploadFileUploadsKeyPutQueryParamsSchema = z.object({
  expires: z.number(),
  signature: z.string(),
  mime: z.string(),
});

export const getProblemBookmarksProblemBookmarksGetQueryParamsSchema = z.object({
  subject: subjectEnumDtoSchema,
  status: z.array(problemStatusDtoSchema).optional().default([]),
  cursor: z.string().optional().nullable(),
  size: z.number().optional().default(10),
});

export const multipleChoiceProblemResponseDtoSchema = z.object({
  id: z.string(),
  type: z.literal('\uB2E4\uC911\uC120\uD0DD \uAC1D\uAD00\uC2DD'),
  content: choiceProblemContentDtoSchema,
});

export const multipleShortAnswerProblemResponseDtoSchema = z.object({
  id: z.string(),
  type: z.literal('\uB2E4\uC911\uC751\uB2F5 \uC8FC\uAD00\uC2DD'),
  content: shortAnswerProblemContentDtoSchema,
});

export const imagesContentDtoSchema = z.object({
  m_type: z.literal('images'),
  value: imagesValueDtoSchema,
});

export const problemLinkContentDtoSchema = z.object({
  m_type: z.literal('problem_link'),
  value: problemLinkValueDtoSchema,
});

export const problemRecommendedContentDtoSchema = z.object({
  m_type: z.literal('problem_recommended'),
  value: problemRecommendedValueDtoSchema,
});

export const quoteContentDtoSchema = z.object({
  m_type: z.literal('quote'),
  value: quoteValueDtoSchema,
});

export const textContentDtoSchema = z.object({
  m_type: z.literal('text'),
  value: textValueDtoSchema,
});

export const problemResponseDtoSchema = z.union([
  z
    .object({
      type: z.literal('\uB2E4\uC911\uC120\uD0DD \uAC1D\uAD00\uC2DD'),
    })
    .and(multipleChoiceProblemResponseDtoSchema),
  z
    .object({
      type: z.literal('\uB2E4\uC911\uC751\uB2F5 \uC8FC\uAD00\uC2DD'),
    })
    .and(multipleShortAnswerProblemResponseDtoSchema),
  z
    .object({
      type: z.literal('\uB2E8\uC77C\uC120\uD0DD \uAC1D\uAD00\uC2DD'),
    })
    .and(singleChoiceProblemResponseDtoSchema),
  z
    .object({
      type: z.literal('\uB2E8\uC77C\uC751\uB2F5 \uC8FC\uAD00\uC2DD'),
    })
    .and(singleShortAnswerProblemResponseDtoSchema),
]);

export const chatProblemSubmitRequestBodyDtoSchema = z.object({
  answer: z.union([
    z
      .object({
        type: z.literal('\uB2E4\uC911\uC120\uD0DD \uAC1D\uAD00\uC2DD'),
      })
      .and(multipleChoiceAnswerDtoSchema),
    z
      .object({
        type: z.literal('\uB2E4\uC911\uC751\uB2F5 \uC8FC\uAD00\uC2DD'),
      })
      .and(multipleShortAnswerDtoSchema),
    z
      .object({
        type: z.literal('\uB2E8\uC77C\uC120\uD0DD \uAC1D\uAD00\uC2DD'),
      })
      .and(singleChoiceAnswerDtoSchema),
    z
      .object({
        type: z.literal('\uB2E8\uC77C\uC751\uB2F5 \uC8FC\uAD00\uC2DD'),
      })
      .and(singleShortAnswerDtoSchema),
  ]),
});

export const hTTPValidationErrorDtoSchema = z.object({
  detail: z.array(validationErrorDtoSchema).optional(),
});

export const toolInfoDtoSchema = z.object({
  name: reActModelToolTypeDtoSchema,
  value: toolValueDictDtoSchema,
});

export const problemBookmarkChatProblemResponseDtoSchema = z.object({
  number: z.number(),
  status: problemStatusDtoSchema,
  last_answer: z.string().nullable(),
  problem_info: problemResponseDtoSchema,
});

export const problemBookmarkResponseDtoSchema = z.object({
  bookmarked_at: z.string().datetime({ offset: true }),
  chat: problemBookmarkChatResponseDtoSchema,
  problem: problemBookmarkChatProblemResponseDtoSchema,
});

export const messageMetadataResponseDtoSchema = z.object({
  tools: z.array(toolInfoDtoSchema).optional().default([]),
  system_hints: z.array(systemHintDtoSchema).optional().nullable(),
});

export const chatMessageCreateRequestBodyDtoSchema = z.object({
  contents: z.array(
    z.union([
      z
        .object({
          m_type: z.literal('images'),
        })
        .and(imagesContentDtoSchema),
      z
        .object({
          m_type: z.literal('problem_link'),
        })
        .and(problemLinkContentDtoSchema),
      z
        .object({
          m_type: z.literal('problem_recommended'),
        })
        .and(problemRecommendedContentDtoSchema),
      z
        .object({
          m_type: z.literal('quote'),
        })
        .and(quoteContentDtoSchema),
      z
        .object({
          m_type: z.literal('text'),
        })
        .and(textContentDtoSchema),
    ]),
  ),
  metadata: chatMessageMetadataRequestDtoSchema,
});

export const chatMessageResponseDtoSchema = z.object({
  id: z.number(),
  chat_id: z.number(),
  created_at: z.string().datetime({ offset: true }),
  type: z.literal('chat'),
  author: messageAuthorDtoSchema,
  contents: z.array(
    z.union([
      z
        .object({
          m_type: z.literal('images'),
        })
        .and(imagesContentDtoSchema),
      z
        .object({
          m_type: z.literal('problem_link'),
        })
        .and(problemLinkContentDtoSchema),
      z
        .object({
          m_type: z.literal('problem_recommended'),
        })
        .and(problemRecommendedContentDtoSchema),
      z
        .object({
          m_type: z.literal('quote'),
        })
        .and(quoteContentDtoSchema),
      z
        .object({
          m_type: z.literal('text'),
        })
        .and(textContentDtoSchema),
    ]),
  ),
  metadata: messageMetadataResponseDtoSchema,
});

export const chatProblemDetailResponseDtoSchema = z.object({
  number: z.number(),
  status: problemStatusDtoSchema,
  last_answer: z.string().nullable(),
  is_bookmarked: z.boolean(),
  problem_info: problemResponseDtoSchema,
});

export const cursorPaginateResponseProblemBookmarkResponseDtoSchema = z.object({
  items: z.array(problemBookmarkResponseDtoSchema),
  next_cursor: z.string().nullable(),
});

export const systemMessageResponseDtoSchema = z.object({
  id: z.number(),
  chat_id: z.number(),
  created_at: z.string().datetime({ offset: true }),
  type: z.literal('system'),
  author: messageAuthorDtoSchema,
  contents: z.array(
    z
      .object({
        m_type: z.literal('date'),
      })
      .and(dateContentDtoSchema),
  ),
  metadata: messageMetadataResponseDtoSchema,
});

export const messageListResponseDtoSchema = z.object({
  data: z.array(
    z.union([
      z
        .object({
          type: z.literal('chat'),
        })
        .and(chatMessageResponseDtoSchema),
      z
        .object({
          type: z.literal('system'),
        })
        .and(systemMessageResponseDtoSchema),
    ]),
  ),
});
