/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../pages/__root'
import { Route as StudentRouteRouteImport } from './../../pages/_student/route'
import { Route as IndexRouteImport } from './../../pages/index'
import { Route as LoginIndexRouteImport } from './../../pages/login/index'
import { Route as LoginUser_idRouteImport } from './../../pages/login/$user_id'
import { Route as StudentSubjectRouteRouteImport } from './../../pages/_student/$subject/route'
import { Route as StudentSubjectIndexRouteImport } from './../../pages/_student/$subject/index'
import { Route as StudentSubjectProblemsRouteImport } from './../../pages/_student/$subject/problems'
import { Route as StudentSubjectChatsRouteRouteImport } from './../../pages/_student/$subject/chats/route'
import { Route as StudentSubjectChatsIndexRouteImport } from './../../pages/_student/$subject/chats/index'
import { Route as StudentSubjectChatsMarkdownRouteImport } from './../../pages/_student/$subject/chats/markdown'
import { Route as StudentSubjectChatsHistoryRouteImport } from './../../pages/_student/$subject/chats/history'
import { Route as StudentSubjectChatsChat_idRouteRouteImport } from './../../pages/_student/$subject/chats/$chat_id/route'
import { Route as StudentSubjectProblemsBookmarkIndexRouteImport } from './../../pages/_student/$subject/problems/bookmark/index'
import { Route as StudentSubjectChatsChat_idProblemRouteRouteImport } from './../../pages/_student/$subject/chats/$chat_id/problem/route'

const StudentRouteRoute = StudentRouteRouteImport.update({
  id: '/_student',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginUser_idRoute = LoginUser_idRouteImport.update({
  id: '/login/$user_id',
  path: '/login/$user_id',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentSubjectRouteRoute = StudentSubjectRouteRouteImport.update({
  id: '/$subject',
  path: '/$subject',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentSubjectIndexRoute = StudentSubjectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentSubjectRouteRoute,
} as any)
const StudentSubjectProblemsRoute = StudentSubjectProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => StudentSubjectRouteRoute,
} as any)
const StudentSubjectChatsRouteRoute =
  StudentSubjectChatsRouteRouteImport.update({
    id: '/chats',
    path: '/chats',
    getParentRoute: () => StudentSubjectRouteRoute,
  } as any)
const StudentSubjectChatsIndexRoute =
  StudentSubjectChatsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StudentSubjectChatsRouteRoute,
  } as any)
const StudentSubjectChatsMarkdownRoute =
  StudentSubjectChatsMarkdownRouteImport.update({
    id: '/markdown',
    path: '/markdown',
    getParentRoute: () => StudentSubjectChatsRouteRoute,
  } as any)
const StudentSubjectChatsHistoryRoute =
  StudentSubjectChatsHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => StudentSubjectChatsRouteRoute,
  } as any)
const StudentSubjectChatsChat_idRouteRoute =
  StudentSubjectChatsChat_idRouteRouteImport.update({
    id: '/$chat_id',
    path: '/$chat_id',
    getParentRoute: () => StudentSubjectChatsRouteRoute,
  } as any)
const StudentSubjectProblemsBookmarkIndexRoute =
  StudentSubjectProblemsBookmarkIndexRouteImport.update({
    id: '/bookmark/',
    path: '/bookmark/',
    getParentRoute: () => StudentSubjectProblemsRoute,
  } as any)
const StudentSubjectChatsChat_idProblemRouteRoute =
  StudentSubjectChatsChat_idProblemRouteRouteImport.update({
    id: '/problem',
    path: '/problem',
    getParentRoute: () => StudentSubjectChatsChat_idRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$subject': typeof StudentSubjectRouteRouteWithChildren
  '/login/$user_id': typeof LoginUser_idRoute
  '/login': typeof LoginIndexRoute
  '/$subject/chats': typeof StudentSubjectChatsRouteRouteWithChildren
  '/$subject/problems': typeof StudentSubjectProblemsRouteWithChildren
  '/$subject/': typeof StudentSubjectIndexRoute
  '/$subject/chats/$chat_id': typeof StudentSubjectChatsChat_idRouteRouteWithChildren
  '/$subject/chats/history': typeof StudentSubjectChatsHistoryRoute
  '/$subject/chats/markdown': typeof StudentSubjectChatsMarkdownRoute
  '/$subject/chats/': typeof StudentSubjectChatsIndexRoute
  '/$subject/chats/$chat_id/problem': typeof StudentSubjectChatsChat_idProblemRouteRoute
  '/$subject/problems/bookmark': typeof StudentSubjectProblemsBookmarkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login/$user_id': typeof LoginUser_idRoute
  '/login': typeof LoginIndexRoute
  '/$subject/problems': typeof StudentSubjectProblemsRouteWithChildren
  '/$subject': typeof StudentSubjectIndexRoute
  '/$subject/chats/$chat_id': typeof StudentSubjectChatsChat_idRouteRouteWithChildren
  '/$subject/chats/history': typeof StudentSubjectChatsHistoryRoute
  '/$subject/chats/markdown': typeof StudentSubjectChatsMarkdownRoute
  '/$subject/chats': typeof StudentSubjectChatsIndexRoute
  '/$subject/chats/$chat_id/problem': typeof StudentSubjectChatsChat_idProblemRouteRoute
  '/$subject/problems/bookmark': typeof StudentSubjectProblemsBookmarkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_student': typeof StudentRouteRouteWithChildren
  '/_student/$subject': typeof StudentSubjectRouteRouteWithChildren
  '/login/$user_id': typeof LoginUser_idRoute
  '/login/': typeof LoginIndexRoute
  '/_student/$subject/chats': typeof StudentSubjectChatsRouteRouteWithChildren
  '/_student/$subject/problems': typeof StudentSubjectProblemsRouteWithChildren
  '/_student/$subject/': typeof StudentSubjectIndexRoute
  '/_student/$subject/chats/$chat_id': typeof StudentSubjectChatsChat_idRouteRouteWithChildren
  '/_student/$subject/chats/history': typeof StudentSubjectChatsHistoryRoute
  '/_student/$subject/chats/markdown': typeof StudentSubjectChatsMarkdownRoute
  '/_student/$subject/chats/': typeof StudentSubjectChatsIndexRoute
  '/_student/$subject/chats/$chat_id/problem': typeof StudentSubjectChatsChat_idProblemRouteRoute
  '/_student/$subject/problems/bookmark/': typeof StudentSubjectProblemsBookmarkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$subject'
    | '/login/$user_id'
    | '/login'
    | '/$subject/chats'
    | '/$subject/problems'
    | '/$subject/'
    | '/$subject/chats/$chat_id'
    | '/$subject/chats/history'
    | '/$subject/chats/markdown'
    | '/$subject/chats/'
    | '/$subject/chats/$chat_id/problem'
    | '/$subject/problems/bookmark'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login/$user_id'
    | '/login'
    | '/$subject/problems'
    | '/$subject'
    | '/$subject/chats/$chat_id'
    | '/$subject/chats/history'
    | '/$subject/chats/markdown'
    | '/$subject/chats'
    | '/$subject/chats/$chat_id/problem'
    | '/$subject/problems/bookmark'
  id:
    | '__root__'
    | '/'
    | '/_student'
    | '/_student/$subject'
    | '/login/$user_id'
    | '/login/'
    | '/_student/$subject/chats'
    | '/_student/$subject/problems'
    | '/_student/$subject/'
    | '/_student/$subject/chats/$chat_id'
    | '/_student/$subject/chats/history'
    | '/_student/$subject/chats/markdown'
    | '/_student/$subject/chats/'
    | '/_student/$subject/chats/$chat_id/problem'
    | '/_student/$subject/problems/bookmark/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudentRouteRoute: typeof StudentRouteRouteWithChildren
  LoginUser_idRoute: typeof LoginUser_idRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_student': {
      id: '/_student'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof StudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/$user_id': {
      id: '/login/$user_id'
      path: '/login/$user_id'
      fullPath: '/login/$user_id'
      preLoaderRoute: typeof LoginUser_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student/$subject': {
      id: '/_student/$subject'
      path: '/$subject'
      fullPath: '/$subject'
      preLoaderRoute: typeof StudentSubjectRouteRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/_student/$subject/': {
      id: '/_student/$subject/'
      path: '/'
      fullPath: '/$subject/'
      preLoaderRoute: typeof StudentSubjectIndexRouteImport
      parentRoute: typeof StudentSubjectRouteRoute
    }
    '/_student/$subject/problems': {
      id: '/_student/$subject/problems'
      path: '/problems'
      fullPath: '/$subject/problems'
      preLoaderRoute: typeof StudentSubjectProblemsRouteImport
      parentRoute: typeof StudentSubjectRouteRoute
    }
    '/_student/$subject/chats': {
      id: '/_student/$subject/chats'
      path: '/chats'
      fullPath: '/$subject/chats'
      preLoaderRoute: typeof StudentSubjectChatsRouteRouteImport
      parentRoute: typeof StudentSubjectRouteRoute
    }
    '/_student/$subject/chats/': {
      id: '/_student/$subject/chats/'
      path: '/'
      fullPath: '/$subject/chats/'
      preLoaderRoute: typeof StudentSubjectChatsIndexRouteImport
      parentRoute: typeof StudentSubjectChatsRouteRoute
    }
    '/_student/$subject/chats/markdown': {
      id: '/_student/$subject/chats/markdown'
      path: '/markdown'
      fullPath: '/$subject/chats/markdown'
      preLoaderRoute: typeof StudentSubjectChatsMarkdownRouteImport
      parentRoute: typeof StudentSubjectChatsRouteRoute
    }
    '/_student/$subject/chats/history': {
      id: '/_student/$subject/chats/history'
      path: '/history'
      fullPath: '/$subject/chats/history'
      preLoaderRoute: typeof StudentSubjectChatsHistoryRouteImport
      parentRoute: typeof StudentSubjectChatsRouteRoute
    }
    '/_student/$subject/chats/$chat_id': {
      id: '/_student/$subject/chats/$chat_id'
      path: '/$chat_id'
      fullPath: '/$subject/chats/$chat_id'
      preLoaderRoute: typeof StudentSubjectChatsChat_idRouteRouteImport
      parentRoute: typeof StudentSubjectChatsRouteRoute
    }
    '/_student/$subject/problems/bookmark/': {
      id: '/_student/$subject/problems/bookmark/'
      path: '/bookmark'
      fullPath: '/$subject/problems/bookmark'
      preLoaderRoute: typeof StudentSubjectProblemsBookmarkIndexRouteImport
      parentRoute: typeof StudentSubjectProblemsRoute
    }
    '/_student/$subject/chats/$chat_id/problem': {
      id: '/_student/$subject/chats/$chat_id/problem'
      path: '/problem'
      fullPath: '/$subject/chats/$chat_id/problem'
      preLoaderRoute: typeof StudentSubjectChatsChat_idProblemRouteRouteImport
      parentRoute: typeof StudentSubjectChatsChat_idRouteRoute
    }
  }
}

interface StudentSubjectChatsChat_idRouteRouteChildren {
  StudentSubjectChatsChat_idProblemRouteRoute: typeof StudentSubjectChatsChat_idProblemRouteRoute
}

const StudentSubjectChatsChat_idRouteRouteChildren: StudentSubjectChatsChat_idRouteRouteChildren =
  {
    StudentSubjectChatsChat_idProblemRouteRoute:
      StudentSubjectChatsChat_idProblemRouteRoute,
  }

const StudentSubjectChatsChat_idRouteRouteWithChildren =
  StudentSubjectChatsChat_idRouteRoute._addFileChildren(
    StudentSubjectChatsChat_idRouteRouteChildren,
  )

interface StudentSubjectChatsRouteRouteChildren {
  StudentSubjectChatsChat_idRouteRoute: typeof StudentSubjectChatsChat_idRouteRouteWithChildren
  StudentSubjectChatsHistoryRoute: typeof StudentSubjectChatsHistoryRoute
  StudentSubjectChatsMarkdownRoute: typeof StudentSubjectChatsMarkdownRoute
  StudentSubjectChatsIndexRoute: typeof StudentSubjectChatsIndexRoute
}

const StudentSubjectChatsRouteRouteChildren: StudentSubjectChatsRouteRouteChildren =
  {
    StudentSubjectChatsChat_idRouteRoute:
      StudentSubjectChatsChat_idRouteRouteWithChildren,
    StudentSubjectChatsHistoryRoute: StudentSubjectChatsHistoryRoute,
    StudentSubjectChatsMarkdownRoute: StudentSubjectChatsMarkdownRoute,
    StudentSubjectChatsIndexRoute: StudentSubjectChatsIndexRoute,
  }

const StudentSubjectChatsRouteRouteWithChildren =
  StudentSubjectChatsRouteRoute._addFileChildren(
    StudentSubjectChatsRouteRouteChildren,
  )

interface StudentSubjectProblemsRouteChildren {
  StudentSubjectProblemsBookmarkIndexRoute: typeof StudentSubjectProblemsBookmarkIndexRoute
}

const StudentSubjectProblemsRouteChildren: StudentSubjectProblemsRouteChildren =
  {
    StudentSubjectProblemsBookmarkIndexRoute:
      StudentSubjectProblemsBookmarkIndexRoute,
  }

const StudentSubjectProblemsRouteWithChildren =
  StudentSubjectProblemsRoute._addFileChildren(
    StudentSubjectProblemsRouteChildren,
  )

interface StudentSubjectRouteRouteChildren {
  StudentSubjectChatsRouteRoute: typeof StudentSubjectChatsRouteRouteWithChildren
  StudentSubjectProblemsRoute: typeof StudentSubjectProblemsRouteWithChildren
  StudentSubjectIndexRoute: typeof StudentSubjectIndexRoute
}

const StudentSubjectRouteRouteChildren: StudentSubjectRouteRouteChildren = {
  StudentSubjectChatsRouteRoute: StudentSubjectChatsRouteRouteWithChildren,
  StudentSubjectProblemsRoute: StudentSubjectProblemsRouteWithChildren,
  StudentSubjectIndexRoute: StudentSubjectIndexRoute,
}

const StudentSubjectRouteRouteWithChildren =
  StudentSubjectRouteRoute._addFileChildren(StudentSubjectRouteRouteChildren)

interface StudentRouteRouteChildren {
  StudentSubjectRouteRoute: typeof StudentSubjectRouteRouteWithChildren
}

const StudentRouteRouteChildren: StudentRouteRouteChildren = {
  StudentSubjectRouteRoute: StudentSubjectRouteRouteWithChildren,
}

const StudentRouteRouteWithChildren = StudentRouteRoute._addFileChildren(
  StudentRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudentRouteRoute: StudentRouteRouteWithChildren,
  LoginUser_idRoute: LoginUser_idRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
